### ISSUE TITLE
[Hope]: 改变群友ID颜色

### ISSUE THREAD

**Issue by SmallYii** [LiteLoaderQQNT/LiteLoaderQQNT#1029]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

默认的灰色实在看不清楚，尤其是和自定义背景融入之后
![image](https://github.com/user-attachments/assets/fad4069d-7456-47ed-8d91-7074834d8e1f)

**Comment by ne0-wu** [comment]
安装 transitio, 加上下面这个 css, 然后改成你想要的颜色
```css
.user-name.text-ellipsis {
    color: #FFFFFF;
}
```
