### ISSUE TITLE
[Bug]: QQ_9.9.16_241121_x64_01安装失败

### ISSUE THREAD

**Issue by kmizmal** [LiteLoaderQQNT/LiteLoaderQQNT#1037]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

QQ_9.9.16_241121_x64_01

### LiteLoaderQQNT 版本 （或 Commit Id）

LiteLoaderQQNT 1.2.3

### 运行环境

Windows

### 重现步骤

首次安装启动失败

### 期望的结果是什么？

成功进入QQ

### 实际的结果是什么？

![image](https://github.com/user-attachments/assets/f68c3895-8515-437c-92b7-036e9c67d5d6)

### 日志记录

![image](https://github.com/user-attachments/assets/fcb68f8f-a1f2-4789-81f0-854b99ec27f6)

**Comment by AnsolWteac** [comment]
自己下一个LiteLoaderQQNT然后放到指定路径就可以了，我是这么解决的

**Comment by kmizmal** [comment]
> 自己下一个LiteLoaderQQNT然后放到指定路径就可以了，我是这么解决的

我放在d盘根目录下，配置也没写错，
指定路径是什么

**Comment by AnsolWteac** [comment]
> > 自己下一个LiteLoaderQQNT然后放到指定路径就可以了，我是这么解决的
> 
> 我放在d盘根目录下，配置也没写错， 指定路径是什么

它上面不是写了么，在此路径没有找到liteloderqqnt模块，你放到他的路径就行了

**Comment by Psermoah** [comment]
![image](https://github.com/user-attachments/assets/f3537bd9-6480-46f3-81a9-b64c8832eb51)
  
从你的报错窗口来看，你在修改 `app/package.json` 文件中应该只修改了末尾的js文件路径，如图中红色标记所示。
在修改`app/package.json`文件中的`main`时应该删掉`/application.asar`，修改为：

  
![image](https://github.com/user-attachments/assets/22ba0ac4-7c59-4a94-acb2-2353ef65f37c)

**Comment by kmizmal** [comment]
> ![image](https://private-user-images.githubusercontent.com/64565551/395998432-f3537bd9-6480-46f3-81a9-b64c8832eb51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTc5MTEsIm5iZiI6MTczNDM1NzYxMSwicGF0aCI6Ii82NDU2NTU1MS8zOTU5OTg0MzItZjM1MzdiZDktNjQ4MC00NmYzLTgxYTktYjY0Yzg4MzJlYjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDE0MDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZTAwNzAwNDcyNzFjODliOGYwMDg2NzYxY2ZhMGE3NmQ4NTZjY2MyODIzOWFjZjBhOTVhN2Y2MjAzOTE0MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HlqFLyhev5QTjkcq1hp4yqj-ctybLn_TB2-JdH6vAxU)
> 
> 从你的报错窗口来看，你在修改 `app/package.json` 文件中应该只修改了末尾的js文件路径，如图中红色标记所示。 在修改`app/package.json`文件中的`main`时应该删掉`/application.asar`，修改为：
> 
> ![image](https://private-user-images.githubusercontent.com/64565551/395999053-22ba0ac4-7c59-4a94-acb2-2353ef65f37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTc5MTEsIm5iZiI6MTczNDM1NzYxMSwicGF0aCI6Ii82NDU2NTU1MS8zOTU5OTkwNTMtMjJiYTBhYzQtN2M1OS00YTk0LWFjYjItMjM1M2VmNjVmMzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDE0MDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYmU2MTA0MmI3NzZhMGY5ZjdkYTkyZTcyNmIxOTE5OWY4M2JjZGQ0MWRjYzc3ZTgyYzZhNDJmNzQ2Y2EzYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qcS7NI-o-nyajJX6sCd4awwA7Hihc4JJgXJfW8xsdS4)

感谢回复，确实是这个问题
我开始只是把index.js改为了nt.js,没注意前面多了东西
