### ISSUE TITLE
[Feat]: 希望可以拦截 QQ 显示登录失效的问题

### ISSUE THREAD

**Issue by tianxiu2b2t** [LiteLoaderQQNT/LiteLoaderQQNT#1043]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

![image](https://github.com/user-attachments/assets/1ac4c14b-5c2a-443e-b274-102279609df9)
貌似有人说是上报环境的问题（含有LiteLoaderQQNT？）
版本为
LiteLoader 1.2.3
QQNT 9.9.17-30594
Electron 31.1.0
Chromium 126.0.6478.36
Nodejs 20.14.0

**Comment by Kroytz** [comment]
同，我自测回退的老版本很稳定，当前最新版会有这个问题

**Comment by tianxiu2b2t** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/1032
已有 issue
