### ISSUE TITLE
启动速度疑问

### ISSUE THREAD

**Issue by HsJohnY** [LiteLoaderQQNT/LiteLoaderQQNT#1048]
在启动QQ后大约7-8s才能弹出登录窗口，后台无任务，请问这种情况正常吗。
基本环境为：Windows11， QQ9.9.17-30899 (64位)，LiteLoader为最新release版本，只装有轻量工具箱

**Comment by jhqwqmc** [comment]
可以去看看`\Tencent Files\你qq号\nt_qq\nt_db\msg_fts.db-wal`这个文件是不是太大了，如果关闭qq后非常大超过1gb直接删掉就好了，可能会丢失一部分的聊天信息，我之前这个问题达到了50g卡得都快动不了了，删掉后丢失了2个星期的聊天数据，但是qq也恢复正常了
