### ISSUE TITLE
-

### ISSUE THREAD

**Issue by mcTinLin** [LiteLoaderQQNT/LiteLoaderQQNT#1052]
-

**Comment by MKStoler4096** [comment]
@mcTinLin 发现一个 typo: 尾部的 360 打成了 160

**Comment by mcTinLin** [comment]
> @mcTinLin 发现一个 typo: 尾部的 360 打成了 160

已经修改了，谢谢指导！

**Comment by qingshujun** [comment]
安装360，呵呵了。

**Comment by TianMengLucky** [comment]
geek 之类的软件也能卸载干净，360就是最大的广告病毒

**Comment by zxxvscs** [comment]
这有啥用 卸载插件 重装QQ就正常登录 为什么还要做这些额外无用功呢？我的号就是这么显示的 重装QQ后一点事都没有

**Comment by kiriYui0** [comment]
有这么麻烦吗....用everything把你盘里所有liteloader删了就好了
