### ISSUE TITLE
[Feat]: 插件市场网络代理

### ISSUE THREAD

**Issue by am-abudu** [LiteLoaderQQNT/LiteLoaderQQNT#108]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

更新/安装插件时可以选择使用Proxy，防止因为网络问题的更新/安装失败

**Comment by mo-jinran** [comment]
插件市场早就用了ghproxy代理加速国内访问，你的意思是像 [优先github，其次代理](https://github.com/mo-jinran/LiteLoaderQQNT-Plugins-Marketplace/pull/14) 吗？

**Comment by am-abudu** [comment]
> 插件市场早就用了ghproxy代理加速国内访问，你的意思是像 [优先github，其次代理](https://github.com/mo-jinran/LiteLoaderQQNT-Plugins-Marketplace/pull/14) 吗？

希望可以自行设置使用镜像/Github/使用Http Proxy。因为无法保证镜像是否一直可用。

**Comment by yige-yigeren** [comment]
> 插件市场早就用了ghproxy代理加速国内访问，你的意思是像 [优先github，其次代理](https://github.com/mo-jinran/LiteLoaderQQNT-Plugins-Marketplace/pull/14) 吗？

其实默认github，然后连接可选ghproxy或者自己定义可能会好一些

**Comment by mo-jinran** [comment]
> > 插件市场早就用了ghproxy代理加速国内访问，你的意思是像 [优先github，其次代理](https://github.com/mo-jinran/LiteLoaderQQNT-Plugins-Marketplace/pull/14) 吗？
> 
> 其实默认github，然后连接可选ghproxy或者自己定义可能会好一些

从插件市场第一版开始就有此功能，你需要编辑配置文件实现自定义源

**Comment by LittleNightmare** [comment]
> 其实默认github，然后连接可选ghproxy或者自己定义可能会好一些

有一说一，刚写完就发现应该这么改。但想了想，不确定这个ui交互怎么弄，就摆了，等待有缘人继续

**Comment by xh321** [comment]
目前最新版已经实现，可以自定义http/socks代理，自定义镜像源仍在规划中，请等待
