### ISSUE TITLE
[Feat]: 增加一个安全模式功能用于插件排错

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [LiteLoaderQQNT/LiteLoaderQQNT#122]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

每次启动自动生成一个lck锁文件，正常退出时删除。启动时如果检测到锁文件因为崩溃没有被删除会切换到不加载任何插件的安全模式，方便检测哪个插件有问题。
![image](https://github.com/mo-jinran/LiteLoaderQQNT/assets/65578116/ff8c219f-76ed-4022-9430-0671a65e9e38)

**Comment by CreeperAWA** [comment]
最好也可以手动启动安全模式
