### ISSUE TITLE
[Bug]: Mac App Store 版 QQNT 上的 bug

### ISSUE THREAD

**Issue by Ripening** [LiteLoaderQQNT/LiteLoaderQQNT#130]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.19-16183（Mac App Store 截止北京时间 8 月 23 日 09:34 的最新版本）

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.2

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

**前排提示：建议先重新安装一个干净的 QQNT 再尝试进行操作。**

在初次安装 llqqnt 后启动后会出现一个弹窗警告：
<img width="372" alt="启动时警告" src="https://github.com/mo-jinran/LiteLoaderQQNT/assets/66284192/01a3dc73-3279-4c40-a6cd-e1feb89b8034">

---

点击其中任意一个按钮后可以正常进入 QQNT，然后尝试使用 command-Q 退出 QQNT 可是没有用，第二次按会关闭窗口，可是此时 QQ 的进程依然存在，同时 Dock 栏上的小黑点也存在，点击 Dock 栏上的 QQ 图标再按 command-Q 即可彻底退出。

**上述退出 QQNT 的操作有小概率会导致 QQNT 未响应。**

### 期望的结果是什么？

已经写到上面了。

### 实际的结果是什么？

我的环境是：

M1 MacBook Air 8 + 256GB，macOS 12.6.8，llqqnt 配置界面如下：
<img width="952" alt="llqqnt 配置界面" src="https://github.com/mo-jinran/LiteLoaderQQNT/assets/66284192/7e643b6d-d995-4458-8922-3c46a1f306b8">

然后重现步骤中第二个操作 100% 复现，第一个操作在重新安装 QQNT 后安装 llqqnt 会 100% 复现。**不保证在其他设备上会复现。**

### 补充说明（可选）

**如果抛开这 2 个 bug 其实也是可以正常使用的。**

**Comment by bruceCzK** [comment]
同样遇到此问题，系统是13.4，x86架构的。导致第三方插件完全不可用。

**Comment by FredLin5** [comment]
不要移动到废纸篓
尝试在终端输入`sudo spctl --master-disable` 并且确认系统设置里的`隐私与安全性->安全性`中选中`任何来源`
至于需要退出3次才能完全退出这个是现在版本的一个一直bug

**Comment by EraserCN** [comment]
[FuckTencent.app.zip](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12546209/FuckTencent.app.zip)
我写了一个脚本用于一键关闭QQ，你可以先用着看看。

**Comment by mo-jinran** [comment]
新版本已修复，具体查看官网：https://liteloaderqqnt.github.io/
