### ISSUE TITLE
[Bug]: Linux 下部分侧边栏按钮点击即崩溃

### ISSUE THREAD

**Issue by LynxCatTheThird** [LiteLoaderQQNT/LiteLoaderQQNT#137]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

AUR 包 linuxqq（版本号 2:3.2.0_16449-2），关于内可见“版本: 3.2.0-16449”

### LiteLoaderQQNT 版本 （或 Commit Id）

AUR 包 liteloader-qqnt-bin（版本号0.5.3-1）

### 运行环境

ArchLinux

### 运行架构

AMD64

### 重现步骤

1. 启动并登录 LinuxQQ
2. 点击侧边栏上除了消息、联系人、侧边栏管理、收藏之外的按钮
3. 需要调用浏览器的能够正常的调用浏览器，但 LinuxQQ 随之崩溃；QQNT 内置的界面打不开
4. LinuxQQ 自动重启进入登录界面

### 期望的结果是什么？

这些页面都能打开且不崩溃

### 实际的结果是什么？

需要调用浏览器的能够正常的调用浏览器，但 LinuxQQ 随之崩溃；QQNT 内置的界面打不开

### 日志记录

[install.txt](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12450691/install.txt)
[qqnt.txt](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12450727/qqnt.txt)
[packages.txt](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12450754/packages.txt)
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/dc7d540b-ccca-437b-87ac-7a432488b98f)

**Comment by mo-jinran** [comment]
新版本已修复，具体查看官网：https://liteloaderqqnt.github.io/
