### ISSUE TITLE
[Bug]: Linux 系统下无限闪退

### ISSUE THREAD

**Issue by Ocyss** [LiteLoaderQQNT/LiteLoaderQQNT#139]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

aur/linuxqq-nt-bwrap 3.2.0_16449-1

### LiteLoaderQQNT 版本 （或 Commit Id）

aur/liteloader-qqnt-bin 0.5.3-1

### 运行环境

ArchLinux

### 运行架构

AMD64

### 重现步骤

bwrap 环境已配置 --setenv LITELOADERQQNT_PROFILE "${QQ_APP_DIR}/LiteLoaderQQNT"

刚安装完并没闪退,点击设置菜单后开始,无限闪退具体如下
> 开了自动登录,进入主界面就闪退,然后自动重启继续自动登录一直反复,平均1秒登录闪退一次

手动 rm -rf ~/.config/QQ/crash_files  ~/.config/QQ/log
闪退现象消除,多次测试会触发的操作: 切换桌面,点击频道,小世界(文档与QQ空间,邮箱点不动),文件管理,设置

### 期望的结果是什么？

正常使用

### 实际的结果是什么？

闪退

### 日志记录

命令行日志:
```
version_config_filename :/home/ocyss/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/electron /opt/QQ/resources/resources/app/package.json
config_build_id :16449
config_base_version :3.2.0-16449
config_current_version :3.2.0-16449
app_build_version :
version_config_filename :/home/ocyss/.config/QQ/versions/config.json
version_config_filename :/home/ocyss/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :16449
config_base_version :3.2.0-16449
config_current_version :3.2.0-16449
app_build_version :16449
config_build_id :16449
config_base_version :3.2.0-16449
config_current_version :3.2.0-16449
app_build_version :16449
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at /opt/QQ.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Done! 3 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[2023/8/29 02:08:24][INFO] /home/ocyss/.config/QQ/versions/config.json 存在

[2023/8/29 02:08:24][INFO] /home/ocyss/.config/QQ/versions/3.2.0-16449.zip 不存在，无法执行解压操作

[2023/8/29 02:08:24][INFO] 从安装目录加载主进程代码: /opt/QQ/resources/app/application/background.js

[2023/8/29 02:08:24][INFO]
---------- 华丽的分割线 ----------



[2:0829/020824.194430:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[2:0829/020824.194484:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
ElectronRendererClient::DidCreateScriptContext
[49:0829/020826.263445:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
linux-bugly: init bugly ...
[BuglyManager.cpp][InitBuglyManager][198]InitBuglyManager path: /home/ocyss/.config/QQ/crash_files/
[BuglyService.cpp][CreatDir][70]!!!begin to CreatDir 0: /home/ocyss/.config/QQ/crash_files/
[BuglyService.cpp][registBugly][589]set signal stack
[BuglyService.cpp][registSignalHandler][520]regist native handler
[BuglyService.cpp][setParam][618]setParam, key:appVersion, value:3.2.0-16449..
linux-bugly: init bugly done.
ElectronRendererClient::DidCreateScriptContext
ElectronRendererClient::DidCreateScriptContext
[49:0829/020829.519802:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
02:08:31.087 › [hot update] hotUpdateApi checkHasMultipleQQ true
02:08:31.129 › [hot update] hotUpdateApi checkHasMultipleQQ true
02:08:31.130 › [hot update] hotUpdateApi checkIsOnErrorVersion 3.1.2-13107
02:08:31.130 › [hot update] hotUpdateApi checkIsOnErrorVersion res is false
[49:0829/020831.165570:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

QQ log目录日志(闪退两次):
```
[2023/8/29 02:08:34][INFO] /home/ocyss/.config/QQ/versions/config.json 存在
[2023/8/29 02:08:34][INFO] /home/ocyss/.config/QQ/versions/3.2.0-16449.zip 不存在，无法执行解压操作
[2023/8/29 02:08:34][INFO] 从安装目录加载主进程代码: /opt/QQ/resources/app/application/background.js
[2023/8/29 02:08:34][INFO] 
---------- 华丽的分割线 ----------


[2023/8/29 02:08:39][INFO] /home/ocyss/.config/QQ/versions/config.json 存在
[2023/8/29 02:08:39][INFO] /home/ocyss/.config/QQ/versions/3.2.0-16449.zip 不存在，无法执行解压操作
[2023/8/29 02:08:39][INFO] 从安装目录加载主进程代码: /opt/QQ/resources/app/application/background.js
[2023/8/29 02:08:39][INFO] 
---------- 华丽的分割线 ----------
```

**Comment by mathematics128** [comment]
+1，qqnt版本 aur/linuxqq 2:3.2.0_16449-2，其余相同

**Comment by mathematics128** [comment]
补充：将`package.json`中`main`键值替换为`./app_launcher/index.js`之后，QQ干脆无法启动，一点击登录即闪退。

也许是QQ官方的问题

**Comment by tehcneko** [comment]
#139

**Comment by zhanghua000** [comment]
自行基于 com.qq.QQ 打包的 flatpak 版本，一样的问题，但仅限于点击菜单中的“关于”、“设置”选项和“系统门户”弹出的“QQ 正在运行”的提示的关闭按钮时闪退，下次重启后仍然正常工作，可以收发消息，但点击上述按钮时仍然会闪退。
打包 flatpak 时用到的清单：
[com.qq.QQWithLiteloader.tar.gz](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12505367/com.qq.QQWithLiteloader.tar.gz)
从启动到崩溃时的终端输出：
[crash.log](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12505377/crash.log)

**Comment by tehcneko** [comment]
> 自行基于 com.qq.QQ 打包的 flatpak 版本，一样的问题，但仅限于点击菜单中的“关于”、“设置”选项和“系统门户”弹出的“QQ 正在运行”的提示的关闭按钮时闪退，下次重启后仍然正常工作，可以收发消息，但点击上述按钮时仍然会闪退。 打包 flatpak 时用到的清单： [com.qq.QQWithLiteloader.tar.gz](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12505367/com.qq.QQWithLiteloader.tar.gz) 从启动到崩溃时的终端输出： [crash.log](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12505377/crash.log)

QQ 没有崩溃，是发现修改后自己退出的

**Comment by zhanghua000** [comment]
> > 自行基于 com.qq.QQ 打包的 flatpak 版本，一样的问题，但仅限于点击菜单中的“关于”、“设置”选项和“系统门户”弹出的“QQ 正在运行”的提示的关闭按钮时闪退，下次重启后仍然正常工作，可以收发消息，但点击上述按钮时仍然会闪退。 打包 flatpak 时用到的清单： [com.qq.QQWithLiteloader.tar.gz](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12505367/com.qq.QQWithLiteloader.tar.gz) 从启动到崩溃时的终端输出： [crash.log](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12505377/crash.log)
> 
> QQ 没有崩溃，是发现修改后自己退出的

那么这种问题的应对方法是啥呢？我看 README 里面没有给出 Linux 反检测的办法

**Comment by tehcneko** [comment]
> > > 自行基于 com.qq.QQ 打包的 flatpak 版本，一样的问题，但仅限于点击菜单中的“关于”、“设置”选项和“系统门户”弹出的“QQ 正在运行”的提示的关闭按钮时闪退，下次重启后仍然正常工作，可以收发消息，但点击上述按钮时仍然会闪退。 打包 flatpak 时用到的清单： [com.qq.QQWithLiteloader.tar.gz](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12505367/com.qq.QQWithLiteloader.tar.gz) 从启动到崩溃时的终端输出： [crash.log](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12505377/crash.log)
> > 
> > 
> > QQ 没有崩溃，是发现修改后自己退出的
> 
> 那么这种问题的应对方法是啥呢？我看 README 里面没有给出 Linux 反检测的办法

没有，其他平台也上了检测 #147

**Comment by mo-jinran** [comment]
已修复，请安装最新版LiteLoaderQQNT，官网：https://liteloaderqqnt.github.io/
