### ISSUE TITLE
[Bug]: Windows11下按照文档操作会报错

### ISSUE THREAD

**Issue by StephenJose-Dai** [LiteLoaderQQNT/LiteLoaderQQNT#140]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
2、使用x64的exe，放到QQ.exe同级下

### 期望的结果是什么？

防撤回

### 实际的结果是什么？

QQ文件已损坏

**Comment by Beelkic** [comment]
同，附上错误代码
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/34309188/79f22da5-c666-42ce-ad57-7365824c2046)

**Comment by pz328** [comment]
重现步骤
1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹

对于 Windows QQNT 9.9.1 版本（除 15717 版本外）以上
使用 Launcher （闭源软件）：

若你之前修改过package.json，请将被修改的 package.json 文件内容还原（必须跟QQ原始的文件一样），如果无法恢复建议重装一次QQ

**Comment by jdfcc** [comment]
> 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> 
> Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> 
> 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ

放在app目录下的不应该是压缩包而是压缩包解压后的文件

**Comment by StephenJose-Dai** [comment]
> > 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> > Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> > 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ
> 
> 放在app目录下的不应该是压缩包而是压缩包解压后的文件

已经解压过了

**Comment by jdfcc** [comment]
> > > 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> > > Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> > > 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ
> > 
> > 
> > 放在app目录下的不应该是压缩包而是压缩包解压后的文件
> 
> 已经解压过了

你的qq版本是不需要修改package.json文件的。[安装矩阵](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT#%E6%94%AF%E6%8C%81%E7%9F%A9%E9%98%B5)

**Comment by jdfcc** [comment]
> > > 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> > > Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> > > 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ
> > 
> > 
> > 放在app目录下的不应该是压缩包而是压缩包解压后的文件
> 
> 已经解压过了

你的qq版本是不需要修改package.json文件的。[安装矩阵](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT#%E6%94%AF%E6%8C%81%E7%9F%A9%E9%98%B5)

**Comment by StephenJose-Dai** [comment]
> > > > 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> > > > Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> > > > 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ
> > > 
> > > 
> > > 放在app目录下的不应该是压缩包而是压缩包解压后的文件
> > 
> > 
> > 已经解压过了
> 
> 你的qq版本是不需要修改package.json文件的。[安装矩阵](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT#%E6%94%AF%E6%8C%81%E7%9F%A9%E9%98%B5)

我尝试过使用release那个exe工具，还是一样的错误，我看到那个工具似乎是自动帮我修改的json

**Comment by jdfcc** [comment]
> > > > > 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> > > > > Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> > > > > 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ
> > > > 
> > > > 
> > > > 放在app目录下的不应该是压缩包而是压缩包解压后的文件
> > > 
> > > 
> > > 已经解压过了
> > 
> > 
> > 你的qq版本是不需要修改package.json文件的。[安装矩阵](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT#%E6%94%AF%E6%8C%81%E7%9F%A9%E9%98%B5)
> 
> 我尝试过使用release那个exe工具，还是一样的错误，我看到那个工具似乎是自动帮我修改的json

正常来说按照你的qq版本将littleloader解压至目标目录后使用提供的launcher在qq.exe所在的文件夹直接启动就可以使用了，不需要使用提供的脚本或者手动对package.json做任何修改

**Comment by StephenJose-Dai** [comment]
> > > > > > 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> > > > > > Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> > > > > > 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ
> > > > > 
> > > > > 
> > > > > 放在app目录下的不应该是压缩包而是压缩包解压后的文件
> > > > 
> > > > 
> > > > 已经解压过了
> > > 
> > > 
> > > 你的qq版本是不需要修改package.json文件的。[安装矩阵](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT#%E6%94%AF%E6%8C%81%E7%9F%A9%E9%98%B5)
> > 
> > 
> > 我尝试过使用release那个exe工具，还是一样的错误，我看到那个工具似乎是自动帮我修改的json
> 
> 正常来说按照你的qq版本将littleloader解压至目标目录后使用提供的launcher在qq.exe所在的文件夹直接启动就可以使用了，不需要使用提供的脚本或者手动对package.json做任何修改

>是的，我尝试这么做，但似乎不生效

**Comment by jdfcc** [comment]
> > > > > > > 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> > > > > > > Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> > > > > > > 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ
> > > > > > 
> > > > > > 
> > > > > > 放在app目录下的不应该是压缩包而是压缩包解压后的文件
> > > > > 
> > > > > 
> > > > > 已经解压过了
> > > > 
> > > > 
> > > > 你的qq版本是不需要修改package.json文件的。[安装矩阵](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT#%E6%94%AF%E6%8C%81%E7%9F%A9%E9%98%B5)
> > > 
> > > 
> > > 我尝试过使用release那个exe工具，还是一样的错误，我看到那个工具似乎是自动帮我修改的json
> > 
> > 
> > 正常来说按照你的qq版本将littleloader解压至目标目录后使用提供的launcher在qq.exe所在的文件夹直接启动就可以使用了，不需要使用提供的脚本或者手动对package.json做任何修改
> 
> > 是的，我尝试这么做，但似乎不生效

建议你查看你的package.json是否已经被修改或者重装qqnt

**Comment by StephenJose-Dai** [comment]
> > > > > > > > 删除步骤 1、下载zip，放到app下，修改package.json中的main指向LiteLoader文件夹
> > > > > > > > Windows QQNT 9.9.1版本（除15717版本外）以上 使用Launcher（闭源软件）：
> > > > > > > > 如果您之前修改过package.json，则须被修改的package.json文件内容（必须与QQ原始的文件一样），如果无法恢复建议重装一次QQ
> > > > > > > 
> > > > > > > 
> > > > > > > 放在app目录下的不应该是压缩包而是压缩包解压后的文件
> > > > > > 
> > > > > > 
> > > > > > 已经解压过了
> > > > > 
> > > > > 
> > > > > 你的qq版本是不需要修改package.json文件的。[安装矩阵](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT#%E6%94%AF%E6%8C%81%E7%9F%A9%E9%98%B5)
> > > > 
> > > > 
> > > > 我尝试过使用release那个exe工具，还是一样的错误，我看到那个工具似乎是自动帮我修改的json
> > > 
> > > 
> > > 正常来说按照你的qq版本将littleloader解压至目标目录后使用提供的launcher在qq.exe所在的文件夹直接启动就可以使用了，不需要使用提供的脚本或者手动对package.json做任何修改
> > 
> > 
> > > 是的，我尝试这么做，但似乎不生效
> 
> 建议你查看你的package.json是否已经被修改或者重装qqnt

执行了你的工具是会被修改，打不开，我再给改回来就又能打开，100%复现

**Comment by xh321** [comment]
建议完全卸载QQ，然后重新安装QQ与框架，解压LiteLoaderQQNT后（一定要确保解压路径正确），直接使用https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer/releases来修补QQ（不要用其他办法和工具），只需要这一个工具，处理好后就能直接打开
