### ISSUE TITLE
[Bug]: 9.9.2-16605 闪退

### ISSUE THREAD

**Issue by lancloud1** [LiteLoaderQQNT/LiteLoaderQQNT#147]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16605

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

触发方式1：登录QQ后切换到其它窗口
触发方式2：登录后打开设置

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

qq闪退后自动重启qq

### 日志记录

[2023/9/2 14:55:10][INFO] D:\Program Files\Tencent\QQNT\resources\app\versions\config.json 存在
[2023/9/2 14:55:10][INFO] D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-16605.zip 不存在，无法执行解压操作
[2023/9/2 14:55:10][INFO] 从版本目录加载主进程代码: D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-16605\application\background.js, {
  "curVersion": "9.9.2-16605",
  "mainProcessFileName": "application\\background.js"
}
[2023/9/2 14:55:10][INFO] 
---------- 华丽的分割线 ----------

**Comment by cancundeyingzi** [comment]
我是第一次启动正常,装了插件然后死了
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/73635883/d1ab849e-4b72-400d-8221-ae8744443e9d)

**Comment by WindLeaf233** [comment]
同样的问题，版本 `9.9.2-16605`，使用的 `patch` 方法。

补充一下日志：
```
[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at F:\QQNT.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Done! 3 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[2023/9/2 19:15:44][INFO] F:\QQNT\resources\app\versions\config.json 存在
[2023/9/2 19:15:44][INFO] F:\QQNT\resources\app\versions\9.9.2-16605.zip 不存在，无法执行解压操作
[2023/9/2 19:15:44][INFO] 从版本目录加载主进程代码: F:\QQNT\resources\app\versions\9.9.2-16605\application\background.js, {
  "curVersion": "9.9.2-16605",
  "mainProcessFileName": "application\\background.js"
}
[2023/9/2 19:15:44][INFO]
---------- 华丽的分割线 ----------
[12732:0902/191552.761:ERROR:ssl_client_socket_impl.cc(978)] handshake failed; returned -1, SSL error code 1, net_error -100
19:15:53.283 > [hot update] hotUpdateApi checkHasMultipleQQ false
19:15:53.285 > [hot update] hotUpdateApi start clearOldVersions
19:15:53.286 > [hot update] hotUpdateApi curVersionZipPath is: F:\QQNT\resources\app\versions\9.9.2-16605.zip false
19:15:53.390 > [hot update] hotUpdateApi checkHasMultipleQQ false
19:15:53.391 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.2-16183
19:15:53.392 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
```

**Comment by xxtg666** [comment]
同样问题，版本 `9.9.2-16605` 用 `Launcher` 方法，闪退后会重启到官方版qq。

**Comment by zhulinyv** [comment]
同样问题，版本 9.9.2-16605 用 Launcher 方法，闪退后会重启到官方版qq。

**Comment by Amor-ai** [comment]
同样问题，版本 9.9.2-16605 用 Launcher 方法，闪退后会重启到官方版qq

**Comment by Fay-114** [comment]
同样问题，版本 9.9.2-16605 用 Launcher 方法，闪退后会重启到官方版qq。

**Comment by WindLeaf233** [comment]
有同样问题的别复制粘贴回帖了，回帖请回复一些有参考价值的内容。

点个通知订阅有更新会邮件通知你的。桌面端右上角，手机端最下面，点一下 `Subscribe` 按钮就行了。

一天给我发好几个邮件我还以为有什么进展了，结果点进来一看都在复读......

**Comment by tehcneko** [comment]
139

**Comment by Ouroboros** [comment]
刚刚手贱更新, 16605不能用, 我退回16183了, 现在还能下载

https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe

**Comment by hideonbush-cell** [comment]
> 刚刚手贱更新, 16605不能用, 我退回16183了, 现在还能下载
> 
> https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe

<img width="444" alt="image" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/68937832/63110fdc-b059-42a4-a780-db6f436c6eaa">
这网站进不去

**Comment by ijrou** [comment]
还好我每次升级都进github上看看提交的代码有没有更新到支持最新版本~~~

继续用我的16183了

**Comment by LYkcul** [comment]
版本 9.9.2-16736 用 patch 方法，启动qq会闪退。

**Comment by shiyihang2007** [comment]
抱歉，我正在睡觉，请勿打扰。

**Comment by xh321** [comment]
目前暂时最高支持到16183
