### ISSUE TITLE
[Bug]: macOS安装后正常方式关闭QQ会卡20秒

### ISSUE THREAD

**Issue by EraserCN** [LiteLoaderQQNT/LiteLoaderQQNT#149]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.19

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

从Dock关闭QQ，或者Command+Q关闭QQ

### 期望的结果是什么？

QQ直接关闭

### 实际的结果是什么？

QQ会卡住20秒才退出

### 日志记录

默认	14:40:33.177874+0800	QQ	Handling Quit AppleEvent
默认	14:40:33.178240+0800	QQ	Checking whether app should terminate
默认	14:40:33.178983+0800	QQ	Asking app delegate whether applicationShouldTerminate:
默认	14:40:33.179068+0800	QQ	replyToApplicationShouldTerminate:YES
默认	14:40:33.179241+0800	QQ	App termination approved
默认	14:40:36.207145+0800	QQ	nw_path_libinfo_path_check 
	libinfo check path: satisfied (Path is satisfied), interface: utun10, ipv4, ipv6, dns
默认	14:40:40.141865+0800	QQ	Handling Quit AppleEvent
默认	14:40:40.141993+0800	QQ	Checking whether app should terminate
默认	14:40:40.142240+0800	QQ	Asking app delegate whether applicationShouldTerminate:
默认	14:40:40.142272+0800	QQ	replyToApplicationShouldTerminate:YES
默认	14:40:40.142378+0800	QQ	App termination approved
默认	14:40:40.151379+0800	QQ	window ElectronNSWindow 550b windowShouldClose: prevented close
默认	14:40:40.156470+0800	QQ	order window: 5503 op: 0 relative: 0 related: 0
默认	14:40:40.156893+0800	QQ	window ElectronNSWindow 5503 windowShouldClose: prevented close
默认	14:40:40.156923+0800	QQ	window ElectronNSWindow 5503 windowShouldClose: prevented close
默认	14:40:40.157104+0800	QQ	void _updateToReflectAutomaticTerminationState(void) Setting _kLSApplicationWouldBeTerminatedByTALKey=1
默认	14:40:40.163826+0800	QQ	window ElectronNSWindow 550b finishing close
默认	14:40:40.164056+0800	QQ	nw_path_evaluator_cancel cancel
默认	14:40:40.166284+0800	QQ	order window: 550b op: 0 relative: 0 related: 0
默认	14:40:40.171179+0800	QQ	window ElectronNSWindow 5503 finishing close
默认	14:40:40.176256+0800	QQ	order window: 5503 op: 0 relative: 0 related: 0
默认	14:40:40.179836+0800	QQ	[0x13001ded480] invalidated on xpc_connection_cancel()
默认	14:40:40.179897+0800	QQ	[0x13002359380] invalidated on xpc_connection_cancel()
默认	14:40:43.166217+0800	QQ	nw_path_libinfo_path_check
	libinfo check path: satisfied (Path is satisfied), interface: utun10, ipv4, ipv6, dns

### 补充说明（可选）

无

**Comment by EraserCN** [comment]
[FuckTencent.app.zip](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12546198/FuckTencent.app.zip)
写了一个可以多次重复执行关闭QQ命令的脚本，应该能解决此问题。已使用开发签签名，可以直接运行。

**Comment by FredLin5** [comment]
是会卡住一段时间后才能退出还是需要连续退出3次？
如果是后者，这是因为QQ检测到修改会自杀，LiteLoader阻止了QQ自杀导致无法一次性退出

**Comment by EraserCN** [comment]
我选择退出后无反应，再按一次退出后QQ界面退出但Dock显示未关闭，再按一次退出才能完全退出

**Comment by FredLin5** [comment]
已知问题，目前可以直接连敲三次cmd+Q来退出

**Comment by mo-jinran** [comment]
新版本已修复，详情查看官网：https://liteloaderqqnt.github.io/
