### ISSUE TITLE
[Bug]: winserver2016提示启动错误，错误代码XXx

### ISSUE THREAD

**Issue by diqiushengwu** [LiteLoaderQQNT/LiteLoaderQQNT#150]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.2

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

在服务器上部署。将所有添加到位后，

### 期望的结果是什么？

打开ntqq

### 实际的结果是什么？

出现qq启动错误代码
![QQ截图20230905202107](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/111220695/ef869aab-43b2-4fda-8bce-427b32d06a19)
![QQ截图20230905202232](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/111220695/a2cec089-9db0-4500-bdf3-29a89ae16bc7)

**Comment by xh321** [comment]
请确认单独安装QQ（不安装框架）能否使用，此类报错一般情况下与框架无关
