### ISSUE TITLE
[Bug]: 用启动器启动(管理员模式)时无法拖拽文件进QQ

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [LiteLoaderQQNT/LiteLoaderQQNT#155]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

使用管理员模式启动器才能正确加载LiteLoader，但是使用管理员启动后QQ也以管理员模式启动了，无法将资源管理器中的文件拖入QQ消息框。

### 期望的结果是什么？

不使用管理员权限运行QQ，这样才能拖拽文件。

### 实际的结果是什么？

同上所述，拖不进去。

**Comment by Fiz-Victor** [comment]
这是windows的uac机制，无解

**Comment by xh321** [comment]
Win环境下，非管理员权限程序无法拖拽文件进入管理员权限启动程序，建议改为修补QQ方式而不是用启动器启动
