### ISSUE TITLE
[Bug]: macOS 6.9.20 闪退

### ISSUE THREAD

**Issue by Dreamail** [LiteLoaderQQNT/LiteLoaderQQNT#157]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.20

### LiteLoaderQQNT 版本 （或 Commit Id）

4fad0cb92d6881438abfa0ffc2934689b6828dd3

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 重现步骤

安装器安装或手动克隆安装后启动QQ

### 期望的结果是什么？

启动QQ

### 实际的结果是什么？

闪退

### 日志记录

app % ../../MacOS/QQ             
IsVersionsDirExist: /Users/paichen/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/versions/
IsVersionsDirExist: exists: 1
IsVersionsDirExist: isDir: 1
[preload] succeeded. /Applications/QQ.app/Contents/Resources/app/major.node
[preload] succeeded. /Applications/QQ.app/Contents/Resources/app/app_launcher/launcher.node
[preload] succeeded. /Applications/QQ.app/Contents/Resources/app/wrapper.node

**Comment by Dreamail** [comment]
补充：不修改package.json依旧闪退，可能是又有文件校验了

**Comment by David-xian66** [comment]
我也闪退了

**Comment by David-xian66** [comment]
> 补充：不修改package.json依旧闪退，可能是又有文件校验了

我不修改不闪退

**Comment by KeeLee2005** [comment]
同样问题，不登陆就不闪退，一登陆很快就闪退了。
QQ Version: 6.9.20-17153 (36250) X86-64 (Native)
macOS Version: Ventura 13.5 (22G74) X86
[QQ的问题报告.txt](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/12776035/QQ.txt)

**Comment by ChrisYP** [comment]
same here

**Comment by Saber-CC** [comment]
6.9.21也闪退，不过可以进入QQ接收信息。但是点击设置、关于。或者点击聊天记录中的图片均会闪退

**Comment by mo-jinran** [comment]
新版本已修复，具体查看官网：https://liteloaderqqnt.github.io/

**Comment by Dreamail** [comment]
复活了？好诶
