### ISSUE TITLE
[Bug]: 插件失效

### ISSUE THREAD

**Issue by Xieu233** [LiteLoaderQQNT/LiteLoaderQQNT#161]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

最新的上个版本

### LiteLoaderQQNT 版本 （或 Commit Id）

最新版

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

安装插件之后所有插件都没了

### 期望的结果是什么？

修复号

### 实际的结果是什么？

没有

**Comment by xh321** [comment]
建议重装QQ，并安装最新版框架
