### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tokuda-Harukasora** [LiteLoaderQQNT/LiteLoaderQQNT#162]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.3-17153

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

打开QQNT

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

报错

### 补充说明（可选）

![屏幕截图 2023-09-23 142816](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/125880096/a10e9f6f-4dc8-42bd-8733-a32b4e583a46)

**Comment by nicklly** [comment]
已知目前最高只支持到9.9.2-16183 所以出现问题很正常

**Comment by adchoufeng** [comment]
16183出现相同情况

**Comment by ijrou** [comment]
> 16183出现相同情况

并没有，是你的问题
