### ISSUE TITLE
[Bug]: QQ9.9.3-17153 闪退

### ISSUE THREAD

**Issue by zhzhongshi** [LiteLoaderQQNT/LiteLoaderQQNT#165]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.3-17153

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

更新QQ
将liteloader启动器放入QQ安装目录
启动liteloader，可正常打开qq
点击 设置，界面闪退

### 期望的结果是什么？

点击 设置 ，正常弹出界面

### 实际的结果是什么？

闪退

### 日志记录

C:\Program Files\Tencent\QQNT>
[Launcher] 开始启动QQ...
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
d8da6f1adf0e22b2b548605c8333b326bbcb6420bc2fafffc0ee7c736a4c3782
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
8aa93ce9f329bf2b9d35cacc94fe9580e636c211899c8745bf7120d4ce79505d
0
[preload] process type:
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.3-17153
[preload] hotupdate current version: 9.9.3-17153
[preload] install app version: 9.9.3-17153

[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.3-17153\major.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.3-17153\wrapper.node
[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at C:\Program Files\Tencent\QQNT.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Found plugin: Chii DevTools
[LiteLoader] Found plugin: 背景插件
[LiteLoader] Found plugin: 自定义 CSS 样式
[LiteLoader] Found plugin: 打开链接跳过拦截页
[LiteLoader] Found plugin: 右键高亮
[LiteLoader] Found plugin: 彻底禁用更新
[LiteLoader] Found plugin: Chronocat
[LiteLoader] Found plugin: LLAPI
[LiteLoader] Found plugin: 二维码解析
[LiteLoader] Found plugin: 删除侧边栏按钮
[LiteLoader] Found plugin: Scriptio
[LiteLoader] Found plugin: Sticker++
[LiteLoader] Done! 15 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[preload] register done. launcher.node
[2023/9/30 14:28:55][INFO] C:\Program Files\Tencent\QQNT\resources\app\versions\config.json 存在

[2023/9/30 14:28:55][INFO] C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.3-17153.zip 不存在，无法执行解压操作

[2023/9/30 14:28:55][INFO] 从版本目录加载主进程代码: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.3-17153\application\background.js, {
  "curVersion": "9.9.3-17153",
  "mainProcessFileName": "application\\background.js"
}

[preload] register done. major.node
[preload] register done. wrapper.node
[2023/9/30 14:28:55][INFO]
---------- 华丽的分割线 ----------

2023-09-30 14:28:55 starting server at localhost:57445/
[Sticker++] 初始化配置文件
[Sticker++] 初始化handlers
[LLAPI] Page finished loading
[LLAPI] Page finished loading
[!Renderer:Log:2] [Background] 开始检测页面路径 {}
2023-09-30 14:28:59 target y78ojX: connected
[!Renderer:Log:2] [Background] 检测到主页页面或聊天页面，注入背景更新函数 {}
[!Renderer:Log:2] [Background] 当前背景更新间隔：600秒 {}
[LLAPI] Page finished loading
[!Renderer:Log:3] [Background] 开始检测页面路径 {}
2023-09-30 14:29:00 target aNKGPm: connected
[ ChronoNative ] LPSAOBPattern( gzFunc ): Created
[ ChronoNative ] CNHook( gzStreamHook ): Installing hook  0 , dst: 00007FFD325A2230
[ ChronoNative ] LPSAOBPattern( gzFunc ): Searching in 00007FFC8DEF0000 68341760 Pattern size: 44
[ ChronoNative ] LPSAOBPattern( gzFunc ): Result: 0000000000000000 Time: 68.081 ms
[ ChronoNative ] CNHook( gzStreamHook ): ERROR: Failed to find source ptr!

### 补充说明（可选）

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/39423408/7ba76599-c9b6-4a1e-9b33-a9245c887719

**Comment by zhzhongshi** [comment]
#147 （希望可以适配该版本（

**Comment by weizhizhuang** [comment]
相同问题，不过我的是在第一次打开时直接闪退自动重启到没有插件的版本

**Comment by Danmo04** [comment]
我也是闪退，然后自动启动无插件qq

**Comment by Strawxiguan** [comment]
等适配，别急，还没版本过低的提示，应该就还能用

**Comment by Ouroboros** [comment]
默默停更了

**Comment by yegouzic** [comment]
干脆换9.9.1版本

**Comment by ijrou** [comment]
似乎停更了。。。

**Comment by 123GitHub0123** [comment]
我直接是运行后正常打开，但是插件全没用

**Comment by CabbCat** [comment]
> 干脆换9.9.1版本

装回9.9.1会报版本过低强制更新怎么办...

**Comment by akFace** [comment]
同闪退

**Comment by bz-2021** [comment]
别停更啊呜呜呜我们请你喝咖啡 @mo-jinran @xh321

**Comment by xh321** [comment]
> 别停更啊呜呜呜我们请你喝咖啡 @mo-jinran @xh321

放心不会停更的，新版本已经有解决方案了，只是我最近比较忙

**Comment by sccccchallz** [comment]
> > 别停更啊呜呜呜我们请你喝咖啡 @mo-jinran @xh321
> 
> 放心不会停更的，新版本已经有解决方案了，只是我最近比较忙

期待，现在我电脑如果是新装的16183没办法自动登陆

**Comment by Guo-Chenxu** [comment]
期待适配

**Comment by mo-jinran** [comment]
使用最新版LiteLoaderQQNT
