### ISSUE TITLE
[Bug]: 在 NixOS 中，安装了 LiteLoaderQQNT 后开启不久即闪退

### ISSUE THREAD

**Issue by Flamarine** [LiteLoaderQQNT/LiteLoaderQQNT#166]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

3.2.1-17153

### LiteLoaderQQNT 版本 （或 Commit Id）

4fad0cb92d6881438abfa0ffc2934689b6828dd3

### 运行环境

Linux

### 运行架构

AMD64

### 重现步骤

- 通过[我自己编写的一个 Flake](https://github.com/Prismwork/llqqnt-nix) 安装附带 LiteLoaderQQNT 的 QQ
- 启动 QQ 并登录
- 在过了一小会儿后闪退（但是会重启，重启后问题依旧存在）

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

持续闪退，无法正常使用

### 日志记录

由于日志过长，故发送相应的 Pastebin 链接。
https://pastebin.com/WKYfcWnN

### 补充说明（可选）

系统：NixOS 23.11（安装了 Home Manager）
桌面环境：Hyprland

未启用 Ozone（启用之后直接无法渲染，并有使 Hyprland 崩溃的风险）。

在未安装 LiteLoaderQQNT 时完美工作。
暂不清楚任何 Wayland 桌面环境是否有此问题。

**Comment by Flamarine** [comment]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/62203463/ea44c27a-1837-4c00-b3ea-6228e22d80a8)

在登录界面即使加载插件也不会崩溃，但是登录过后似乎只要碰到有关 LiteLoader 的界面就会闪退。

**Comment by Cross0ver** [comment]
Wayland环境下同样出现了开启后不久（大约几秒钟后崩溃的情况（非flat）），此问题和另外一个issue随机发生

**Comment by xh321** [comment]
17153版本暂未适配，请等待

**Comment by Flamarine** [comment]
> 17153版本暂未适配，请等待

是这样的啊，那我用 3.1.2-12912 再试一下（因为这是 23.05 分支的最新版本，unstable 直接 3.2.1-17153 了（

**Comment by mo-jinran** [comment]
旧版本因qq会检测liteloader导致主动崩溃，现在新版本已修复，根据官网教程进行安装：https://liteloaderqqnt.github.io

**Comment by DataEraserC** [comment]
```nix
#https://github.com/Prismwork/llqqnt-nix/blob/trunk/pkgs/llqqnt.nix
{
  pkgs,
  fetchurl,
  fetchgit,
  ...
}: let
  LiteLoaderQQNT_VERSION = "1.0.2";
  LiteLoaderQQNT_URL = "https://github.com/LiteLoaderQQNT/LiteLoaderQQNT";
  LiteLoaderQQNT_SRC = fetchgit {
    url = LiteLoaderQQNT_URL;
    sha256 = "sha256-4pWXd/C3Fgh0kQjHOdN1Dce82d9WQN7r/21M0W+JE5Y=";
  };
in
  pkgs.qq.overrideAttrs (oldAttrs @ {nativeBuildInputs ? [],version, ...}: {
    nativeBuildInputs = nativeBuildInputs ++ [pkgs.p7zip];

    postInstall = ''
      sed -i '1s@^@require("${LiteLoaderQQNT_SRC}");\n@' $out/opt/QQ/resources/app/app_launcher/index.js
      mkdir -vp $out/opt/QQ/resources/app/application/
      cp -f ${LiteLoaderQQNT_SRC}/src/preload.js $out/opt/QQ/resources/app/application/
    '';
  })
  ```
修改了@Flamarine的表达式,现在能在`LITELOADERQQNT_PROFILE=$XDG_DATA_HOME/LLQQNT qq`指令下正常工作,~~但是不知道该怎么写比较优雅,比如给用户选项来指定LITELOADERQQNT_PROFILE什么的~~
