### ISSUE TITLE
[Bug]: 解压LiteLoader并修改main键为LiteLoader，打开qq会发生文件已损坏，

### ISSUE THREAD

**Issue by 123GitHub0123** [LiteLoaderQQNT/LiteLoaderQQNT#167]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

v9.9.3

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

通过解压LiteLoader并修改main键指向LiteLoader

### 期望的结果是什么？

达到期望值

### 实际的结果是什么？

qq文件损坏，重新下载qq
恢复main键，qq重新可使用

**Comment by 123GitHub0123** [comment]
使用LiteLoaderQQNT-Launcher_x64.exe会闪退，并且不会生效防撤回

**Comment by daijunhaoMinecraft** [comment]
> 使用LiteLoaderQQNT-Launcher_x64.exe会闪退，并且不会生效防撤回

用旧版本试试看？https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe

**Comment by xh321** [comment]
9.9.3暂未适配，请等待

**Comment by bianyuan456** [comment]
> 我不知道为什么，我的两个账号，其中有个不能使用旧版本接收消息，但是可以发送

我和你一样的情况，你按照这个指定的帖子操作就可以解决这个问题！
![Uploading QQ截图20231128222959.png…]()

**Comment by mo-jinran** [comment]
新版本已修复，具体查看官网：https://liteloaderqqnt.github.io/
