### ISSUE TITLE
[Bug]: launcher无法启动QQ，本体文件损坏

### ISSUE THREAD

**Issue by ABKQPO** [LiteLoaderQQNT/LiteLoaderQQNT#170]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.3.17153

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

使用launcher运行试图启动默认安装路径无修改文件的qqnt
使用三种办法修补QQ，均适用管理员运行

### 期望的结果是什么？

正常运行QQ并可以使用插件

### 实际的结果是什么？

launcher启动QQ失败
使用LLQQNTInstaller.py无法使用poetry安装
无法使用py3.11安装LLQQNTInstaller-py
patch全自动修补程序无法修复qqnt
ps1脚本无法修复
使用9.9.2.16103或9.9.0.14619登陆成功后直接崩溃，提示wrapper.node出错
系统Microsoft Windows Server 2019 Datacenter

### 日志记录

 [app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
25e181a5573b293127895ed0fe3760bdc73b6e72bc1dade40efc01e3107ca124
error code v2:-8

### 补充说明（可选）

服务器并未安装任何显卡

**Comment by ABKQPO** [comment]
使用winserver2022，qqnt版本QQ9.9.2.16183_x64可以使用补丁修复，但是登录成功后窗口空白

**Comment by daijunhaoMinecraft** [comment]
> win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面

使用旧版9.9.2.16183
https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe

**Comment by xh321** [comment]
17153版本暂未适配，请等待

**Comment by bnEars** [comment]
> > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> 
> 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe

太棒啦 完美 爱你

**Comment by bnEars** [comment]
> > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> 
> 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe

发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL

**Comment by xh321** [comment]
> > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > 
> > 
> > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> 
> 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL

我16183正常呀
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/37585529/7fef9a71-d228-4dec-8bde-89978ca38b12)

**Comment by Ichiruchan** [comment]
在ubuntu上使用了3.1.2-13107 + LiteLoaderQQNT 0.5.3 qq就无法启动，还原main值可以启动

**Comment by Ichiruchan** [comment]
> 在ubuntu上使用了3.1.2-13107 + LiteLoaderQQNT 0.5.3 qq就无法启动，还原main值可以启动

已解决，权限问题，致歉

**Comment by genghaosan** [comment]
9.9.4文件本体损坏，无法使用

**Comment by xh321** [comment]
> 9.9.4文件本体损坏，无法使用

你好，暂未适配，请等待

**Comment by bnEars** [comment]
> > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > 
> > > 
> > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > 
> > 
> > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> 
> 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)

应该是我电脑上本来就安装有TIM吧所以可能是缓存文件有冲突没办法清理干净

**Comment by JayNine25** [comment]
> > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > 
> > > 
> > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > 
> > 
> > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> 
> 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)

16183使用power shell脚本安装后，100%文件损坏打不开，重装试了好几次

**Comment by xh321** [comment]
> > > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > > 
> > > > 
> > > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > > 
> > > 
> > > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> > 
> > 
> > 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)
> 
> 16183使用power shell脚本安装后，100%文件损坏打不开，重装试了好几次

完整卸载后重新安装QQ，并使用https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer修补（只需要用这一个工具，不能同时使用ps脚本）

**Comment by kkkkato** [comment]
> > > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > > 
> > > > 
> > > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > > 
> > > 
> > > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> > 
> > 
> > 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)
> 
> 应该是我电脑上本来就安装有TIM吧所以可能是缓存文件有冲突没办法清理干净

请问一下，后面重新安装16183，能正常使用收到消息了吗？是需要也彻底删除电脑内的TIM吗？

**Comment by xh321** [comment]
> > > > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > > > 
> > > > > 
> > > > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > > > 
> > > > 
> > > > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> > > 
> > > 
> > > 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)
> > 
> > 
> > 应该是我电脑上本来就安装有TIM吧所以可能是缓存文件有冲突没办法清理干净
> 
> 请问一下，后面重新安装16183，能正常使用收到消息了吗？是需要也彻底删除电脑内的TIM吗？

我一直在用16183到目前为止一切正常。TIM的兼容性不确定

**Comment by kkkkato** [comment]
> > > > > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > > > > 
> > > > > > 
> > > > > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > > > > 
> > > > > 
> > > > > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> > > > 
> > > > 
> > > > 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)
> > > 
> > > 
> > > 应该是我电脑上本来就安装有TIM吧所以可能是缓存文件有冲突没办法清理干净
> > 
> > 
> > 请问一下，后面重新安装16183，能正常使用收到消息了吗？是需要也彻底删除电脑内的TIM吗？
> 
> 我一直在用16183到目前为止一切正常。TIM的兼容性不确定

原来安装过17412，现在把17412删掉，也把TIM删掉了。重装16183也是收不到任何消息，却可以发出消息，只能等您更新LL，支持17412了

**Comment by xh321** [comment]
> > > > > > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > > > > > 
> > > > > > > 
> > > > > > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > > > > > 
> > > > > > 
> > > > > > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> > > > > 
> > > > > 
> > > > > 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)
> > > > 
> > > > 
> > > > 应该是我电脑上本来就安装有TIM吧所以可能是缓存文件有冲突没办法清理干净
> > > 
> > > 
> > > 请问一下，后面重新安装16183，能正常使用收到消息了吗？是需要也彻底删除电脑内的TIM吗？
> > 
> > 
> > 我一直在用16183到目前为止一切正常。TIM的兼容性不确定
> 
> 原来安装过17412，现在把17412删掉，也把TIM删掉了。重装16183也是收不到任何消息，却可以发出消息，只能等您更新LL，支持17412了

你有没有清空ll的数据目录呢，这个问题非常奇怪，不应该发生的

**Comment by kkkkato** [comment]
> > > > > > > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > > > > > > 
> > > > > > > 
> > > > > > > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> > > > > > 
> > > > > > 
> > > > > > 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)
> > > > > 
> > > > > 
> > > > > 应该是我电脑上本来就安装有TIM吧所以可能是缓存文件有冲突没办法清理干净
> > > > 
> > > > 
> > > > 请问一下，后面重新安装16183，能正常使用收到消息了吗？是需要也彻底删除电脑内的TIM吗？
> > > 
> > > 
> > > 我一直在用16183到目前为止一切正常。TIM的兼容性不确定
> > 
> > 
> > 原来安装过17412，现在把17412删掉，也把TIM删掉了。重装16183也是收不到任何消息，却可以发出消息，只能等您更新LL，支持17412了
> 
> 你有没有清空ll的数据目录呢，这个问题非常奇怪，不应该发生的

17412，TIM，LL的安装目录，我都整个删了，情况还是如此

**Comment by xh321** [comment]
> > > > > > > > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> > > > > > > 
> > > > > > > 
> > > > > > > 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)
> > > > > > 
> > > > > > 
> > > > > > 应该是我电脑上本来就安装有TIM吧所以可能是缓存文件有冲突没办法清理干净
> > > > > 
> > > > > 
> > > > > 请问一下，后面重新安装16183，能正常使用收到消息了吗？是需要也彻底删除电脑内的TIM吗？
> > > > 
> > > > 
> > > > 我一直在用16183到目前为止一切正常。TIM的兼容性不确定
> > > 
> > > 
> > > 原来安装过17412，现在把17412删掉，也把TIM删掉了。重装16183也是收不到任何消息，却可以发出消息，只能等您更新LL，支持17412了
> > 
> > 
> > 你有没有清空ll的数据目录呢，这个问题非常奇怪，不应该发生的
> 
> 17412，TIM，LL的安装目录，我都整个删了，情况还是如此

不是安装目录，是数据目录，放插件的。默认在文档里，可以找一下

**Comment by 940842546** [comment]
> > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > 
> > > 
> > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > 
> > 
> > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> 
> 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)

你好 能问下Launcher哪里下载吗

**Comment by kkkkato** [comment]
> 是数据目录

非常感谢，在您的指导下，终于安装上16183+LL，并正常使用了，确实是因为LL数据目录，还是NT的数据目录没有删除，所以一直有异常，现在能正常使用了，感谢。

**Comment by kkkkato** [comment]
> > > > > > > > > > > win11.22H2.22621 QQ9.9.3.17260 无任何修改使用Launcher启动并登录后QQ正常使用 点击QQ设置立即闪退回登录界面
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 使用旧版9.9.2.16183 https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 发现问题 了 这个版本的安装包 安装之后 哪怕不安装LL 就原版QQNT 也收不到消息 可以正常发送 但是无法接收消息 更新最新版QQNT就能正常使用了 只是最新版还不支持LL
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我16183正常呀 ![image](https://user-images.githubusercontent.com/37585529/275929676-7fef9a71-d228-4dec-8bde-89978ca38b12.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 应该是我电脑上本来就安装有TIM吧所以可能是缓存文件有冲突没办法清理干净
> > > > > > 
> > > > > > 
> > > > > > 请问一下，后面重新安装16183，能正常使用收到消息了吗？是需要也彻底删除电脑内的TIM吗？
> > > > > 
> > > > > 
> > > > > 我一直在用16183到目前为止一切正常。TIM的兼容性不确定
> > > > 
> > > > 
> > > > 原来安装过17412，现在把17412删掉，也把TIM删掉了。重装16183也是收不到任何消息，却可以发出消息，只能等您更新LL，支持17412了
> > > 
> > > 
> > > 你有没有清空ll的数据目录呢，这个问题非常奇怪，不应该发生的
> > 
> > 
> > 17412，TIM，LL的安装目录，我都整个删了，情况还是如此
> 
> 不是安装目录，是数据目录，放插件的。默认在文档里，可以找一下

非常感谢，在您的指导下，终于安装上16183+LL，并正常使用了，确实是因为LL数据目录，还是NT的数据目录没有删除，所以一直有异常，现在能正常使用了，感谢。

**Comment by dixyes** [comment]
给装了新版本qqnt 然后装16183无法接受消息的人:

**这会清空聊天记录啥的**
删掉`C:\Users\<username>\Documents\Tencent Files` 重启qq就能用了

不需要清除ll数据目录

**Comment by mo-jinran** [comment]
新版本已修复，具体查看官网：https://liteloaderqqnt.github.io/

**Comment by Senyu520** [comment]
版本: 9.9.15-26909 (64位) 更改了index.js就会提示文件损坏 改回去就可以打开QQ了
