### ISSUE TITLE
[Bug?]: 插件市场一直加载不出来

### ISSUE THREAD

**Issue by gufan05** [LiteLoaderQQNT/LiteLoaderQQNT#174]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

打开插件市场等了很久都没加载出来,就觉得奇怪,然后就来看issues了,没看到我想要的,故来提本issue
可能需要的信息:1.2.4为配置信息,3为出现的问题
1.![1.png](https://pic.ziyuan.wang/2023/10/29/gufan_10779d67f7b39.png)
2.![2.png](https://pic.ziyuan.wang/2023/10/29/gufan_ed3d3064c06b5.png)
3.![3.png](https://pic.ziyuan.wang/2023/10/29/gufan_fa2b67106f4e1.png)
4.
![4.png](https://pic.ziyuan.wang/2023/10/29/gufan_6ff91aa8f03db.png)

### 期望的结果是什么？

能够正确加载出插件市场

### 实际的结果是什么？

长时间都未成功加载出插件市场

### 日志记录

D:\Program Files\Tencent\QQNT>.\LLQQ.exe

D:\Program Files\Tencent\QQNT>
[Launcher] 开始启动QQ...
[app]module file name: D:\Program Files\Tencent\QQNT\QQ.exe
50d3e6a32e99ec96b270574e70caf7ed0b4476eafe62daec9274876496fe87ed
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
05aa17dcc96655b9cd8184cc9c47cfeac4473e4c938d0417796d3f98dabb9982

[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at D:\Program Files\Tencent\QQNT.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Done! 3 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[2023/10/29 01:22:03][INFO] D:\Program Files\Tencent\QQNT\resources\app\versions\config.json 存在

[2023/10/29 01:22:03][INFO] D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-16183.zip 不存在，无法执行解压操 作

[2023/10/29 01:22:03][INFO] 从版本目录加载主进程代码: D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-16183\application\background.js, {
  "curVersion": "9.9.2-16183",
  "mainProcessFileName": "application\\background.js"
}

[2023/10/29 01:22:03][INFO]
---------- 华丽的分割线 ----------
01:22:16.656 > [hot update] hotUpdateApi checkHasMultipleQQ false
01:22:16.660 > [hot update] hotUpdateApi start clearOldVersions
01:22:16.661 > [hot update] hotUpdateApi curVersionZipPath is: D:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-16183.zip false
01:22:16.742 > [hot update] hotUpdateApi checkHasMultipleQQ false
01:22:16.744 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.3-17412
01:22:16.746 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
01:22:16.826 > [hot update] hotUpdateApi cancel
01:22:16.827 > [hot update] onStatusChanged IDLE
01:22:16.829 > [hot update] onUpdateCancel

### 补充说明（可选）

我使用的是**LiteLoaderQQNT-Launcher_x86.exe**启动,且我重命名为了**LLQQ.exe**,故上面**日志记录**中的启动命令变成了".\LLQQ.exe",因为".\QQ.exe"并不会加载出LiteLoaderQQNT

**Comment by gufan05** [comment]
请各位大佬帮忙解答,谢谢了

**Comment by misaka10843** [comment]
尝试访问ghproxy.com，似乎是因为cdn无法访问导致无法获取

**Comment by qiuzilu** [comment]
+1，
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/64822124/d7feb3b4-f7d5-4b6d-9549-80733aa0fd4f)

**Comment by Nana7miChiaKi** [comment]
配置文件里删除https://ghproxy.com/

**Comment by Timing-up** [comment]
需要自己在配置页面，配置自己的代理。已成功访问。

**Comment by xh321** [comment]
请更新到最新版框架，目前支持手动配置代理。
