### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ZXL-Q** [LiteLoaderQQNT/LiteLoaderQQNT#175]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2.16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.3

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

安装LiteLoaderQQNT后直接运行LiteLoaderQQNT-Launcher_x64.exe

### 期望的结果是什么？

正常运行并正常使用

### 实际的结果是什么？

![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/121118429/d2d1ea7b-8b1d-496b-9d7f-127d5d604e96)
运行LiteLoaderQQNT-Launcher_x64.exe后截图

### 日志记录

C:\Program Files\Tencent\QQNT>[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
50d3e6a32e99ec96b270574e70caf7ed0b4476eafe62daec9274876496fe87ed
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
05aa17dcc96655b9cd8184cc9c47cfeac4473e4c938d0417796d3f98dabb9982

[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at C:\Program Files\Tencent\QQNT.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Found plugin: 防撤回
[LiteLoader] Found plugin: Chii DevTools
[LiteLoader] Found plugin: DeepL
[LiteLoader] Found plugin: Fluentify
[LiteLoader] Found plugin: 背景插件
[LiteLoader] Found plugin: 打开链接跳过拦截页
[LiteLoader] Found plugin: 右键高亮
[LiteLoader] Found plugin: 彻底禁用更新
[LiteLoader] Found plugin: Markdown-it
[LiteLoader] Found plugin: Chronocat
[LiteLoader] Found plugin: 繁化姬
[LiteLoader] Found plugin: LLAPI
[LiteLoader] Found plugin: 加密消息
[LiteLoader] Found plugin: QQ增强
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Found plugin: 二维码解析
[LiteLoader] Found plugin: 仿Telegram风格主题
[LiteLoader] Found plugin: QQ消息修改
[LiteLoader] Found plugin: MSpring Theme
[LiteLoader] Found plugin: 窗口置顶
[LiteLoader] Done! 22 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[2023/11/4 00:48:59][INFO] C:\Program Files\Tencent\QQNT\resources\app\versions\config.json 存在

[2023/11/4 00:48:59][INFO] C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-16183.zip 不存在，无法执行解压操作

[2023/11/4 00:48:59][INFO] 从版本目录加载主进程代码: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.2-16183\application\background.js, {
  "curVersion": "9.9.2-16183",
  "mainProcessFileName": "application\\background.js"
}

[2023/11/4 00:48:59][INFO]
---------- 华丽的分割线 ----------

2023-11-04 00:48:59 starting server at localhost:60581/
(node:3184) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `QQ --trace-warnings ...` to show where the warning was created)
[3184:1104/004945.260:ERROR:network_service_instance_impl.cc(558)] Network service crashed, restarting service.
(node:3184) UnhandledPromiseRejectionWarning: Error: Database is not open
    at maybeOpened (C:\Users\Administrator\Documents\LiteLoaderQQNT\plugins\anti_recall\node_modules\abstract-level\abstract-level.js:133:18)
    at C:\Users\Administrator\Documents\LiteLoaderQQNT\plugins\anti_recall\node_modules\abstract-level\abstract-level.js:160:13
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
(node:3184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise
inate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by xh321** [comment]
如果遇到这种问题，请删除LiteLoaderQQNT的数据目录，再重启QQ。有关数据目录在哪，README里已经有说明
