### ISSUE TITLE
[Bug]: 插件市场完全空白

### ISSUE THREAD

**Issue by daijunhaoMinecraft** [LiteLoaderQQNT/LiteLoaderQQNT#177]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.6

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

我使用的代理是https://www.gitclone.com ，提示暂未发现LIteloaderQQNT有新版本，但是插件市场一片白（不给刷新的机会
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/121751847/91e60319-306d-46fd-ad06-7693238911f9)
）

### 期望的结果是什么？

能够显示出插件市场

### 实际的结果是什么？

反复重启，依然是一片白

### 日志记录

G:\Deskop>D:\QQNT\LiteLoaderQQNT-Launcher_x64.exe

[32m[Launcher][0m 开始启动QQ...
[app]module file name: D:\QQNT\QQ.exe
50d3e6a32e99ec96b270574e70caf7ed0b4476eafe62daec9274876496fe87ed
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
05aa17dcc96655b9cd8184cc9c47cfeac4473e4c938d0417796d3f98dabb9982

[32m[LiteLoader][0m Initializing...
[32m[LiteLoader][0m Found QQNT installation at D:\QQNT.
[32m[LiteLoader][0m Start loading plugins.
[32m[LiteLoader][0m Found plugin: LiteLoader 配置界面
[32m[LiteLoader][0m Found plugin: LiteLoader 样式框架
[32m[LiteLoader][0m Found plugin: LiteLoader 插件市场
[32m[LiteLoader][0m Found plugin: 防撤回
[32m[LiteLoader][0m Found plugin: 自动刷屏
[32m[LiteLoader][0m Found plugin: Chii DevTools
[32m[LiteLoader][0m Found plugin: DeepL
[32m[LiteLoader][0m Found plugin: Fluentify
[32m[LiteLoader][0m Found plugin: 背景插件
[32m[LiteLoader][0m Found plugin: 自定义 CSS 样式
[32m[LiteLoader][0m Found plugin: 打开链接跳过拦截页
[32m[LiteLoader][0m Found plugin: QQNT Eruda
[32m[LiteLoader][0m Found plugin: 右键高亮
[32m[LiteLoader][0m Found plugin: 彻底禁用更新
[32m[LiteLoader][0m Found plugin: Markdown-it
[32m[LiteLoader][0m Found plugin: 消息靠左连续展示
[32m[LiteLoader][0m Found plugin: Chronocat
[32m[LiteLoader][0m Found plugin: 演示模式
[32m[LiteLoader][0m Found plugin: 歪比巴卜
[32m[LiteLoader][0m Found plugin: 繁化姬
[32m[LiteLoader][0m Found plugin: LLAPI
[32m[LiteLoader][0m Found plugin: 加密消息
[32m[LiteLoader][0m Found plugin: 自定义表情
[32m[LiteLoader][0m Found plugin: 二维码解析
[32m[LiteLoader][0m Found plugin: QQNT vConsole
[32m[LiteLoader][0m Found plugin: 本地查看图片和视频
[32m[LiteLoader][0m Found plugin: QQ消息修改
[32m[LiteLoader][0m Found plugin: MSpring Theme
[32m[LiteLoader][0m Found plugin: 删除侧边栏按钮
[32m[LiteLoader][0m Found plugin: 复读只因
[32m[LiteLoader][0m Found plugin: Scriptio
[32m[LiteLoader][0m Found plugin: Sticker++
[32m[LiteLoader][0m Found plugin: Transitio
[32m[LiteLoader][0m Found plugin: 窗口置顶
[32m[LiteLoader][0m Done! 34 plugins loaded!
[32m[LiteLoader][0m Preprocessing plugins' preloads...
[32m[LiteLoader][0m Preprocessing plugins' preloads done!
[32m[LiteLoader][0m Starting QQNT...
[2023/11/5 20:02:02][INFO] D:\QQNT\resources\app\versions\config.json 存在

[2023/11/5 20:02:02][INFO] D:\QQNT\resources\app\versions\9.9.2-16183.zip 不存在，无法执行解压操作

[2023/11/5 20:02:02][INFO] 从版本目录加载主进程代码: D:\QQNT\resources\app\versions\9.9.2-16183\application\background.js, {
  "curVersion": "9.9.2-16183",
  "mainProcessFileName": "application\\background.js"
}

[2023/11/5 20:02:03][INFO]
---------- 华丽的分割线 ----------

2023-11-05 20:02:03 starting server at localhost:9272/
[34m[Sticker++][39m 初始化配置文件
[34m[Sticker++][39m 初始化handlers
[32m[LLAPI][0m Page finished loading
[!Renderer:Log:1] [32m[自定义表情-渲染][0m []
[!Renderer:Log:1] [MSpring Theme] [检测] 已启用背景插件
[!Renderer:Log:1] [Background] 开始检测页面路径 {}
[!Renderer:Log:1] [MSpring Theme] [设置] 开启赫蹏
[!Renderer:Log:1] [MSpring Theme] [设置] 开启消息合并
[!Renderer:Log:1] [Background] 非主页或聊天页面，停止注入 {}
[32m[LLAPI][0m Page finished loading
[!Renderer:Log:2] [32m[自定义表情-渲染][0m []
2023-11-05 20:02:04 [33mtarget[39m uXPEmX: [32mconnected[39m
[!Renderer:Log:2] [MSpring Theme] [检测] 已启用背景插件
[!Renderer:Log:2] [Background] 开始检测页面路径 {}
[!Renderer:Log:2] [MSpring Theme] [设置] 开启赫蹏
[!Renderer:Log:2] [MSpring Theme] [设置] 开启消息合并
2023-11-05 20:02:04 [33mtarget[39m ksCrQC: [32mconnected[39m
2023-11-05 20:02:06 [33mtarget[39m uXPEmX: [31mdisconnected[39m
[32m[LLAPI][0m Page finished loading
[!Renderer:Log:3] [32m[自定义表情-渲染][0m []
[32mAnti-Recall:[0m NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message
[32mImage-Local-View:[0m NTQQ Image-Local-View for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message
[!Renderer:Log:3] [MSpring Theme] [检测] 已启用背景插件
[!Renderer:Log:3] [Background] 开始检测页面路径 {}
[!Renderer:Log:3] [MSpring Theme] [设置] 开启赫蹏
[!Renderer:Log:3] [MSpring Theme] [设置] 开启消息合并
2023-11-05 20:02:07 [33mtarget[39m GM79vc: [32mconnected[39m
[!Renderer:Log:2] [Background] 检测到主页页面或聊天页面，注入背景更新函数 {}
[!Renderer:Log:2] [DeepL] 已检测到 #ml-root .ml-list
[!Renderer:Log:2] [Media-Local-View] 检测到聊天区域，已在当前页面加载视频下载辅助
[!Renderer:Log:2] [Anti-Recall] 检测到聊天区域，已在当前页面加载反撤回
[!Renderer:Log:2] [MSpring Theme] 已检测到 #ml-root .ml-list
[!Renderer:Log:2] [MSpring Theme] 已检测到 #ml-root .ml-list
2023-11-05 20:02:07 [33mtarget[39m ksCrQC: [32mconnected[39m
[!Renderer:Log:2] [Background] 当前背景更新间隔：600秒 {}
[!Renderer:Log:3] [Background] 非主页或聊天页面，停止注入 {}
[!Renderer:Log:3] [34m[Sticker++][39m 设置Config页面
2023-11-05 20:02:09 [33mtarget[39m GM79vc: [32mconnected[39m
[32m[LLAPI][0m Page finished loading
[!Renderer:Log:3] [34m[Sticker++][39m Added config view
[!Renderer:Log:3] [34m[Sticker++][39m Listening to config view
[!Renderer:Log:3] [Msg Encode Renderer] jiamiicon
[!Renderer:Log:4] [32m[自定义表情-渲染][0m []
[!Renderer:Log:4] [MSpring Theme] [检测] 已启用背景插件
[!Renderer:Log:4] [Background] 开始检测页面路径 {}
[!Renderer:Log:4] [MSpring Theme] [设置] 开启赫蹏
[!Renderer:Log:4] [MSpring Theme] [设置] 开启消息合并
2023-11-05 20:02:10 [33mtarget[39m UwupY4: [32mconnected[39m
20:02:10.874 > [hot update] hotUpdateApi checkHasMultipleQQ false
20:02:10.876 > [hot update] hotUpdateApi start clearOldVersions
20:02:10.877 > [hot update] hotUpdateApi curVersionZipPath is: D:\QQNT\resources\app\versions\9.9.2-16183.zip false
20:02:15.900 > [hot update] hotUpdateApi checkHasMultipleQQ false
20:02:15.901 > [hot update] hotUpdateApi checkIsOnErrorVersion null
20:02:15.902 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/121751847/f9747e2d-437d-411e-a1ff-5ebaf2d7bce9)

### 补充说明（可选）

目前使用Steam++，插件市场依然空白
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/121751847/6bae966b-921b-47a5-b65b-354a9309ab66)

**Comment by xh321** [comment]
请在配置界面手动设置socks或http代理（或者自动应用系统代理），最好不要用第三方软件设置加速，并更新框架到最新版（目前0.5.7）

**Comment by xh321** [comment]
另外说明一下，ghproxy.com这个网站目前不稳定，设置他为加速反而会阻碍访问
