### ISSUE TITLE
[Bug]: 代理问题

### ISSUE THREAD

**Issue by ChAoKiLL** [LiteLoaderQQNT/LiteLoaderQQNT#180]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.9

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

设置http代理不能保存，测试不通过,无法保存。0.5.6 可以使用
`http://账号:密码@10.0.0.6:7893`

### 期望的结果是什么？

正常使用

### 实际的结果是什么？

不能使用

**Comment by miniEast** [comment]
我都全局代理了，获取最新更新版都能获取到返回，但是插件市场还是没数据

**Comment by meowlitlot** [comment]
我的代理配置界面的测试也不能通过，不过我手动改了`config.json`
类似这样
```
{
    "plugins_marketplace": {
        "mirrorlist": [
            "https://raw.githubusercontent.com/LiteLoaderQQNT/LiteLoaderQQNT-Plugin-List/v3/plugins.json",
            "https://raw.githubusercontent.com/LiteLoaderQQNT/LiteLoaderQQNT-Plugin-List/v3/builtins.json"
        ],
        "proxy": null,
        "plugin_type": [
            "all",
            "current"
        ],
        "sort_order": [
            "random",
            "forward"
        ],
        "list_style": [
            "single",
            "loose"
        ]
    },
    "proxy": "http://127.0.0.1:7890"        
}
```

下面的`proxy`好像才是会被读取的代理配置，总之改完我连上了

**Comment by Joackk** [comment]
一样的问题，在设置里设置了系统代理，但是似乎并没有生效，按照上面老哥的配置自己手动加上后正常使用了

**Comment by Joackk** [comment]
> 我的代理配置界面的测试也不能通过，不过我手动改了`config.json` 类似这样
> 
> ```
> {
>     "plugins_marketplace": {
>         "mirrorlist": [
>             "https://raw.githubusercontent.com/LiteLoaderQQNT/LiteLoaderQQNT-Plugin-List/v3/plugins.json",
>             "https://raw.githubusercontent.com/LiteLoaderQQNT/LiteLoaderQQNT-Plugin-List/v3/builtins.json"
>         ],
>         "proxy": null,
>         "plugin_type": [
>             "all",
>             "current"
>         ],
>         "sort_order": [
>             "random",
>             "forward"
>         ],
>         "list_style": [
>             "single",
>             "loose"
>         ]
>     },
>     "proxy": "http://127.0.0.1:7890"        
> }
> ```
> 
> 下面的`proxy`好像才是会被读取的代理配置，总之改完我连上了

感谢，看了下配置文件，一样是用他设置的并没有生效，手动加上去后正常了

**Comment by misaka10843** [comment]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/69132853/b7f45b7b-2c1c-4441-a1a8-004908e8b25d)
在设置界面设置http代理测试似乎只会请求一言接口，并不会检测GitHub连接性（至少日志中并没有显示）

**Comment by xh321** [comment]
你好，已知问题，已经修复
