### ISSUE TITLE
[Bug]: 检查更新时报错：无法验证第一个证书

### ISSUE THREAD

**Issue by xwy231321** [LiteLoaderQQNT/LiteLoaderQQNT#181]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-15962

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.9

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

打开配置页面后检查更新时一直是报错状态，无法验证第一个证书
点击重新发现按钮，依然是该报错内容，日志为：[!Renderer:Log:3] {}

### 期望的结果是什么？

检查出正确的版本

### 实际的结果是什么？

![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/106575654/0153b6d5-e6ec-4aa8-9131-0cd2b87f1b69)

### 日志记录

[preload] process type:
[app]module file name: C:\app\ntqq\QQ.exe
[preload] hotupdate base version: 9.9.2-15962
[preload] hotupdate current version: 9.9.2-15962
[preload] install app version: 9.9.2-15962

[preload] succeeded. C:\app\ntqq\resources\app\versions\9.9.2-15962\wrapper.node
[preload] succeeded. C:\app\ntqq\resources\app\app_launcher\launcher.node
[preload] succeeded. C:\app\ntqq\resources\app\versions\9.9.2-15962\major.node
[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at C:\app\ntqq.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Found plugin: 防撤回
[LiteLoader] Found plugin: DeepL
[LiteLoader] Found plugin: Fluentify
[LiteLoader] Found plugin: 背景插件
[LiteLoader] Found plugin: 打开链接跳过拦截页
[LiteLoader] Found plugin: 右键高亮
[LiteLoader] Found plugin: 彻底禁用更新
[LiteLoader] Found plugin: 演示模式
[LiteLoader] Found plugin: LLAPI
[LiteLoader] Found plugin: QQ增强
[LiteLoader] Found plugin: MSpring Theme
[LiteLoader] Done! 14 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[preload] register done. launcher.node
[2023/11/7 22:22:27][INFO] C:\app\ntqq\resources\app\versions\config.json 存在

[2023/11/7 22:22:27][INFO] C:\app\ntqq\resources\app\versions\9.9.2-15962.zip 不存在，无法执行解压操作

[2023/11/7 22:22:27][INFO] 从版本目录加载主进程代码: C:\app\ntqq\resources\app\versions\9.9.2-15962\application\background.js, {
  "curVersion": "9.9.2-15962",
  "mainProcessFileName": "application\\background.js"
}

[preload] register done. major.node
[preload] register done. wrapper.node
[2023/11/7 22:22:27][INFO]
---------- 华丽的分割线 ----------

[LLAPI] Page finished loading
[!Renderer:Log:1] [MSpring Theme] [检测] 已启用背景插件
[!Renderer:Log:1] [Background] 开始检测页面路径 {}
[!Renderer:Log:1] [Background] 非主页或聊天页面，停止注入 {}
[LLAPI] Page finished loading
[!Renderer:Log:2] [MSpring Theme] [检测] 已启用背景插件
[!Renderer:Log:2] [Background] 开始检测页面路径 {}
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message
[!Renderer:Log:2] [Background] 检测到主页页面或聊天页面，注入背景更新函数 {}
[LLAPI] Page finished loading
[!Renderer:Log:2] [Background] 当前背景更新间隔：600秒 {}
[!Renderer:Log:3] [MSpring Theme] [检测] 已启用背景插件
[!Renderer:Log:3] [Background] 开始检测页面路径 {}
[!Renderer:Log:2] [DeepL] 已检测到 #ml-root .ml-list
[!Renderer:Log:2] [Anti-Recall] 检测到聊天区域，已在当前页面加载反撤回

** (process:14704): WARNING **: 22:22:32.271: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:22:32.271: pngsave: no property named `no-subsample'

22:22:34.142 > [hot update] hotUpdateApi checkHasMultipleQQ false
22:22:34.144 > [hot update] hotUpdateApi start clearOldVersions
22:22:34.144 > [hot update] hotUpdateApi curVersionZipPath is: C:\app\ntqq\resources\app\versions\9.9.2-15962.zip false
22:22:34.191 > [hot update] hotUpdateApi checkHasMultipleQQ false
22:22:34.193 > [hot update] hotUpdateApi checkIsOnErrorVersion null
22:22:34.194 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false
[!Renderer:Log:3] [Background] 非主页或聊天页面，停止注入 {}
[LLAPI] Page finished loading

** (process:14704): WARNING **: 22:22:35.721: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:22:35.721: pngsave: no property named `no-subsample'

[!Renderer:Log:3] {}
[!Renderer:Log:4] [MSpring Theme] [检测] 已启用背景插件
[!Renderer:Log:4] [Background] 开始检测页面路径 {}

** (process:14704): WARNING **: 22:22:36.042: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:22:36.042: pngsave: no property named `no-subsample'

[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}
[!Renderer:Log:3] {}

### 补充说明（可选）

qq无操作情况下，日志为** (process:14704): WARNING **: 22:22:52.478: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:22:52.478: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:23:31.725: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:23:31.725: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:24:03.136: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:24:03.136: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:24:34.036: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:24:34.036: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:25:40.456: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:25:40.456: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:25:43.819: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:25:43.819: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:25:43.915: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:25:43.915: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:25:43.935: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:25:43.935: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:25:43.974: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:25:43.974: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:25:44.008: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:25:44.008: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:25:44.024: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:25:44.024: pngsave: no property named `no-subsample'

** (process:14704): WARNING **: 22:25:44.049: pngsave: no property named `optimize-coding'

** (process:14704): WARNING **: 22:25:44.049: pngsave: no property named `no-subsample'

一直在循环

**Comment by xwy231321** [comment]
qq无操作情况下，日志为** (process:14704): WARNING **: 22:22:52.478: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:22:52.478: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:23:31.725: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:23:31.725: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:24:03.136: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:24:03.136: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:24:34.036: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:24:34.036: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:25:40.456: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:25:40.456: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:25:43.819: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:25:43.819: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:25:43.915: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:25:43.915: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:25:43.935: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:25:43.935: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:25:43.974: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:25:43.974: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:25:44.008: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:25:44.008: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:25:44.024: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:25:44.024: pngsave: no property named `no-subsample'


** (process:14704): WARNING **: 22:25:44.049: pngsave: no property named `optimize-coding'


** (process:14704): WARNING **: 22:25:44.049: pngsave: no property named `no-subsample'


一直在循环

**Comment by FinaFina233** [comment]
我也是，服了

**Comment by xh321** [comment]
你好，请配置一下代理，你所在地域污染了Github dns导致无法访问。在这个界面下面就有代理配置（请先更新框架到最新版）。之后的版本我们也会添加自定义镜像源的功能。
