### ISSUE TITLE
[Bug]: 使用一键脚本安装导致的安装不成功

### ISSUE THREAD

**Issue by xyls184** [LiteLoaderQQNT/LiteLoaderQQNT#184]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183 等需要脚本安装的版本

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.9 需要脚本安装的版本

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

**直接看下面补充说明，我找到了原因**
有类似问题的也可以看下面，我写了我安装好的流程。

事先安装了https://t.me/QQUpdates/117 处的QQ，版本windowsQQ_9.9.2.16183_x64
1. 在这一步骤下载了安装脚本[使用安装脚本安装（一键）](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT#%E4%BD%BF%E7%94%A8%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC%E5%AE%89%E8%A3%85%E4%B8%80%E9%94%AE)于桌面上，即“C:\Users\xyls184\Desktop”。
2. 使用管理员权限打开powershell运行后，选择第二项“使用全自动patch程序（开源）”，如图所示：
![1](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/20354136/67cdea9c-549e-4e1f-ae32-a10f59fec5cb)
3. 弹出Liteloader Patcher & Fixer提权窗口，提升为管理员身份运行后，识别到qq版本：9.9.2.16183，点击“一键修补QQ”，点击运行，弹出窗口“文件已损坏，请重新安装QQ”。
4. 点击“一键修复QQ提示损坏”，
![photo_2023-11-08_23-42-34](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/20354136/b3b40457-2f9d-4804-ae0d-1b97537bab79)
仍提示“文件已损坏，请重新安装QQ”

### 期望的结果是什么？

qq被patch，可以正常打开。

### 实际的结果是什么？

提示“文件已损坏，请重新安装QQ”

### 补充说明（可选）

首先声明我打开脚本看了半天，但是编程0基础一点也没看懂
发现可能是脚本的路径写错了，因为当我使用脚本安装完后（方法二与方法三都这样），打开“C:\Program Files\Tencent\QQNT\resources\app”文件夹后，发现脚本直接把文件夹内的内容覆盖在了目录里，而是没有拷贝文件夹，如下图所示：
![photo_2023-11-09_00-05-52](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/20354136/4280b0df-5c13-406c-b2a7-35a01fa374b8)
此时无论怎么修补QQ都打不开，且 package.json 明明声明不要动却被直接覆盖成LiteLoader项目里的 package.json，所以我想可能是因为脚本覆盖错了。
于是我卸载了QQ并删除了“C:\Program Files\Tencent\QQNT”里的所有文件，并重新安装，这次的做法是下载最新release里最新的压缩包，解压至文件夹内并改名成“LiteLoader”，然后移动到“C:\Program [Files\Tencent\QQNT\resources\app”中（不要动package.json）此时再用[LiteLoaderQQNT-PatcherNFixer](https://github.com/xh321/LiteLoaderQQNT-PatcherNFixer)中的修改器进行修补，最后成功打开。
按照我的方法修补的文件结构长这样：
![photo_2023-11-09_00-11-55](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/20354136/e0401207-2f12-4490-b6a6-2f45dbc6d559)
QQ已可以成功打开并加载插件：
![1122](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/20354136/dbd41564-f41c-41d9-ab07-10249907f4b9)

还有一个小问题是方法一并没有自动下载启动器，我猜测是因为最新的issue（0.5.9）里不包含启动器

**Comment by MaxCrazy1101** [comment]
感觉像是解压文件夹错了

**Comment by cancundeyingzi** [comment]
给个置顶吧,确实有效

**Comment by mo-jinran** [comment]
新版本已无需这么麻烦（
具体查看官网：https://liteloaderqqnt.github.io/
