### ISSUE TITLE
[Bug]: 如果安装过一遍新版的QQNT再去使用99216183版本时接受不到消息的问题

### ISSUE THREAD

**Issue by Kuroto114514** [LiteLoaderQQNT/LiteLoaderQQNT#186]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2 16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.9

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

安装过QQNT9.9.3新版且打开登录过 会在文档\Tencent Files\你的qq 里面生成nt_qq文件夹 然后退回9.9.2后是不会被覆盖的 将文件夹删除 再开9.9.2就可以正常接收消息了

### 期望的结果是什么？

正常使用

### 实际的结果是什么？

9.9.2的消息无法接收

**Comment by jiangyin14** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> 
> - [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
> - [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> - [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
> - [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
> 
> ### QQNT 版本
> 
> 9.9.2 16183
> 
> ### LiteLoaderQQNT 版本 （或 Commit Id）
> 
> 0.5.9
> 
> ### 运行环境
> 
> Windows (64)
> 
> ### 运行架构
> 
> None
> 
> ### 重现步骤
> 
> 安装过QQNT9.9.3新版且打开登录过 会在文档\Tencent Files\你的qq 里面生成nt_qq文件夹 然后退回9.9.2后是不会被覆盖的 将文件夹删除 再开9.9.2就可以正常接收消息了
> 
> ### 期望的结果是什么？
> 
> 正常使用
> 
> ### 实际的结果是什么？
> 
> 9.9.2的消息无法接收
> 
> ### 日志记录
> 
> _No response_
> 
> ### 补充说明（可选）
> 
> _No response_

能给个99216183包吗

**Comment by RinLin-NYA** [comment]
解决该问题的方式：在安装LiteLoaderQQNT项目前先纯净登录一遍9.9.2-16183，再安装LiteLoaderQQNT

**Comment by zxytql** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> * [x]  我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
> * [x]  我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> * [x]  我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
> * [x]  我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
> 
> ### QQNT 版本
> 9.9.2 16183
> 
> ### LiteLoaderQQNT 版本 （或 Commit Id）
> 0.5.9
> 
> ### 运行环境
> Windows (64)
> 
> ### 运行架构
> None
> 
> ### 重现步骤
> 安装过QQNT9.9.3新版且打开登录过 会在文档\Tencent Files\你的qq 里面生成nt_qq文件夹 然后退回9.9.2后是不会被覆盖的 将文件夹删除 再开9.9.2就可以正常接收消息了
> 
> ### 期望的结果是什么？
> 正常使用
> 
> ### 实际的结果是什么？
> 9.9.2的消息无法接收
> 
> ### 日志记录
> _No response_
> 
> ### 补充说明（可选）
> _No response_

我也遇到了一样的问题，按照你的重新步骤执行过后可以正常接收信息了，感谢

**Comment by xh321** [comment]
可能是QQ改了什么数据结构，导致16183不兼容，按照楼上的办法即可
