### ISSUE TITLE
[Feat]: 建议添加自定义Github代理加速网站

### ISSUE THREAD

**Issue by JERRY-SYSTEM** [LiteLoaderQQNT/LiteLoaderQQNT#188]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

因Ghproxy访问问题，导致Liteloader的插件市场出现无法加载的问题。很高兴看到作者积极修复并添加了自定义代理功能，但我想提出建议添加自定义Github代理加速网站功能，原因如下：

1. 系统代理往往需要VPN客户端和节点，部分用户可能没有这些。
2. Ghproxy是个开源项目，网络上不止一个同源码网站，且每个人都可以在Cloudflare上部署，添加此功能可以免VPN获取插件信息，更加方便。

以上为我个人看法，如有不妥请指出。

**Comment by mo-jinran** [comment]
有自定义插件源功能，不过没写UI，需要手动修改数据目录config.json，可在原有链接前添加代理或新增

**Comment by mo-jinran** [comment]
很抱歉，新版 LiteLoaderQQNT 已移除插件市场，但有社区代替插件：https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store
