### ISSUE TITLE
[Bug]: 非正常关闭qq后再次启动提示A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by rainyorange** [LiteLoaderQQNT/LiteLoaderQQNT#189]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2.16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.9

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

电脑蓝屏时qq正在运行，重启后出现

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/36807368/f56443b3-7b0b-4419-be16-7d13100ef9f8)

### 日志记录

![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/36807368/9a27b780-d68d-4b4c-b888-2aba83688713)

**Comment by rainyorange** [comment]
将数据文档中的乱码config.json删除后再次启动有额外启动日志，但是继续报错
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/36807368/4569c758-8863-4d22-9880-a2c5d4b3071b)

**Comment by rainyorange** [comment]
将数据文档中所有文件移除后，正常启动

**Comment by xiyuesaves** [comment]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/25543545/b6b866cf-0d8e-4286-8432-4a16f6fd5726)
错误来自防撤回插件无法打开数据库文件导致，和LiteLoaderQQNT本体没有关系
