### ISSUE TITLE
[Feat]: 介绍插件的本地加载（不是新功能而是完善readme.md！！！）

### ISSUE THREAD

**Issue by JessBobby** [LiteLoaderQQNT/LiteLoaderQQNT#191]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

1.问题
        遇到的问题是在完成安装后，因代理问题始终无法加载出插件市场。
2.尝试解决
        采用了issue中的更改代理的方式完成显示，但是无法完成插件的下载。
3.解决办法
        点击插件【详情】前往作者的插件仓库下载文件并放到plugins文件夹下，随后重启便安装完成。
**4.建议**
        **在readme.md中添加对小白更友好的说明，通过将插件下载到本地再加载来解决代理导致插件市场无法访问的问题。**

大致内容可如下：
解决因代理问题导致插件市场无法加载【**手动下载插件，不推荐**】
（缺点：手动更新+仓库过多）
1.**前往各插件**作者的**仓库**，**下载**最新release，或者下载对应分支下的所有文件。
2.插件对应的**仓库地址**可在此查看]**(https://github.com/LiteLoaderQQNT/LiteLoaderQQNT-Plugin-List/blob/v3/plugins.json)**
        “repo”代表作者的插件仓库（都在github，直接搜索可找到），”branch“代表对应分支
3.下载对应文件压缩包后，将其**解压在LiteLoaderQQNT数据目录**（LiteLoader配置页面有对应路径）下的**plugins文件夹**中，**每一个插件都要一个独立的文件夹**。
4.重启QQ。

**Comment by xh321** [comment]
已修正
