### ISSUE TITLE
[Feat]: 更换域名解决ghproxy.com时常断线的问题

### ISSUE THREAD

**Issue by zh9c418** [LiteLoaderQQNT/LiteLoaderQQNT#192]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

根据ghproxy官网公告：
>由于主域名 ghproxy.com 喜提 GFW，请更换为 [mirror.ghproxy.com](https://mirror.ghproxy.com/)二级域名

所以将ghproxy.com改成mirror.ghproxy.com 应该能解决目前遇到的部分问题

**Comment by xh321** [comment]
目前支持配置自定义代理，自定义镜像源请等待后续更新

**Comment by xh321** [comment]
目前已有重复 issue #188 ，暂且先关闭这个 issue 了，你可以关注另一个 issue 的最新进展
