### ISSUE TITLE
[Bug]: 使用系统代理（梯子），插件商店能显示。 使用第三方代理（https://mirror.ghproxy.com/），测试通过，但插件商店加载不出来

### ISSUE THREAD

**Issue by SunshineboyZj** [LiteLoaderQQNT/LiteLoaderQQNT#194]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.10

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

使用系统代理（梯子），测试通过，应用后，重复几次关闭设置并打开，插件商店能加载出来。 
用第三方代理GitHub Proxy https://mirror.ghproxy.com/ ，测试通过，应用后，重复几次关闭设置并打开，插件商店加载不出来

![1](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/81549837/05c79e87-3088-4e4d-812f-478bad0f3548)
![2](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/81549837/9e84c2f4-7e8b-48ca-9192-c334a9c6fdaa)
三倍速视频

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/81549837/74f025d2-7abf-4331-9919-c133abc515c7

### 期望的结果是什么？

能够正常使用第三方GitHub Proxy https://mirror.ghproxy.com/ 代理

### 实际的结果是什么？

测试通过，但插件商店加载不出来

### 日志记录

PS D:\软件\QQ> .\LiteLoaderQQNT-Launcher_x64.exe
PS D:\软件\QQ>
[Launcher] 开始启动QQ...
[app]module file name: D:\\QQ\QQ.exe
50d3e6a32e99ec96b270574e70caf7ed0b4476eafe62daec9274876496fe87ed
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
643a4a860c15c91827bf0f2a77510172a980fc5d3a18ef73ffec757ec3086463
05aa17dcc96655b9cd8184cc9c47cfeac4473e4c938d0417796d3f98dabb9982

[LiteLoader] Initializing...
[LiteLoader] Found QQNT installation at D:\软件\QQ.
[LiteLoader] Start loading plugins.
[LiteLoader] Found plugin: LiteLoader 配置界面
[LiteLoader] Found plugin: LiteLoader 样式框架
[LiteLoader] Found plugin: LiteLoader 插件市场
[LiteLoader] Found plugin: 防撤回
[LiteLoader] Found plugin: 彻底禁用更新
[LiteLoader] Done! 5 plugins loaded!
[LiteLoader] Preprocessing plugins' preloads...
[LiteLoader] Preprocessing plugins' preloads done!
[LiteLoader] Starting QQNT...
[2023/12/9 19:12:46][INFO] D:\软件\QQ\resources\app\versions\config.json 存在

[2023/12/9 19:12:46][INFO] 已经存在 D:\软件\QQ\resources\app\versions\9.9.2-16183 目录，无需执行解压操作

[2023/12/9 19:12:46][INFO] 从版本目录加载主进程代码: D:\软件\QQ\resources\app\versions\9.9.2-16183\application\background.js, {
  "curVersion": "9.9.2-16183",
  "mainProcessFileName": "application\\background.js"
}

[2023/12/9 19:12:46][INFO]
---------- 华丽的分割线 ----------

Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?processGroupNS=createBlankWindow1#/main/message
19:12:53.795 > [hot update] hotUpdateApi checkHasMultipleQQ false
19:12:53.796 > [hot update] hotUpdateApi start clearOldVersions
19:12:53.797 > [hot update] hotUpdateApi curVersionZipPath is: D:\软件\QQ\resources\app\versions\9.9.2-16183.zip true
19:12:53.797 > [hot update] hotUpdateApi start movePatchUpdateResourceToBackupDir 9.9.2-16183
19:13:00.339 > [hot update] hotUpdateApi checkHasMultipleQQ false
19:13:00.346 > [hot update] hotUpdateApi checkIsOnErrorVersion null
19:13:00.349 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false

### 补充说明（可选）

在我所在的地区，GitHub Proxy https://mirror.ghproxy.com/ 是可以裸连的，是我使用的代理/方法不对吗😂

**Comment by SunshineboyZj** [comment]
删掉所有第三方插件之后，也是如此

**Comment by zeyudada** [comment]
人家要的是http代理，不是镜像
比如clash的代理就是7890端口

**Comment by mo-jinran** [comment]
很抱歉，新版 LiteLoaderQQNT 已移除插件市场，但有社区代替插件：https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store
