### ISSUE TITLE
[Bug]: Error: Cannot find module '...\QQNT\resources\app\LiteLoader'，

### ISSUE THREAD

**Issue by MrAgNO3** [LiteLoaderQQNT/LiteLoaderQQNT#197]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.10

### 运行环境

Windows (64)

### 运行架构

AMD64

### 重现步骤

1. 安装QQNT 9.9.2-16183
2. 安装LiteloaderQQNT，方法是从 Releases 中下载稳定版的方式进行安装
3. 下载并运行LiteLoaderQQNT-PatcherNFixer_x64.exe修补程序 v1.0.1，一键修补 QQ

### 期望的结果是什么？

正常安装liteloader并启动qqnt

### 实际的结果是什么？

启动qqnt报错
![屏幕截图 2023-12-20 150020](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/74173773/51ade717-9f7c-43d4-aafe-aa842131dc0f)

### 补充说明（可选）

根据报错信息，将app目录下的`LiteloaderQQNT`文件夹重命名为`Liteloader`即可成功打开qqnt

![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/74173773/e47f5f7e-9d6a-4f02-91ce-0f317fd06162)

**Comment by INF-C2O** [comment]
好像只是因为修补更改的文件夹名字和实际下载的不一样...神奇

**Comment by mo-jinran** [comment]
现在使用最新版（支持全版本全平台全架构），并且根据官网教程安装
https://liteloaderqqnt.github.io/guide/install.html
