### ISSUE TITLE
[Bug]: 挂梯子了一直显示正在安装是怎么回事

### ISSUE THREAD

**Issue by bingtiansu** [LiteLoaderQQNT/LiteLoaderQQNT#198]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

0.53

### LiteLoaderQQNT 版本 （或 Commit Id）

0.53

### 运行环境

Windows (64)

### 运行架构

None

### 重现步骤

之前是可以的我这个号少个撤回。后面有新版本更新了用旧版本更新一下就显示正在安装

### 期望的结果是什么？

liteloder注入器能更新一下不用挂梯子就能用

### 实际的结果是什么？

无

### 日志记录

无

**Comment by mo-jinran** [comment]
很抱歉，新版 LiteLoaderQQNT 已移除插件市场，但有社区代替插件：https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store
