### ISSUE TITLE
9.9.6 用不了了[Bug]: 

### ISSUE THREAD

**Issue by kkgg0521** [LiteLoaderQQNT/LiteLoaderQQNT#199]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.6

### LiteLoaderQQNT 版本 （或 Commit Id）

lastest

### 运行环境

Windows (64)

### 运行架构

其它

### 重现步骤

"main": "./app_launcher/index.js",

### 期望的结果是什么？

"main": "./app_launcher/index.js",****

### 实际的结果是什么？

"main": "./app_launcher/index.js",

### 日志记录

"main": "./app_launcher/index.js",

### 补充说明（可选）

"main": "./app_launcher/index.js",

**Comment by KNQMuzzi** [comment]
不是只支持到QQ9.9.2.16183吗

**Comment by XokoukioX** [comment]
文档说了现在没有实现 但是有方法 等吧

**Comment by iRonixx0219** [comment]
看安装方法中的支持矩阵

**Comment by mo-jinran** [comment]
等候 1.0.0 正式版 （不过目前无插件适配，等第三方插件开发者适配）
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/66980784/80a8c0c3-34a0-4793-a3c1-4ae05b110a64)

**Comment by mayeths** [comment]
@mo-jinran 请问1.0.0版本和原来的差别大吗？我准备在Linux版上做开发，要不要等1.0.0发布了对应文档再开发，还是可以用0.x.x的版本来开发

**Comment by mo-jinran** [comment]
我重构了，但是区别跟原来不是很大，具体请等待插件模板更新文档

**Comment by mayeths** [comment]
谢谢了，感谢发明LiteLoaderQQNT
