### ISSUE TITLE
[Bug]: QQNT9.9.2.16183版本提示版本过低

### ISSUE THREAD

**Issue by YouYouLip** [LiteLoaderQQNT/LiteLoaderQQNT#202]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2.16183

### LiteLoaderQQNT 版本 （或 Commit Id）

0.5.10

### 运行环境

Windows (64)

### 运行架构

x86

### 重现步骤

在今天我把QQNT退出登录之后 再登录QQNT提示版本过低请升级，我以为是我这里出现了什么bug，然后在用前chronocat无头猫插件上面运行机器人的电脑同样测试了一下，也是提示QQ版本过低

### 期望的结果是什么？

能够在用liteloaderQQNT的情况下登录QQ吧，但是这情况应该要支持更高版本了

### 实际的结果是什么？

登录不上（悲）

**Comment by KagaJiankui** [comment]
扫码暂时还能成功登录

**Comment by iRonixx0219** [comment]
9.9.0但是屏蔽了更新提示，还能用

**Comment by Whuihuan** [comment]
你QQ被风控限制了最低登录版本

**Comment by mo-jinran** [comment]
使用最新版 LiteLoaderQQNT
