### ISSUE TITLE
[bug]macOS QQ6.9.25无法找到QQNT问题

### ISSUE THREAD

**Issue by badcandy0** [LiteLoaderQQNT/LiteLoaderQQNT#203]
如图所示，我通过powershell命令行运行patch.ps1脚本提示以下错误，请问是什么情况？
<img width="941" alt="iShot_2024-01-17_12 28 22" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/54410863/6dc6e89b-4892-4644-8cbd-59d61a6cd867">

**Comment by mo-jinran** [comment]
请使用LiteLoaderQQNT最新版，而且只有Windows才需要Patch
