### ISSUE TITLE
[Bug]: macOS QQNT: 6.9.25-20811 登录页面直接空白

### ISSUE THREAD

**Issue by ChenSiWu** [LiteLoaderQQNT/LiteLoaderQQNT#204]
### QQNT版本
6.9.25-20811
### LiteLoaderQQNT 版本 （或 Commit Id）
LiteLoaderQQNT 0.5.10
### 运行环境
macOS Monterey 12.7
### 运行架构
X86-64 (Native)
### 重现步骤
根据[官网教程](https://liteloaderqqnt.github.io/guide/install.html)进行安装。打开app后，这时候进入设置页面直接奔溃。
index.js
```js
require("/Applications/QQ.app/Contents/Resources/app/app_launcher/LiteLoaderQQNT");
require('./launcher.node').load('external_index', module);
```
### 截图
<img width="690" alt="image" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/12423395/f58f2f31-8f95-4b12-84f1-a23662e98a26">

**Comment by arrio464** [comment]
同样的问题。
目测文档的进度快于Release，尝试直接下载main分支并解压后解决。

**Comment by mayeths** [comment]
@arrio464 的方法有用，但在Linux的xfce桌面上启动QQ使用的是桌面登录账户（比如我桌面登录了alice账户），而安装QQ时我是root用户安装在了`/opt/QQ`下。这导致`LiteLoaderQQNT/src/main.js:144`想拷贝它的`preload.js`到QQNT目录时，权限不够，QQ无法正常启动。

所以，Linux用户可能还需要类似`chown -R alice: /opt/QQ`才能让LiteLoaderQQNT拷贝文件过去。

如果遇到别的错误，可以把[下面的代码](https://stackoverflow.com/a/35542360)加入到`/opt/QQ/resources/app/app_launcher/index.js`的最前面，能让QQ的所有日志输出到`/qq.log`文件，看看啥错误导致无法启动：
```javascript
var access = fs.createWriteStream('/qq.log');
process.stdout.write = process.stderr.write = access.write.bind(access);
process.on('uncaughtException', function(err) {
  console.error((err && err.stack) ? err.stack : err);
});
```
命令行创建`/qq.log`：
```bash
sudo touch /qq.log
chmod 777 /qq.log
```

**Comment by ChenSiWu** [comment]
@arrio464 更新到1.0.0后，直接连页面也不展示了...

**Comment by mo-jinran** [comment]
请使用最新版LiteLoaderQQNT

**Comment by mayeths** [comment]
这个问题没有得到解决；我在MacOS里很轻松就复现了这个问题，尝试了各种办法，不论是哪个1.0以上的LiteLoaderQQNT的数个commit版本，都能复现出来。

### 复现

1. 如果LLQQNT在QQNT目录下`require("./LLQQNT")`，则启动后什么页面也不显示；
2. 如果LLQQNT在QQNT目录外`require("/path/LLQQNT")`，则启动后Nodejs报错EPERM无权限；
3. 如果在`index.js`里使用`var fs = require('fs'); fs.readFileSync("./haha.js")`，则启动后什么页面也不显示；
4. 如果在`index.js`里使用`var fs = require('fs'); fs.readFile("./haha.js")`，则正常启动，但关闭QQ程序时会报错

综上，我判断这个问题与LiteLoaderQQNT的代码无关，而是与Nodejs在MacOS的文件系统中有问题导致的。特别是3. 用`fs.readFileSync`同步读QQNT目录下的文件，也是启动后什么页面也不显示，我判断是读文件无限阻塞了。而4. 用`fs.readFile`异步读文件能正常启动，但关闭程序时有报错，应该是异步读文件未结束的原因。

### 判断

这个MacOS环境里的问题总结为：

- 如果LLQQNT在QQNT的目录下，那么读文件会被阻塞；
- 如果LLQQNT在QQNT的目录外，那么读文件会直接拒绝EPERM。

### 尝试

为此，需要解决**在Mac上无法正常读文件的问题**，我尝试了两种办法：

- 在MacOS的系统设置里`Security & Privacy -> Full Disk Access`里给QQ完全文件系统权限，没用
- 将LLQQNT的文件夹权限设置为777，没用

暂时没有更多的想法来解决问题。对MacOS机制有更多了解的朋友可以尝试一下

**Comment by mo-jinran** [comment]
你需要关闭SIP，并将`LiteLoaderQQNT/src/preload.js`文件手动复制到`/Applications/QQ.app/Contents/Resources/app/versions/版本号/application`目录下
