### ISSUE TITLE
文件损坏，不能打开

### ISSUE THREAD

**Issue by JevonGit** [LiteLoaderQQNT/LiteLoaderQQNT#206]
修改main后面那一行后，QQ就打不开了，用那个修复工具也不管用啊

**Comment by Whuihuan** [comment]
QQ版本高于9.9.2-16183后就没用

**Comment by adoin** [comment]
一样，版本9.9.7
index.js更改，免验证补丁打了 没用

**Comment by Whuihuan** [comment]
> 一样，版本9.9.7 index.js更改，免验证补丁打了 没用

试试新发布的1.0，旧版只支持到9.9.2-16183

**Comment by adoin** [comment]
> > 一样，版本9.9.7 index.js更改，免验证补丁打了 没用
> 
> 试试新发布的1.0，旧版只支持到9.9.2-16183

就是新版的。。

**Comment by KelseySking** [comment]
我用的997版本就没问题
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/62224263/08ebb82e-687c-4c1d-9d3f-f37747b2fd40)

**Comment by adoin** [comment]
> 我用的997版本就没问题 ![image](https://private-user-images.githubusercontent.com/62224263/298479617-08ebb82e-687c-4c1d-9d3f-f37747b2fd40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDQ2NjYsIm5iZiI6MTcwNTkwNDM2NiwicGF0aCI6Ii82MjIyNDI2My8yOTg0Nzk2MTctMDhlYmI4MmUtNjg3Yy00YzFkLTlkM2YtZjM3NzQ3YjJmZDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA2MTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZjE0ZDBlMTE2NDBkYzMyMWI5Nzk1OWQxNWM3MjRkZjE0MTQ4MjRiZWYzMzg2NTA3N2NhMGRjYjRlMmIyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49KXTfJb0ZJPurMHghvYyTq8szaD5TXIEWQLax_qYLE)

我看了下版本，我居然是32位的。。。为啥我会安装成32位的啊、、、

**Comment by Whuihuan** [comment]
> > 我用的997版本就没问题 ![image](https://private-user-images.githubusercontent.com/62224263/298479617-08ebb82e-687c-4c1d-9d3f-f37747b2fd40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDQ2NjYsIm5iZiI6MTcwNTkwNDM2NiwicGF0aCI6Ii82MjIyNDI2My8yOTg0Nzk2MTctMDhlYmI4MmUtNjg3Yy00YzFkLTlkM2YtZjM3NzQ3YjJmZDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA2MTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZjE0ZDBlMTE2NDBkYzMyMWI5Nzk1OWQxNWM3MjRkZjE0MTQ4MjRiZWYzMzg2NTA3N2NhMGRjYjRlMmIyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49KXTfJb0ZJPurMHghvYyTq8szaD5TXIEWQLax_qYLE)
> 
> 我看了下版本，我居然是32位的。。。为啥我会安装成32位的啊、、、

破案了，这个patch只patch64的，32位难怪无效

**Comment by KelseySking** [comment]
> > 我用的997版本就没问题 [![image](https://private-user-images.githubusercontent.com/62224263/298479617-08ebb82e-687c-4c1d-9d3f-f37747b2fd40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDQ2NjYsIm5iZiI6MTcwNTkwNDM2NiwicGF0aCI6Ii82MjIyNDI2My8yOTg0Nzk2MTctMDhlYmI4MmUtNjg3Yy00YzFkLTlkM2YtZjM3NzQ3YjJmZDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA2MTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZjE0ZDBlMTE2NDBkYzMyMWI5Nzk1OWQxNWM3MjRkZjE0MTQ4MjRiZWYzMzg2NTA3N2NhMGRjYjRlMmIyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49KXTfJb0ZJPurMHghvYyTq8szaD5TXIEWQLax_qYLE)](javascript:void(0))
> 
> 我看了下版本，我居然是32位的。。。为啥我会安装成32位的啊、、、

官网默认64位的吧，哈哈怎么搞的32位

**Comment by adoin** [comment]
> > > 我用的997版本就没问题 ![image](https://private-user-images.githubusercontent.com/62224263/298479617-08ebb82e-687c-4c1d-9d3f-f37747b2fd40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDQ2NjYsIm5iZiI6MTcwNTkwNDM2NiwicGF0aCI6Ii82MjIyNDI2My8yOTg0Nzk2MTctMDhlYmI4MmUtNjg3Yy00YzFkLTlkM2YtZjM3NzQ3YjJmZDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA2MTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZjE0ZDBlMTE2NDBkYzMyMWI5Nzk1OWQxNWM3MjRkZjE0MTQ4MjRiZWYzMzg2NTA3N2NhMGRjYjRlMmIyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49KXTfJb0ZJPurMHghvYyTq8szaD5TXIEWQLax_qYLE)
> > 
> > 
> > 我看了下版本，我居然是32位的。。。为啥我会安装成32位的啊、、、
> 
> 官网默认64位的吧，哈哈怎么搞的32位

不知道。。。我是第一批测试NT的，不知道是不是沿用那时候的更新就是32的

**Comment by Whuihuan** [comment]
> > > > 我用的997版本就没问题 ![image](https://private-user-images.githubusercontent.com/62224263/298479617-08ebb82e-687c-4c1d-9d3f-f37747b2fd40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDQ2NjYsIm5iZiI6MTcwNTkwNDM2NiwicGF0aCI6Ii82MjIyNDI2My8yOTg0Nzk2MTctMDhlYmI4MmUtNjg3Yy00YzFkLTlkM2YtZjM3NzQ3YjJmZDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA2MTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZjE0ZDBlMTE2NDBkYzMyMWI5Nzk1OWQxNWM3MjRkZjE0MTQ4MjRiZWYzMzg2NTA3N2NhMGRjYjRlMmIyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49KXTfJb0ZJPurMHghvYyTq8szaD5TXIEWQLax_qYLE)
> > > 
> > > 
> > > 我看了下版本，我居然是32位的。。。为啥我会安装成32位的啊、、、
> > 
> > 
> > 官网默认64位的吧，哈哈怎么搞的32位
> 
> 不知道。。。我是第一批测试NT的，不知道是不是沿用那时候的更新就是32的

你没换过就一直是32，我是首个64出了就马上换掉32的

**Comment by RingingVolcano** [comment]
我的QQ是64位v9.9.7 打了补丁之后应该是能用的

**Comment by mo-jinran** [comment]
请根据官网的教程进行安装，新版本不要修改main键值
https://liteloaderqqnt.github.io/guide/install.html
