### ISSUE TITLE
[Bug]: 登录界面异常

### ISSUE THREAD

**Issue by RawDiamondMC** [LiteLoaderQQNT/LiteLoaderQQNT#211]
除了背景啥都没...

[4601a43](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/4601a430d3b1d79ff2686ebad5cce39947a328df)

![图片](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/112449001/e3ff69c0-8f47-4064-991d-dbd0526e2c8b)

**Comment by RUnknown** [comment]
+1，换回昨天的版本就正常了...

**Comment by DaBoSAMA** [comment]
最新版本应该正常了
