### ISSUE TITLE
无法重新打开已关闭的插件

### ISSUE THREAD

**Issue by RingingVolcano** [LiteLoaderQQNT/LiteLoaderQQNT#214]
在设置的插件列表中关闭已安装的插件后重启QQ，被关闭的插件在重启后于插件列表内消失，无法再次重新打开。
（图片中关闭了QQ增强和工具箱两个插件，重启后插件在列表消失）
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/72140353/a4ab312c-b219-4c41-852c-a6a57021626e)

各组件版本：
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/72140353/32778f0e-69ee-479c-a2ba-e4eb5ac781f3)

**Comment by mo-jinran** [comment]
已更新，在1.0.2版本
