### ISSUE TITLE
希望插件列表加个滚动条

### ISSUE THREAD

**Issue by shi-an** [LiteLoaderQQNT/LiteLoaderQQNT#215]
插件过多时调整窗口大小才能显示全部插件
![e7d8f3509699688ba9bb113ab46a66db](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/79352488/c1a34d52-0d66-4f45-8759-e0ec5be42a0f)

**Comment by mo-jinran** [comment]
已更新，在1.0.2版本
