### ISSUE TITLE
想搞插件、有没有更详细些的开发文档呢？

### ISSUE THREAD

**Issue by adoin** [LiteLoaderQQNT/LiteLoaderQQNT#216]
比如打开聊天的钩子
从任务栏弹出的钩子
最小化的钩子
等等事件钩子、哪些是有的？

**Comment by adoin** [comment]
还有除了fs写入data之外，怎么维护一份本地持久数据呢 Local Storage吗？

**Comment by mo-jinran** [comment]
官网开发文档中写的，就是全部了，剩下的需要你自己看Electron的开发文档与Node.js的

**Comment by mo-jinran** [comment]
也可以使用社区开发的LLAPI来帮助你实现一些QQNT功能
https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-LLAPI
