### ISSUE TITLE
部分界面会闪现并出现色块

### ISSUE THREAD

**Issue by LynxCatTheThird** [LiteLoaderQQNT/LiteLoaderQQNT#221]
# 问题描述

如以下录屏，自带商店界面有色块出现

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/758ab898-3c21-4a2f-97d6-aca380c77c94

启用 [DeepL 翻译插件](https://github.com/MUKAPP/LiteLoaderQQNT-DeepL)后问题范围扩大到个人聊天界面。打到个人聊天界面后有色块出现，滚动群聊列表色块会闪动，同时群聊头像也会闪动。

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/450d1b1d-0c0b-4468-8cf1-11dfd9abff24

而群聊则不会

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/7485bd71-35e0-4d4a-b09c-dd386390dde5

结合 Transitio，有问题的元素有
1. `.list-item__avatar > .avatar, .list-item__avatar > .recent-contact-item__phone,`
2. `.secondary-info,`（极有可能）

# 控制台报错
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/e11ee5e1-a466-432c-b1da-3ae45df57dc5)

# 相关信息

## 版本信息
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/0bd43859-bb6b-4dff-9ae0-a849a6210ce8)

## 系统信息
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/792adcef-63ed-498c-a04e-19cac9e90d0b)

## 插件列表
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/3b9ba460-01aa-4f19-8a10-7092ff5c9a9e)
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/e1836377-f6eb-4ca7-b87c-9849a26d95b0)

## 安装信息
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/96b5c628-afb9-4a8c-8eb8-c49fe86d8260)
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/103188954/ca07a5a1-a754-441d-923b-dfebc9eefc57)

**Comment by mo-jinran** [comment]
非框架本体的问题，以及插件商店属于第三方插件，在1.0版本后官方插件市场已废弃，并未内置
