### ISSUE TITLE
macOS上部分插件显示“无法下载”,请问是什么原因造成的

### ISSUE THREAD

**Issue by Tinyu-Zhao** [LiteLoaderQQNT/LiteLoaderQQNT#223]
<img width="952" alt="image" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/44396641/4f126c5b-b359-4e65-9b2d-1c317528d6ef">

**Comment by xiyuesaves** [comment]
目前插件市场是作为第三方插件安装的，请到对应仓库提 issue [Plugin-Store](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store)

**Comment by qiuzilu** [comment]
直接点"详情"，去仓库下载就好啦

**Comment by Tinyu-Zhao** [comment]
> 直接点"详情"，去仓库下载就好啦

谢谢啦
