### ISSUE TITLE
功能建议 liteloaderQQNT在QQ更新后自动补全index.js文件

### ISSUE THREAD

**Issue by heerxingen** [LiteLoaderQQNT/LiteLoaderQQNT#226]
如题，QQNT更新之后会把这文件恢复回去阿巴阿巴

**Comment by RtRuoli** [comment]
感觉这个不太可能实现，更新之后index.js文件被恢复了，恢复了就不能加载框架，加载不了框架就没法修复index.js，这不闭环么（笑）

**Comment by lamprose** [comment]
自己写个脚本，每次更新后运行一下就行了

**Comment by heerxingen** [comment]
或许能检测到更新然后弹出个窗口问’你是要更新吗’？
但是好像也不太好搞
