### ISSUE TITLE
安装插件后，部分插件未在扩展列表里显示

### ISSUE THREAD

**Issue by Sunsh4j** [LiteLoaderQQNT/LiteLoaderQQNT#229]
rt，从0.x更新到最新版，然后又把所有的插件手动安装了一遍
但是发现有很多插件未在扩展列表里显示，消失的那部分插件都已经对1.x做了适配，但就是没有显示

**Comment by ChenXu233** [comment]
+1

**Comment by remyhuang03** [comment]
可以尝试手工下载相关插件粘贴到plugins文件夹中，然后重启QQ

**Comment by arenekosreal** [comment]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/17194552/1ba8e508-eb22-4ba2-8050-4b74eb18e48a)
确实，使用 Linux 版本，终端输出里面都正常，但是已安装的插件列表里面没有完全显示出来
另外下面的“本体位置”和“数据位置”也没有显示具体值，不过按照终端输出来看是能正确读取环境变量里面指定的数据位置的

**Comment by mo-jinran** [comment]
这是因为配置界面在解析插件清单时，有些插件没按照规范写导致内部报错所以没显示，已在几周前修复，直接拉取仓库使用即可

**Comment by mo-jinran** [comment]
我是说修复后的代码已经上传到仓库内，还没发布新版本，你需要自己手动拉取源代码使用，或者再等等发布新版

**Comment by mo-jinran** [comment]
根据安装教程重新来一遍就行了

**Comment by arenekosreal** [comment]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/17194552/efb1c915-1afc-4516-b6d2-5b8fba3a07c1)
更新到 1.1.0 之后倒是能在左侧显示，但是 LiteLoaderQQNT 页面内的插件列表仍然没有修复，不过下面的目录信息倒是恢复了

**Comment by BoXueDuoCai** [comment]
> 更新到1.1.1， LiteLoaderQQNT 页面内的插件列表显示仍然是只有部分插件

我是直接全都不显示了ha

**Comment by 1003999458** [comment]
![QQ截图20240604104526](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/38431629/4a36a210-9fe7-4d77-b15b-fbe2a94bd5e5)
![QQ截图20240604105217](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/38431629/ede39aa7-67ef-45b5-ab38-12bc14ee25e5)
我也不显示插件了

**Comment by LINKlang** [comment]
一样不全显示
windows系统
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/116951234/4d0c0aed-2321-4008-adae-7b0a1c87f336)
