### ISSUE TITLE
希望作者能支持一下markdown渲染

### ISSUE THREAD

**Issue by misaka10384** [LiteLoaderQQNT/LiteLoaderQQNT#230]
如标题  原本的[markdown渲染](https://github.com/d0j1a1701/LiteLoaderQQNT-Markdown)的插件作者好像不做了

**Comment by cdc12345** [comment]
有人帮忙修复了新版本,这个插件目前能用了,而且Liteloader是一个loader,一般来说不应该去支持这个

**Comment by misaka10384** [comment]
> 有人帮忙修复了新版本,这个插件目前能用了,而且Liteloader是一个loader,一般来说不应该去支持这个

一般来说确实  这不是指望作者能亲自下场做个插件嘛
