### ISSUE TITLE
安装LiteLoader后QQNT在非管理员模式下启动时会报错

### ISSUE THREAD

**Issue by It-is-Sean** [LiteLoaderQQNT/LiteLoaderQQNT#232]
如题
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/122372814/f786850d-be99-481e-8d3e-eef397eaf118)

**Comment by cdc12345** [comment]
虽然我不是开发者,但还是吐槽一下,这个预计是你电脑的问题,很多权限比较严格的电脑时常出现这样的事情

**Comment by mo-jinran** [comment]
设置环境变量解决此问题
https://liteloaderqqnt.github.io/guide/install.html#存储目录
