### ISSUE TITLE
macOS QQ 不能正常启动

### ISSUE THREAD

**Issue by lipei007** [LiteLoaderQQNT/LiteLoaderQQNT#234]
将LiteLoaderQQNT 放到 ~/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/global/extensions/LiteLoaderQQNT

```
require(String.raw`/Users/jack/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/global/extensions/LiteLoaderQQNT`);
require('./launcher.node').load('external_index', module);
```

启动QQ没界面出现，控制台输出
```
[LiteLoader] Start finding all plugins.
[LiteLoader] The plugins directory does not exist.
[LiteLoader] A new plugin directory will be created:/Users/jack/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/global/extensions/LiteLoaderQQNT/plugins
[preload] register done. launcher.node
[preload] register done. major.node
[bytecode]current path: /Applications/QQ.app/Contents/Resources/app/application/
[preload] register done. wrapper.node
[LiteLoader] Plugins directory created successfully!
```
到此就没有其他消息了

**Comment by lipei007** [comment]
QQ 版本： 6.9.23-19689

**Comment by ojifgl** [comment]
Windows端QQ9.9.0-14569也会出现这个问题

**Comment by Zker67** [comment]
+1，系统是 sonoma14.2，即使给了终端所有文件和修改其他应用权限也是这样

**Comment by wyshp** [comment]
+1
也是在 MAC下也是无法正常使用插件，好不容易插件装上进 QQ 了还闪退

**Comment by suenley** [comment]
+1

**Comment by guozhigq** [comment]
> 将LiteLoaderQQNT 放到 ~/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/global/extensions/LiteLoaderQQNT
> 
> ```
> require(String.raw`/Users/jack/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/global/extensions/LiteLoaderQQNT`);
> require('./launcher.node').load('external_index', module);
> ```
> 
> 启动QQ没界面出现，控制台输出
> 
> ```
> [LiteLoader] Start finding all plugins.
> [LiteLoader] The plugins directory does not exist.
> [LiteLoader] A new plugin directory will be created:/Users/jack/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/global/extensions/LiteLoaderQQNT/plugins
> [preload] register done. launcher.node
> [preload] register done. major.node
> [bytecode]current path: /Applications/QQ.app/Contents/Resources/app/application/
> [preload] register done. wrapper.node
> [LiteLoader] Plugins directory created successfully!
> ```
> 
> 到此就没有其他消息了

是通过什么方式启动的QQ呢，我在 【应用程序 - QQ - Contents - MacOS - QQ】 启动时，会提示一些权限问题。
把 【LiteLoaderQQNT - src - preload.js】文件复制到 QQ 目录跟 **app_launcher** 同级的 **application** 文件夹下可以启动了

**Comment by ghostflyby** [comment]
试试看文件放到沙盒内。`/Users/user/Library/Containers/com.tencent.qq/`下都可以。
