### ISSUE TITLE
[BUG]进出QQ频道的语音一次后,图片和设置等界面不再弹出

### ISSUE THREAD

**Issue by boitar** [LiteLoaderQQNT/LiteLoaderQQNT#237]
在win11和mac上均做过测试,均能100%复现
复现步骤:
1. 打开QQ频道
2. 随意进入一个音视频频道
3. 退出音视频频道
4. 所有图片无法点击打开查看大图,同时无法打开设置界面,所有弹出类窗口无法弹出

**Comment by boitar** [comment]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/49229338/75875a7b-1e00-4756-947e-c2b393bc5a9e)
![bdc049d06ea7842c419588543c4acc52](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/49229338/b72d7703-7b16-4ea2-8d46-092de3b6524f)

**Comment by cdc12345** [comment]
貌似只要是弹出式的窗口都会在上诉操作后无法正常弹出()()()

**Comment by boitar** [comment]
> 貌似只要是弹出式的窗口都会在上诉操作后无法正常弹出 ()()()

是的，目前每次进出完频道语音后都只能重新登录才能恢复正常

**Comment by b6e0** [comment]
我这里屏幕共享后也会出现类似 bug

**Comment by mo-jinran** [comment]
已在此提交中修复 #252 等待发新版
