### ISSUE TITLE
群文件无法正常使用

### ISSUE THREAD

**Issue by Raiden-Yayi** [LiteLoaderQQNT/LiteLoaderQQNT#239]
安装之后群文件无法刷新出文件

**Comment by cdc12345** [comment]
请注意issue提出原则,您需要给出以下信息以保证开发者能够定位错误原因:

1. 您运行liteloaderqqnt的运行日志
2. 您运行liteloaderqqnt的插件列表

开发者是学生,时间并不多,所以您可能需要进行自查.

1. 在暂时卸载掉liteloaderqqnt后尝试再次刷新群文件,二次判断是否为liteloaderqqnt的原因

**Comment by Avenger233** [comment]
你是不是同时安装了轻量工具箱和QQ增强
https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues/129
