### ISSUE TITLE
插件安装失败

### ISSUE THREAD

**Issue by HumanMus1c** [LiteLoaderQQNT/LiteLoaderQQNT#240]
本人使用的项目[https://github.com/Mzdyl/LiteLoaderQQNT_Install](url)安装的，

进入插件市场安装任意插件都提示错误：
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/46023154/625de705-678f-4be0-b9ab-a8196f076eae)
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/46023154/4503aee3-4a11-4b0a-bee9-3ac4d7d47085)
QQ相关信息
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/46023154/c1931a9e-acb8-4a26-81c7-0ae43aac3a82)
插件相关信息
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/46023154/71b851c1-5961-4b74-87f4-8c09b5f86bd7)

**Comment by cdc12345** [comment]
首先,插件商店和Loader就想婆孙关系,在这里问干嘛?
然后,你这是权限问题,建议把数据目录位置改一下,改到权限宽松的地方.你也可以自己去搜如何解除UAC

**Comment by cdc12345** [comment]
附上插件商店的链接:
https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store
然后就是这个项目已经停更了()

**Comment by HumanMus1c** [comment]
抱歉，刚开始摸索这个项目，还不了解。还有类似该项目的插件商店吗？

**Comment by cdc12345** [comment]
> 抱歉，刚开始摸索这个项目，还不了解。还有类似该项目的插件商店吗？

貌似没了()
