### ISSUE TITLE
LLAPI版本过低

### ISSUE THREAD

**Issue by WSQ0127** [LiteLoaderQQNT/LiteLoaderQQNT#242]
求助，每次打开后都会显示
![](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/128284134/f15b117b-6afd-4f32-8cc8-a9040b8fba36)
不影响正常使用，但是得点一下，很烦

* LiteLoderQQ：1.0.3
* QQNT：9.9.7-21173
* Chromiun：120.0.6099.56
* Electron：28.0.0
* Node.js：18.18.2
* 插件列表：
    * DeepL
    * markdown-it
    * QQ增强
    * 轻量工具箱
    * 防撤回
    * QQRedPackGetter

**Comment by lelucermaire17** [comment]
同，今天刚接触liteloder，安装完就显示这个

**Comment by mo-jinran** [comment]
这是第三方插件，请按照提示更新插件，或转移到此仓库
https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-LLAPI/tree/main

**Comment by lelucermaire17** [comment]
> 求助，每次打开后都会显示 ![](https://private-user-images.githubusercontent.com/128284134/311482943-f15b117b-6afd-4f32-8cc8-a9040b8fba36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjk2MjMsIm5iZiI6MTcxMDgyOTMyMywicGF0aCI6Ii8xMjgyODQxMzQvMzExNDgyOTQzLWYxNWIxMTdiLTZhZmQtNGYzMi04Y2M4LWE5MDQwYjhmYmEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwNjIyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjI1ZWM5NTI5ZDUzMjM5NjFmNTg3ZjU0ZDM1MDIwMTMyZmZmNDdhZGYxMjcwZWZhN2M1MTM1YzRlYTk3MjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.46hJ4FH-rfYKfYdSATmtMd2Urq1bYVcw28Fh-KnnVYY) 不影响正常使用，但是得点一下，很烦
> 
> * LiteLoderQQ：1.0.3
> * QQNT：9.9.7-21173
> * Chromiun：120.0.6099.56
> * Electron：28.0.0
> * Node.js：18.18.2
> * 插件列表：
>   
>   * DeepL
>   * markdown-it
>   * QQ增强
>   * 轻量工具箱
>   * 防撤回
>   * QQRedPackGetter

我装了插件市场后面，在插件市场里面有新版LLAPI更新

**Comment by WSQ0127** [comment]
> 这是第三方插件，请按照提示更新插件，或转移到此仓库 https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-LLAPI/tree/main

> > 求助，每次打开后都会显示 ![](https://private-user-images.githubusercontent.com/128284134/311482943-f15b117b-6afd-4f32-8cc8-a9040b8fba36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjk2MjMsIm5iZiI6MTcxMDgyOTMyMywicGF0aCI6Ii8xMjgyODQxMzQvMzExNDgyOTQzLWYxNWIxMTdiLTZhZmQtNGYzMi04Y2M4LWE5MDQwYjhmYmEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQwNjIyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjI1ZWM5NTI5ZDUzMjM5NjFmNTg3ZjU0ZDM1MDIwMTMyZmZmNDdhZGYxMjcwZWZhN2M1MTM1YzRlYTk3MjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.46hJ4FH-rfYKfYdSATmtMd2Urq1bYVcw28Fh-KnnVYY) 不影响正常使用，但是得点一下，很烦
> > 
> > * LiteLoderQQ：1.0.3
> > * QQNT：9.9.7-21173
> > * Chromiun：120.0.6099.56
> > * Electron：28.0.0
> > * Node.js：18.18.2
> > * 插件列表：
> >   
> >   * DeepL
> >   * markdown-it
> >   * QQ增强
> >   * 轻量工具箱
> >   * 防撤回
> >   * QQRedPackGetter
> 
> 我装了插件市场后面，在插件市场里面有新版LLAPI更新

感谢
