### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by zone1889** [LiteLoaderQQNT/LiteLoaderQQNT#243]
为什么安装了qqnt-ll 1.0.3没有显示插件市场和已安装插件，plugins里安装了插件，也未生效，
是因为qq版本吗9.9.421484

**Comment by mo-jinran** [comment]
可能是版本太低，没测试过这么低的版本（尝试更新QQNT

**Comment by zone1889** [comment]
现在是9.9.7-21484，仍然无法查看插件市场



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月15日 19:32 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LiteLoaderQQNT/LiteLoaderQQNT] 疑问 (Issue #243) |

可能是版本太低，没测试过这么低的版本（尝试更新QQNT

**Comment by mo-jinran** [comment]
自从1.x版本开始不自带插件市场，0.x版本插件市场已经弃用，请寻找第三方插件市场插件，或查看官网寻找插件
