### ISSUE TITLE
无法加载框架

### ISSUE THREAD

**Issue by YinLiaoQwQ** [LiteLoaderQQNT/LiteLoaderQQNT#245]
更新到9.9.7-21804 (64位)之后，QQNT目录下不存在QQNT/resources/app/versions/此处为版本号/application文件夹了
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/32790396/a226f331-b06b-464d-aedc-c1c392e26700)

**Comment by linguo2625469** [comment]
不用application啊  直接去app_launcher里/index.js修改文件就好了 具体看文档

**Comment by mo-jinran** [comment]
application是需要手动创建的，以及默认情况下直接修改app_launcher/index.js即可
