### ISSUE TITLE
在Ubuntu 22.04 LTS中使用无法加载出登录界面

### ISSUE THREAD

**Issue by Yuzu-io** [LiteLoaderQQNT/LiteLoaderQQNT#247]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/69612382/c91a0b51-030d-437f-9b27-0aca4f87eeec)

没有插入require(String.raw`xxxxx`); 时启动可以登录，插入之后就加载不出

显示为如下：
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/69612382/506f80dc-fb3d-4de1-ac1e-bf860e9dff15)

**Comment by mo-jinran** [comment]
https://liteloaderqqnt.github.io/guide/install.html#%E5%AE%89%E8%A3%85-1

确保QQNT/resources/app/versions/此处为版本号/application/preload.js存在并与LiteLoaderQQNT/src/preload.js一致

**Comment by Yuzu-io** [comment]
> https://liteloaderqqnt.github.io/guide/install.html#%E5%AE%89%E8%A3%85-1
> 
> 确定QQNT/resources/app/versions/此处为版本号/application/preload.js存在并与LiteLoaderQQNT/src/preload.js一致

我的ubuntu安装的QQNT没有QQNT/resources/app/versions/此处为版本号/application而是/QQ/resources/app/application。
我把preload.js丢到了/QQ/resources/app/application里面
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/69612382/47f3f476-dca8-4d4a-a474-f3ae887b92ce)
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/69612382/7ab2ddaf-e36d-45ec-99af-02a58515c6a8)

**Comment by mo-jinran** [comment]
尝试更新LiteLoaderQQNT 1.1.0版本

**Comment by Yuzu-io** [comment]
> 尝试更新LiteLoaderQQNT 1.1.0版本

ok,好了
