### ISSUE TITLE
QQNT更新后已无法使用LiteLoader

### ISSUE THREAD

**Issue by ZhuFengDream** [LiteLoaderQQNT/LiteLoaderQQNT#249]
2024年3月19日晚的QQNT更新后已无法使用LiteLoader（版本为9.9.8-22165 (64位)）

**Comment by ZhuFengDream** [comment]
![微信图片_20240319230621](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/126370716/2d46dd19-3865-4c1d-8c06-ff0c4ac603c8)

**Comment by xiyuesaves** [comment]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/25543545/e2e85d45-e03b-40d2-b4ef-913983a3149a)
你不觉得这个路径有什么问题吗？

**Comment by ZhuFengDream** [comment]
> ![image](https://private-user-images.githubusercontent.com/25543545/314401567-e2e85d45-e03b-40d2-b4ef-913983a3149a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjkzODMsIm5iZiI6MTcxMDkyOTA4MywicGF0aCI6Ii8yNTU0MzU0NS8zMTQ0MDE1NjctZTJlODVkNDUtZTAzYi00MGQyLWI0ZWYtOTEzOTgzYTMxNDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDEwMDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1M2IzNzc4MDJmYWRjYWYxNDhjMDdmZDIwYWIwYjVhODcyYThjMTUyMTM3ODdhNjAxNTliZjE3NDViN2Y3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5qME7_CgeFq2eJOjpWitWRvz43MmGRZKeM4hEaDX7c8) 你不觉得这个路径有什么问题吗？

现在解决了，我直接LiteLoaderQQNT_Install一键安装了
