### ISSUE TITLE
新插件请求

### ISSUE THREAD

**Issue by SoudayoWwww** [LiteLoaderQQNT/LiteLoaderQQNT#250]
![1](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/52328223/9727e83c-e5b8-48e6-83bf-abbbcccbb0ea)

缩放图片的时候画面正中间会出现持续时间巨长的低透明度提示框，看一些大图的时候经常影响，老版本qq我记得这个东西是出现在画面下方而且消失地很快的。

之前在[LiteLoaderQQNT-lite_tools](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)作者issue内请求上述内容，但由于作者[暂停接受新功能请求](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues/175)，暂时无精力开发新内容，遂希望有新的开发者能开发上述内容。

**Comment by AkatsukiZhang** [comment]
我有一个建议就是可以使用[media-local-view](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View)这个插件用系统自带的图片浏览器打开聊天消息图片，不过缺点就是无法按顺序查看图片消息

**Comment by SoudayoWwww** [comment]
> 我有一个建议就是可以使用[media-local-view](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View)这个插件用系统自带的图片浏览器打开聊天消息图片，不过缺点就是无法按顺序查看图片消息

有两个问题，一是win10自带的系统默认浏览器bug非常多，使用起来体验完全不如一些第三方图片浏览器；二是我目前很依赖[LiteLoaderQQNT-lite_tools](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)的`快速关闭预览图片`功能，这个快速关闭极大提升了日常聊天看图的体验（虽然这个功能在老版本qq一直是自带的，不清楚qqnt为什么要给他去除了）。上述提到的无法顺序查看的缺点也非常的致命。

**Comment by AkatsukiZhang** [comment]
> 有两个问题，一是win10自带的系统默认浏览器bug非常多，使用起来体验完全不如一些第三方图片浏览器；二是我目前很依赖[LiteLoaderQQNT-lite_tools](https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools)的`快速关闭预览图片`功能，这个快速关闭极大提升了日常聊天看图的体验（虽然这个功能在老版本qq一直是自带的，不清楚qqnt为什么要给他去除了）。上述提到的无法顺序查看的缺点也非常的致命。

目前我用的是[HoneyView](https://www.bandisoft.com/honeyview/)，可以自定义一些快捷操作，我也是被qqnt搞的(x

**Comment by SoudayoWwww** [comment]
> 目前我用的是[HoneyView](https://www.bandisoft.com/honeyview/)，可以自定义一些快捷操作，我也是被qqnt搞的(x

收到，确实比系统自带舒服一些，不过我issue先开着吧，说不定有大佬真的会做新插件（

**Comment by PRO-2684** [comment]
https://github.com/PRO-2684/Transitio-user-css/blob/main/image-viewer.css

**Comment by SoudayoWwww** [comment]
> https://github.com/PRO-2684/Transitio-user-css/blob/main/image-viewer.css

感谢
