### ISSUE TITLE
mac环境下node无法使用child_process调用/usr/local/bin/ffmpeg

### ISSUE THREAD

**Issue by zyzdai** [LiteLoaderQQNT/LiteLoaderQQNT#251]
An unknown error occurred. Details: Error: Command failed: ffmpeg -y -i "/Users/zyzdai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/data/text_to_speech/tts.wav" -acodec pcm_s16le -f s16le -ac 1 -ar 24000 "/Users/zyzdai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/data/text_to_speech/tts.wav.wav" -loglevel error
/bin/sh: ffmpeg: command not found
插件代码在windows环境下可完美运行。

**Comment by zyzdai** [comment]
An unknown error occurred. Details: Error: Command failed: /usr/local/bin/ffmpeg -y -i "/Users/zyzdai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/data/text_to_speech/tts.wav" -acodec pcm_s16le -f s16le -ac 1 -ar 24000 "/Users/zyzdai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/data/text_to_speech/tts.wav.wav" -loglevel error
/bin/sh: /usr/local/bin/ffmpeg: Operation not permitted

**Comment by mo-jinran** [comment]
第三方插件的问题不应该提到框架下，而且你这个报错是权限不足
