### ISSUE TITLE
无法使用qq小程序

### ISSUE THREAD

**Issue by fly-over-ocean** [LiteLoaderQQNT/LiteLoaderQQNT#253]
win11，安装完LiteLoaderQQNT后即使不按装任何插件，也无法使用qq小程序，例如手机分享的b站视频，双击后没有反应。卸载liteloader后可以正常使用qq小程序。
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/116910180/74fbeafe-d3b8-4af6-80b2-4a695f604950)

**Comment by mo-jinran** [comment]
已在此 [Commit](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/946abb0a1d9d2f53698b964cdc1545d18774b2ee) 中修复
