### ISSUE TITLE
无法安装插件

### ISSUE THREAD

**Issue by qxsck** [LiteLoaderQQNT/LiteLoaderQQNT#254]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/118588391/5e4033a3-2d7c-4a42-9c10-69a71512ef89)

**Comment by mo-jinran** [comment]
第三方插件问题，请勿发到此项目下

**Comment by qxsck** [comment]
> 第三方插件问题，请勿发到此项目下

抱歉
