### ISSUE TITLE
新插件请求，去掉对面设置的自动回复

### ISSUE THREAD

**Issue by Zane-Zzx** [LiteLoaderQQNT/LiteLoaderQQNT#260]
就是屏蔽掉这种自动回复，不要显示在屏幕上，或者顶多显示一次，不然看着很恼人。

![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/75843496/c9c96c02-5c52-4074-87b3-167627b46632)

**Comment by mo-jinran** [comment]
https://github.com/elegantloneliness/qqMessageBlocker/tree/main
