### ISSUE TITLE
新插件请求-好友状态统计

### ISSUE THREAD

**Issue by jhqwqmc** [LiteLoaderQQNT/LiteLoaderQQNT#261]
监控好友的状态变更并且记录时间 (记录变更后的状态)
可以设置触发记录的状态
可以通过 日期/好友名称/状态 来搜索记录
查看记录的入口插入到
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/113768629/f4a795d4-d80d-4bd6-a580-3454ec52adc1)

**Comment by Shapaper233** [comment]
@jhqwqmc 请问是已经有插件实现了吗？

**Comment by jhqwqmc** [comment]
无
