### ISSUE TITLE
然后插件商店空白

### ISSUE THREAD

**Issue by gttuytyt** [LiteLoaderQQNT/LiteLoaderQQNT#262]
求助我重新安装 LiteLoaderQQNT然后插件商店空白怎么办
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/155792023/e49a788d-47a9-49cd-adbf-0af6d8eaaf8e)

**Comment by mo-jinran** [comment]
第三方插件问题请勿发送到框架下，请前往对应插件仓库下提  https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store

**Comment by mo-jinran** [comment]
如果目前真的等不及想用 eee 做的部分插件
可以编辑 LiteLoaderQQNT/src/setting/renderer.js 的第42行下面新建一行，写入nav_item.classList.add("liteloader");
