### ISSUE TITLE
更新至1.1.0后插件商店崩溃

### ISSUE THREAD

**Issue by yige-yigeren** [LiteLoaderQQNT/LiteLoaderQQNT#263]
LiteLoader 1.1.0
QQNT 9.9.9-22741
加载方式为DLL注入
旧版商店：
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/53390868/c081b87d-6dbc-421f-b1cc-5b3ba6ec7c18)
新版：
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/53390868/a115f5b4-a5ab-4dbf-84de-50b55244f997)
启用的扩展：
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/53390868/02c17db8-ea58-4756-bd90-bfb45caab0ad)

**Comment by susgsudvgshghg** [comment]
可以先回退到1.0.3，目前此版本依然可用

**Comment by mo-jinran** [comment]
第三方插件问题请勿发送到框架下，请前往对应插件仓库下提 https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store

**Comment by mo-jinran** [comment]
如果目前真的等不及想用 eee 做的部分插件
可以编辑 LiteLoaderQQNT/src/setting/renderer.js 的第42行下面新建一行，写入nav_item.classList.add("liteloader");
