### ISSUE TITLE
插件商店失效

### ISSUE THREAD

**Issue by GHOST1834** [LiteLoaderQQNT/LiteLoaderQQNT#264]
升上最新版后插件商店失效了，请问如何解决？
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/125651481/600344e5-5c35-447a-9a22-2cf8821ccaca)

**Comment by bling-yshs** [comment]
+1

**Comment by dsyo2008** [comment]
+1

**Comment by xinyihl** [comment]
等插件商店作者更新兼容，要么就退回上一个版本

**Comment by ZeroSunBrand** [comment]
可以拜托问一下字体是怎么换的吗？我试着在工具箱里的自定义字体功能选中了自己下载的字体，但显示的依旧是默认的（泪

**Comment by GHOST1834** [comment]
那就奇怪了我这个选字体是有效的，你改完以后退出qq再进去也还是不变吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZeroSunBrand ***@***.***&gt;
发送时间: 2024年4月8日 15:50
收件人: LiteLoaderQQNT/LiteLoaderQQNT ***@***.***&gt;
抄送: GHOST1834 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [LiteLoaderQQNT/LiteLoaderQQNT] 插件商店失效 (Issue #264)





 
可以拜托问一下字体是怎么换的吗？我试着在工具箱里的自定义字体功能选中了自己下载的字体，但显示的依旧是默认的（泪

**Comment by ZeroSunBrand** [comment]
是的我还在想是不是因为字体的缘故 后面换了别的也还是这样  方便告知一下字体包的名字嘛我换一下再试试

**Comment by GHOST1834** [comment]
我记得只有一个插件有换字体的功能，应该和字体包没什么关系。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZeroSunBrand ***@***.***&gt;
发送时间: 2024年4月8日 16:01
收件人: LiteLoaderQQNT/LiteLoaderQQNT ***@***.***&gt;
抄送: GHOST1834 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [LiteLoaderQQNT/LiteLoaderQQNT] 插件商店失效 (Issue #264)





 
是的我还在想是不是因为字体的缘故 后面换了别的也还是这样  方便告知一下字体包的名字嘛我换一下再试试

**Comment by mo-jinran** [comment]
第三方插件问题请勿发送到框架下，请前往对应插件仓库下提 https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store 等待作者适配

**Comment by mo-jinran** [comment]
如果目前真的等不及想用 eee 做的部分插件
可以编辑 `LiteLoaderQQNT/src/setting/renderer.js` 的第42行下面新建一行，写入`nav_item.classList.add("liteloader");`
