### ISSUE TITLE
切换深色模式会导致无折叠的 `<setting-list>` 组件出现折叠按钮

### ISSUE THREAD

**Issue by maxchang3** [LiteLoaderQQNT/LiteLoaderQQNT#266]
LiteLoader 1.1.1
QQNT 6.9.25-20811
Electron 28.0.0
Chromium 120.0.6099.56
Node.js 18.18.2
macOS 14.4.1 (23E224)

已确定关闭插件加载器亦会复现。

**Comment by mo-jinran** [comment]
具体触发步骤？我无法复现

**Comment by maxchang3** [comment]
我这边是切换深色模式后直接就出现了。

**Comment by maxchang3** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/36927158/1e59b785-1163-4333-be8e-275f9c265fea

**Comment by ltxhhz** [comment]
在页面添加一个 `dialog` 元素，然后调用元素的 `showModal` 方法应该可以复现
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/51697596/20406a11-8a4a-4b02-b5fb-626aa9f1aa31)
