### ISSUE TITLE
我的插件开关呢？

### ISSUE THREAD

**Issue by CooStack** [LiteLoaderQQNT/LiteLoaderQQNT#268]
上一个版本可以选择某些插件是否启用
这个版本没掉啦
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/112278452/2bde4aad-ea03-4be1-9044-3ee80de0a924)

**Comment by xinyihl** [comment]
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/75861358/2b0cc9e1-fb09-4b94-9a03-c5cdb71dec5b)
仔细看这个是不是开关

**Comment by YuSanr** [comment]
> ![image](https://private-user-images.githubusercontent.com/75861358/322203898-2b0cc9e1-fb09-4b94-9a03-c5cdb71dec5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTkwNjMsIm5iZiI6MTcxMzU5ODc2MywicGF0aCI6Ii83NTg2MTM1OC8zMjIyMDM4OTgtMmIwY2M5ZTEtZmIwOS00Yjk0LTlhMDMtYzVjZGI3MWRlYzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA3MzkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4Zjc3ZjdiNDBkM2ZlOTFkNjBiZGZlZGJmZjNjMWUyZjU4MmExOTg1M2VmMzBlYTA3NTc4YjE1MzM0ODc0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.33HVa9ti6zuOTJnZ8ldXUlqGe7dijr4c0eXSBU-an_8) 仔细看这个是不是开关

不是啊 我点烂了都没啥反应

**Comment by Arcticn** [comment]
我这边是由背景插件导致的，关掉或者去掉插件就好了

**Comment by mo-jinran** [comment]
大概率是装了什么插件导致的，建议排查；安装新版LiteLoaderQQNT
