### ISSUE TITLE
[Hope]: 禁用QQNT右下角的广告气泡

### ISSUE THREAD

**Issue by TranscendMa** [LiteLoaderQQNT/LiteLoaderQQNT#275]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望添加对QQNT广告的屏蔽。
情景描述：
今日早些时候电脑右下角本该是弹出通知的地方弹出来一个广告，形似通知气泡，但不会自动关闭。经过排查发现，只要退出QQ进程，广告即消失。由于当时并没有第一时间截图，而之后的数小时使用中也没有更多的广告弹出，故无法提供。如有需要，我会等广告再次出现时截图并定位其进程。

使用环境：
Windows 11 专工 中文版 23H2
LL版本1.1.1   QQNT版本22355

**Comment by WuJunkai2004** [comment]
在设置里面关闭推送后，依然会弹出弹窗

**Comment by CreeperAWA** [comment]
我的QQNT提示QQ游戏需要单独下载，也就是说根本没有安装，但是还是有这个广告

**Comment by fred913** [comment]
@CreeperAWA 一个是QQ游戏，一个是游戏。
你搞错了。

**Comment by CreeperAWA** [comment]
> @CreeperAWA 一个是QQ游戏，一个是游戏。 你搞错了。

别人给的方法就是从QQ游戏关

**Comment by fred913** [comment]
@CreeperAWA 那就是你跟别人都搞错了 你在游戏里就能看到关闭按钮了

**Comment by CreeperAWA** [comment]
今天总算是抓到QQ广告的域名了
这个广告的原理就是弹出一个窗口打开一张图片
但是很可惜，我并没有找到QQ是通过哪次请求获取到这个地址的
下方链接是2024年9月28日的一个广告的图片对应的网址
https://img.gamecenter.qq.com/pc_tips_cover/B_hc197f26630e70200cP0Nc3kPe3sSdM0X5c

**Comment by CreeperAWA** [comment]
补充信息：
窗口标题 `QQ`
窗体类名 `Chrome_WidgetWin_1`
窗口样式 `WS_VISIBLE|WS_CLIPSIBLINGS|WS_GROUP|WS_TABSTOP|WS_MINIMIZEBOX|WS_MAXIMIZEBOX`
拓展样式 `WS_EX_LEFT|WS_EX_LTRREADING|WS_EX_RIGHTSCROLLBAR|WS_EX_CONTROLPARENT|WS_EX_STATICEDGE`

不知这些信息是否有用

**Comment by CreeperAWA** [comment]
> 今天总算是抓到QQ广告的域名了 这个广告的原理就是弹出一个窗口打开一张图片 但是很可惜，我并没有找到QQ是通过哪次请求获取到这个地址的 下方链接是2024年9月28日的一个广告的图片对应的网址 https://img.gamecenter.qq.com/pc_tips_cover/B_hc197f26630e70200cP0Nc3kPe3sSdM0X5c

我今天再看你的评论才看明白 我们俩说的就是一个东西啊，那个“游戏”就是“QQ游戏”，你看广告上咋写的
![2f3a967ed26a7c8fbbf2b60565165bb6](https://github.com/user-attachments/assets/842220aa-d6ed-4261-a109-59c5ac568c38)
