### ISSUE TITLE
[Feat]: 支持scoop进行包管理

### ISSUE THREAD

**Issue by magisk317** [LiteLoaderQQNT/LiteLoaderQQNT#280]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

如题，电脑上不少软件都是通过scoop安装的，路径统一，方便管理，希望大佬能支持

refer：https://github.com/ScoopInstaller/Scoop/wiki/Creating-an-app-manifest

**Comment by mo-jinran** [comment]
https://github.com/okibcn/ScoopMaster/blob/8a84c331176c7cf121cc582ad90374290f35ddce/bucket/LiteLoaderQQNT.json

**Comment by magisk317** [comment]
> https://github.com/okibcn/ScoopMaster/blob/8a84c331176c7cf121cc582ad90374290f35ddce/bucket/LiteLoaderQQNT.json

666，还有这么个库呢，我先试试
