### ISSUE TITLE
[Bug]: 安装LiteLoaderQQNT后设置里的插件布局显示异常，似乎图片被替换为上箭头了

### ISSUE THREAD

**Issue by KimLay233** [LiteLoaderQQNT/LiteLoaderQQNT#288]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-16183 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.1

### 运行环境

Windows

### 重现步骤

不确定是不是，在此之前已经安装过最新版本的QQNT（9.9.9），后卸载安装了9.9.2-16183

### 期望的结果是什么？

正常显示

### 实际的结果是什么？

我尝试安装了一些插件，显示似乎都有问题。
![1](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/52519339/8f0df5f0-ee5e-42b2-bb35-a42e32c00ac6)
![2](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/52519339/096d8d8e-7f78-4c45-87fe-8d7e5acb19fe)
![3](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/52519339/9263de83-d14d-472a-bc7f-155ce1d13a3f)
![4](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/52519339/29bac098-f9db-4b22-857b-dc1daf1fe4cd)

### 日志记录

![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/52519339/ac1a83e1-1343-4cd6-996e-8a4cdbbbe229)

### 补充说明

降版本后出现了接收不到消息的问题，查阅了issue #186 后按步骤把聊天记录文件夹的 nt_qq删除，问题得以解决。

**Comment by xinyihl** [comment]
新版本框架已经不支持旧版本qq了。
只能说正常现象

**Comment by KimLay233** [comment]
> 新版本框架已经不支持旧版本qq了。 只能说正常现象

那请问现在是最低支持什么版本的qqnt了

**Comment by mo-jinran** [comment]
支持 QQNT 桌面端 全架构 最低 20667 版本到官网最新版
