### ISSUE TITLE
[Bug]: LiteLoader设置不显示

### ISSUE THREAD

**Issue by BoXueDuoCai** [LiteLoaderQQNT/LiteLoaderQQNT#289]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

QQ_9.9.9_240507_x64_01

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.1

### 运行环境

Windows

### 重现步骤

安装最新版QQNT，LiteLoaderQQNT1.1.1，装以下插件
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/106514148/342ad98d-fc89-4435-94fe-6289f2861ae8)
运行patch，打开qqnt
[plugins.zip](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/files/15363212/plugins.zip)

### 期望的结果是什么？

QQNT设置处，左边红框处有LiteLoaderQQNT及插件的设置按钮
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/106514148/02485f63-117c-4a4c-ae95-40b7bbf9dfbb)

### 实际的结果是什么？

无任何设置按钮
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/106514148/1e50da9b-15b5-4b6f-85f1-62b021af7e58)
但是部分功能可用
DeepL
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/106514148/189b12cd-1af2-4def-83fa-370cfe97b6ef)
某插件(不清楚)的时间显示
![32ddb317259c52830abcbd526fa33b90](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/106514148/fa7ab5f7-f0f7-430e-b1e2-80f2110339d6)

### 日志记录

C:\Program Files\Tencent\QQNT>.\QQ.exe

C:\Program Files\Tencent\QQNT>not mini app.
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
3c8a04e672433cf0c091a50bd0429a9e879eca6114b94b5003e6a1add5dbd8a7
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
9a9c27fab025a3860d723d756c0a95072f88842be42b039b890ffc099223a00d
ee20a334f0f2a24d45547941beb0e084b01578a026ad970915d6bf6d42475a3d
4b350966dc065d1630191443a0dea9be609650684c870c8fe11d3ecd7f55a12d
0
[preload] process type:
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.9-23424
[preload] hotupdate current version: 9.9.9-23424
[preload] install app version: 9.9.9-23424

[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424\major.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424\wrapper.node
[preload] register done. launcher.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: 鎻掍欢鍒楄〃鏌ョ湅
[LiteLoader] Found plugin: DeepL
[LiteLoader] Found plugin: 鎵撳紑閾炬帴璺宠繃鎷︽埅椤?[LiteLoader] Found plugin: Fake Message Missing dependencies: euphony
[LiteLoader] Found plugin: Link Preview
[LiteLoader] Found plugin: Markdown-it
[LiteLoader] Found plugin: QQ绾韩妯″紡
[LiteLoader] Found plugin: LLAPI
[LiteLoader] Found plugin: QQ澧炲己
[LiteLoader] Found plugin: 浜岀淮鐮佽В鏋?[LiteLoader] Found plugin: 鎻掍欢妫€娴嬫洿鏂癆PI
[LiteLoader] Found plugin: 杞婚噺宸ュ叿绠?[LiteLoader] Found plugin: 鏈湴鏌ョ湅鍥剧墖鍜岃棰?[LiteLoader] Found plugin: PluginInstaller
[LiteLoader] Found plugin: 闃叉挙鍥?[LiteLoader] Found 15 plugins, start loading plugins.
[preload] register done. major.node
[CheckUpdate] checkUpdate starts
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at WebContents.emit (node:events:517:28)
[preload] register done. wrapper.node
[LLAPI] Page finished loading
[LLAPI] Page finished loading
浣跨敤榛樿閰嶇疆
鏇存柊閰嶇疆鏂囦欢 {
  debug: {
    console: false,
    mainConsole: false,
    autoCompileScss: false,
    showWeb: false,
    showChannedCommunication: false
  },
  compatibleLLAPI: false,
  keywordReminder: { enabled: false, keyList: [] },
  wordSearch: {
    enabled: false,
    searchUrl: 'https://www.bing.com/search?q=%search%'
  },
  imageSearch: {
    enabled: false,
    searchUrl: 'https://saucenao.com/search.php?url=%search%'
  },
  localEmoticons: {
    enabled: false,
    quickEmoticons: false,
    quickEmoticonsAutoInputOnlyOne: false,
    quickEmoticonsActiveKey: '/',
    sendBigImage: false,
    majorization: false,
    commonlyEmoticons: true,
    copyFileTolocalEmoticons: false,
    toLeftSlot: false,
    hoverShowCommonlyEmoticons: false,
    commonlyNum: 20,
    rowsSize: 5,
    localPath: ''
  },
  sidebar: {
    top: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    bottom: [ [Object], [Object], [Object], [Object] ]
  },
  imageViewer: { quickClose: false, touchMove: false },
  message: {
    previreUrl: { enabled: false, dontLoadPic: false },
    goBackMainList: false,
    HighlightReplies: false,
    disabledSticker: false,
    disabledHotGIF: false,
    disabledBadge: false,
    disabledSlideMultipleSelection: false,
    convertMiniPrgmArk: true,
    showMsgTime: true,
    showMsgTimeFullDate: false,
    showMsgTimeToSenderName: false,
    replaceBtn: true,
    doubleClickReplace: false,
    removeReplyAt: false,
    mergeMessage: false,
    mergeMessageKeepTime: false,
    selfMsgToLeft: false,
    onlyAvatar: false,
    removeBubbleLimit: false,
    removeVipName: false,
    imageAutoWidth: false,
    currentLocation: false,
    overrideFont: { family: '', style: '', fullName: '', postscriptName: '' },
    preventNSFW: { enabled: false, includesAnimationEmoticons: false, list: [] },
    avatarSticky: { enabled: false, toBottom: false }
  },
  messageToImage: { enabled: true, highResolution: false, path: '' },
  preventMessageRecall: {
    enabled: true,
    localStorage: true,
    customColor: true,
    preventSelfMsg: true,
    blockAllRetractions: false,
    textColor: { light: '#ff6666', dark: '#c70000' }
  },
  tail: { enabled: false, tips: false, list: [ [Object] ] },
  textAreaFuncList: [
    { name: '琛ㄦ儏', id: 'id-func-bar-expression', disabled: false },
    { name: '鎴浘', id: 'id-func-bar-screenshot', disabled: false },
    { name: '鏂囦欢', id: 'id-func-bar-folder', disabled: false },
    { name: '鍥剧墖', id: 'id-func-bar-image', disabled: false },
    { name: '绾㈠寘', id: 'id-func-bar-lucky_money', disabled: false },
    { name: '璇煶娑堟伅', id: 'id-func-bar-microphone_on', disabled: false },
    { name: '鑱婂ぉ璁板綍', id: 'id-func-bar-MessageRecord', disabled: false },
    { name: '鏈哄櫒浜烘寚浠?, id: 'id-func-bar-channel_robot', disabled: false },
    { name: '绐楀彛鎶栧姩', id: 'id-func-bar-shake', disabled: false },
    { name: '缈昏瘧', id: 'deepl-bar-icon', disabled: false }
  ],
  chatAreaFuncList: [
    { name: '璇煶閫氳瘽', id: 'id-func-bar-telephone', disabled: false },
    { name: '瑙嗛閫氳瘽', id: 'id-func-bar-video_on', disabled: false },
    { name: '灞忓箷鍏变韩', id: 'id-func-bar-share_screen', disabled: false },
    {
      name: '缇ゅ簲鐢?,
      id: 'id-func-bar-group_application',
      disabled: false
    },
    { name: '閭€璇峰姞缇?, id: 'id-func-bar-group_building', disabled: false },
    { name: '宸ュ叿鏍忛」鐩?, id: 'id-func-bar-more', disabled: false },
    { name: '鍙戣捣缇よ亰', id: 'id-func-bar-group_building', disabled: false },
    { name: '杩滅▼鍗忓姪', id: 'id-func-bar-remote_control', disabled: false },
    { name: '灞忚斀浼氳瘽', id: 'id-func-bar-shield', disabled: false },
    { name: '娣诲姞濂藉弸', id: 'id-func-bar-add_friend', disabled: false },
    { name: null, id: 'id-func-bar-more', disabled: false }
  ],
  preventEscape: false,
  advanceHookVue: false,
  setWindowIcon: false,
  autoRelanch: false,
  background: {
    overlaySiderBar: false,
    removeMask: false,
    redrawCard: false,
    backgroundVisible: true,
    blurFilter: true,
    opacity: 0.5,
    enabled: false,
    url: ''
  },
  global: {
    UA: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    rkey: '&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64',
    PIC_BASE_URL: 'https://gchat.qpic.cn'
  },
  disableQtag: { level: false, title: false, all: false }
}
[app]module file name: [app]moImage-Local-View: NTQQ Image-Local-View for window: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message
dule file name: C:\Program Files\Tencent\QQNT\QQ.exe
C:\Program Files\Tencent\QQNT\QQ.exe
3c8a04e672433cf0c091a50bd0429a9e879eca6114b94b5003e6a1add5dbd8a73c8a04e672433cf0c091a50bd0429a9e879eca6114b94b5003e6a1add5dbd8a7

c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
9a9c27fab025a3860d723d756c0a95072f88842be42b039b890ffc099223a00d
9a9c27fab025a3860d723d756c0a95072f88842be42b039b890ffc099223a00d
error code v2:-8
error code v2:-8
Anti-Recall: Detected recall, intercepted and recovered from dbMsg
Anti-Recall: Detected recall, intercepted and recovered from dbMsg
Anti-Recall: Detected recall, intercepted and recovered from dbMsg
Anti-Recall: Detected recall, intercepted and recovered from dbMsg
[LLAPI] Page finished loading
20:14:19.257 > [hot update] hotUpdateApi checkHasMultipleQQ false
20:14:19.262 > [hot update] hotUpdateApi start clearOldVersions
20:14:19.263 > [hot update] hotUpdateApi curVersionZipPath is: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424.zip false
20:14:19.375 > [hot update] hotUpdateApi checkHasMultipleQQ false
20:14:19.379 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.9-22961
20:14:19.383 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false

### 补充说明（可选）

日志乱码
转UTF-8后如下
C:\Program Files\Tencent\QQNT>.\QQ.exe

C:\Program Files\Tencent\QQNT>not mini app.
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
3c8a04e672433cf0c091a50bd0429a9e879eca6114b94b5003e6a1add5dbd8a7
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
9a9c27fab025a3860d723d756c0a95072f88842be42b039b890ffc099223a00d
ee20a334f0f2a24d45547941beb0e084b01578a026ad970915d6bf6d42475a3d
4b350966dc065d1630191443a0dea9be609650684c870c8fe11d3ecd7f55a12d
0
[preload] process type:
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.9-23424
[preload] hotupdate current version: 9.9.9-23424
[preload] install app version: 9.9.9-23424

[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424\major.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424\wrapper.node
[preload] register done. launcher.node
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: 插件列表查看
[LiteLoader] Found plugin: DeepL
[LiteLoader] Found plugin: 打开链接跳过拦截�?[LiteLoader] Found plugin: Fake Message Missing dependencies: euphony
[LiteLoader] Found plugin: Link Preview
[LiteLoader] Found plugin: Markdown-it
[LiteLoader] Found plugin: QQ纯享模式
[LiteLoader] Found plugin: LLAPI
[LiteLoader] Found plugin: QQ增强
[LiteLoader] Found plugin: 二维码解�?[LiteLoader] Found plugin: 插件检测更新API
[LiteLoader] Found plugin: 轻量工具�?[LiteLoader] Found plugin: 本地查看图片和视�?[LiteLoader] Found plugin: PluginInstaller
[LiteLoader] Found plugin: 防撤�?[LiteLoader] Found 15 plugins, start loading plugins.
[preload] register done. major.node
[CheckUpdate] checkUpdate starts
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at WebContents.emit (node:events:517:28)
[preload] register done. wrapper.node
[LLAPI] Page finished loading
[LLAPI] Page finished loading
使用默认配置
更新配置文件 {
  debug: {
    console: false,
    mainConsole: false,
    autoCompileScss: false,
    showWeb: false,
    showChannedCommunication: false
  },
  compatibleLLAPI: false,
  keywordReminder: { enabled: false, keyList: [] },
  wordSearch: {
    enabled: false,
    searchUrl: 'https://www.bing.com/search?q=%search%'
  },
  imageSearch: {
    enabled: false,
    searchUrl: 'https://saucenao.com/search.php?url=%search%'
  },
  localEmoticons: {
    enabled: false,
    quickEmoticons: false,
    quickEmoticonsAutoInputOnlyOne: false,
    quickEmoticonsActiveKey: '/',
    sendBigImage: false,
    majorization: false,
    commonlyEmoticons: true,
    copyFileTolocalEmoticons: false,
    toLeftSlot: false,
    hoverShowCommonlyEmoticons: false,
    commonlyNum: 20,
    rowsSize: 5,
    localPath: ''
  },
  sidebar: {
    top: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    bottom: [ [Object], [Object], [Object], [Object] ]
  },
  imageViewer: { quickClose: false, touchMove: false },
  message: {
    previreUrl: { enabled: false, dontLoadPic: false },
    goBackMainList: false,
    HighlightReplies: false,
    disabledSticker: false,
    disabledHotGIF: false,
    disabledBadge: false,
    disabledSlideMultipleSelection: false,
    convertMiniPrgmArk: true,
    showMsgTime: true,
    showMsgTimeFullDate: false,
    showMsgTimeToSenderName: false,
    replaceBtn: true,
    doubleClickReplace: false,
    removeReplyAt: false,
    mergeMessage: false,
    mergeMessageKeepTime: false,
    selfMsgToLeft: false,
    onlyAvatar: false,
    removeBubbleLimit: false,
    removeVipName: false,
    imageAutoWidth: false,
    currentLocation: false,
    overrideFont: { family: '', style: '', fullName: '', postscriptName: '' },
    preventNSFW: { enabled: false, includesAnimationEmoticons: false, list: [] },
    avatarSticky: { enabled: false, toBottom: false }
  },
  messageToImage: { enabled: true, highResolution: false, path: '' },
  preventMessageRecall: {
    enabled: true,
    localStorage: true,
    customColor: true,
    preventSelfMsg: true,
    blockAllRetractions: false,
    textColor: { light: '#ff6666', dark: '#c70000' }
  },
  tail: { enabled: false, tips: false, list: [ [Object] ] },
  textAreaFuncList: [
    { name: '表情', id: 'id-func-bar-expression', disabled: false },
    { name: '截图', id: 'id-func-bar-screenshot', disabled: false },
    { name: '文件', id: 'id-func-bar-folder', disabled: false },
    { name: '图片', id: 'id-func-bar-image', disabled: false },
    { name: '红包', id: 'id-func-bar-lucky_money', disabled: false },
    { name: '语音消息', id: 'id-func-bar-microphone_on', disabled: false },
    { name: '聊天记录', id: 'id-func-bar-MessageRecord', disabled: false },
    { name: '机器人指�?, id: 'id-func-bar-channel_robot', disabled: false },
    { name: '窗口抖动', id: 'id-func-bar-shake', disabled: false },
    { name: '翻译', id: 'deepl-bar-icon', disabled: false }
  ],
  chatAreaFuncList: [
    { name: '语音通话', id: 'id-func-bar-telephone', disabled: false },
    { name: '视频通话', id: 'id-func-bar-video_on', disabled: false },
    { name: '屏幕共享', id: 'id-func-bar-share_screen', disabled: false },
    {
      name: '群应�?,
      id: 'id-func-bar-group_application',
      disabled: false
    },
    { name: '邀请加�?, id: 'id-func-bar-group_building', disabled: false },
    { name: '工具栏项�?, id: 'id-func-bar-more', disabled: false },
    { name: '发起群聊', id: 'id-func-bar-group_building', disabled: false },
    { name: '远程协助', id: 'id-func-bar-remote_control', disabled: false },
    { name: '屏蔽会话', id: 'id-func-bar-shield', disabled: false },
    { name: '添加好友', id: 'id-func-bar-add_friend', disabled: false },
    { name: null, id: 'id-func-bar-more', disabled: false }
  ],
  preventEscape: false,
  advanceHookVue: false,
  setWindowIcon: false,
  autoRelanch: false,
  background: {
    overlaySiderBar: false,
    removeMask: false,
    redrawCard: false,
    backgroundVisible: true,
    blurFilter: true,
    opacity: 0.5,
    enabled: false,
    url: ''
  },
  global: {
    UA: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    rkey: '&rkey=CAQSKAB6JWENi5LMk0kc62l8Pm3Jn1dsLZHyRLAnNmHGoZ3y_gDZPqZt-64',
    PIC_BASE_URL: 'https://gchat.qpic.cn'
  },
  disableQtag: { level: false, title: false, all: false }
}
[app]module file name: [app]moImage-Local-View: NTQQ Image-Local-View for window: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message
Anti-Recall: NTQQ Anti-Recall loaded for window: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message
dule file name: C:\Program Files\Tencent\QQNT\QQ.exe
C:\Program Files\Tencent\QQNT\QQ.exe
3c8a04e672433cf0c091a50bd0429a9e879eca6114b94b5003e6a1add5dbd8a73c8a04e672433cf0c091a50bd0429a9e879eca6114b94b5003e6a1add5dbd8a7

c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
c48457ac24c9ad33bd2e0250f734116535df7e8caeb043a6d3164fd6ea65046c
9a9c27fab025a3860d723d756c0a95072f88842be42b039b890ffc099223a00d
9a9c27fab025a3860d723d756c0a95072f88842be42b039b890ffc099223a00d
error code v2:-8
error code v2:-8
Anti-Recall: Detected recall, intercepted and recovered from dbMsg
Anti-Recall: Detected recall, intercepted and recovered from dbMsg
Anti-Recall: Detected recall, intercepted and recovered from dbMsg
Anti-Recall: Detected recall, intercepted and recovered from dbMsg
[LLAPI] Page finished loading
20:14:19.257 > [hot update] hotUpdateApi checkHasMultipleQQ false
20:14:19.262 > [hot update] hotUpdateApi start clearOldVersions
20:14:19.263 > [hot update] hotUpdateApi curVersionZipPath is: C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.9-23424.zip false
20:14:19.375 > [hot update] hotUpdateApi checkHasMultipleQQ false
20:14:19.379 > [hot update] hotUpdateApi checkIsOnErrorVersion 9.9.9-22961
20:14:19.383 > [hot update] hotUpdateApi checkIsOnErrorVersion res is false

**Comment by xinyihl** [comment]
某个插件导致的问题，自行查找不支持的插件。

**Comment by Banise** [comment]
同款问题

**Comment by BoXueDuoCai** [comment]
问题找到了，LiteLoaderQQNT-Fake-Message插件的问题

**Comment by Banise** [comment]
帮助排查
同款问题   
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/91298198/200fcb22-8cd6-4a21-a426-ea27d9de3647)
经过排查后发现插件text to speech存在该问题   将该插件删除解决  liteloader插件列表恢复正常
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/91298198/b153ddd5-7fc5-40b6-a57a-b23fbcfc639d)
