### ISSUE TITLE
[Hope]: 更多菜单隐藏选项

### ISSUE THREAD

**Issue by Shapaper233** [LiteLoaderQQNT/LiteLoaderQQNT#291]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

![f1cc3b46c9adf6feca7ab4a834de3947](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/157946924/c7b1829f-d581-4b24-a284-7c269f4e7f6d)
如图所示，该按钮经常在配置liteloader的时候误触，触碰后需要用手机解锁很不方便，望有大佬制作隐藏插件

**Comment by xinyihl** [comment]
使用 [transitio](https://github.com/PRO-2684/transitio) 加载这个 css 片段
``` css
.more-menu :nth-last-child(4) {
  display: none !important;
}
```
:nth-last-child(4) 中的4代表倒数第四个，根据你自己的修改

**Comment by Shapaper233** [comment]
谢谢啦
