### ISSUE TITLE
[Bug]: 最新版qq无法使用

### ISSUE THREAD

**Issue by bobandbrony** [LiteLoaderQQNT/LiteLoaderQQNT#294]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

v 9.9.10

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.1

### 运行环境

Windows

### 重现步骤

使用最新版qq安装插件，使用DLLHijackMethod来绕过完整性检查

### 期望的结果是什么？

qq正常加载使用插件

### 实际的结果是什么？

打开qq提示“文件已损坏，请重新安装qq”，无法使用

### 日志记录

PS D:\QQNT> .\QQ.exe
PS D:\QQNT> not mini app.
[preload] process type:
[app]module file name: D:\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.10-23873
[preload] hotupdate current version: 9.9.10-23873
[preload] install app version: 9.9.10-23873

[preload] succeeded. D:\QQNT\resources\app\versions\9.9.10-23873\major.node
[preload] succeeded. D:\QQNT\resources\app\versions\9.9.10-23873\wrapper.node
[preload] succeeded. D:\QQNT\resources\app\app_launcher\launcher.node
not mini app.
[app]module file name: D:\QQNT\QQ.exe
8f933e668d2eb8bb0d352aa7ace9b9ceb8a79eaa37687078cc86a1df61564afb
12e0323daef1a122be5efadc01e462079a5ec1501c4b33ebb787769a535d38ce
error code v2:-8

**Comment by 250king** [comment]
我也遇到了
```
[preload] process type:
[app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.10-23873
[preload] hotupdate current version: 9.9.10-23873
[preload] install app version: 9.9.10-23873

[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.10-23873\major.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.10-23873\wrapper.node
[LiteLoader] Use LITELOADERQQNT_PROFILE environment variables: C:\Users\250king\AppData\Local\LiteLoaderQQNT
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: 使用自定义浏览器打开链接并跳过拦截页
[LiteLoader] Found plugin: Fake Message Missing dependencies: euphony
[LiteLoader] Found plugin: 插件商店
[LiteLoader] Found plugin: MSpring Theme
[LiteLoader] Found plugin: pURLfy
[LiteLoader] Found plugin: 二维码解析
[LiteLoader] Found 6 plugins, start loading plugins.
[preload] register done. launcher.node
[preload] register done. major.node
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at WebContents.emit (node:events:517:28)
[preload] register done. wrapper.node
```

**Comment by bobandbrony** [comment]
> 我也遇到了
> 
> ```
> [preload] process type:
> [app]module file name: C:\Program Files\Tencent\QQNT\QQ.exe
> [preload] hotupdate base version: 9.9.10-23873
> [preload] hotupdate current version: 9.9.10-23873
> [preload] install app version: 9.9.10-23873
> 
> [preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.10-23873\major.node
> [preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\app_launcher\launcher.node
> [preload] succeeded. C:\Program Files\Tencent\QQNT\resources\app\versions\9.9.10-23873\wrapper.node
> [LiteLoader] Use LITELOADERQQNT_PROFILE environment variables: C:\Users\250king\AppData\Local\LiteLoaderQQNT
> [LiteLoader] Start finding all plugins.
> [LiteLoader] Found plugin: 使用自定义浏览器打开链接并跳过拦截页
> [LiteLoader] Found plugin: Fake Message Missing dependencies: euphony
> [LiteLoader] Found plugin: 插件商店
> [LiteLoader] Found plugin: MSpring Theme
> [LiteLoader] Found plugin: pURLfy
> [LiteLoader] Found plugin: 二维码解析
> [LiteLoader] Found 6 plugins, start loading plugins.
> [preload] register done. launcher.node
> [preload] register done. major.node
> Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
>     at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
>     at WebContents.emit (node:events:517:28)
> [preload] register done. wrapper.node
> ```

我用liteloder的安装器成功了，建议你也去试试

**Comment by 250king** [comment]
这个？
https://github.com/Mzdyl/LiteLoaderQQNT_Install

**Comment by bobandbrony** [comment]
> 这个？ https://github.com/Mzdyl/LiteLoaderQQNT_Install

嗯嗯

**Comment by 250king** [comment]
插件商店是不是不能用了？

**Comment by bobandbrony** [comment]
> 插件商店是不是不能用了？

啊？怎么不能用了
