### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by manggo94** [LiteLoaderQQNT/LiteLoaderQQNT#295]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.10-24108

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.1

### 运行环境

Windows

### 重现步骤

安装玩最新版本后LL在设置中无任何显示

### 期望的结果是什么？

正常使用

### 实际的结果是什么？

无显示

### 补充说明（可选）

![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/64975311/af0ff6e2-97f6-4ff4-a136-54d2965be639)

**Comment by manggo94** [comment]
我撤回消息时，手机端显示撤回，PC端未撤回，所以正常来说插件应该生效了，但就是看不到

**Comment by 250king** [comment]
新版QQ应该是弄拦截了
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/294

**Comment by adproqwq** [comment]
应该是某个插件炸了，检查下有没有安装TTS插件，或者自己逐个排查

**Comment by YIEMM** [comment]
所以怎么解决.-.

**Comment by adproqwq** [comment]
> 所以怎么解决.-.

排查插件，删除问题插件

**Comment by Cranyozen** [comment]
检测插件是不是炸了。。。例如 LLAPI
这个 commit [a55932d3a6991946324c7ced30b1ce84dfc625d9](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/a55932d3a6991946324c7ced30b1ce84dfc625d9) 应该解决了这个问题，但是没有合并到 release

**Comment by adproqwq** [comment]
> 但是没有合并到 release

没发版你急什么？真这么急你就用ci版

**Comment by Cranyozen** [comment]
> > 但是没有合并到 release
> 
> 没发版你急什么？真这么急你就用ci版

我只是表示修了，但是你下 release 看不到效果而已，我哪急了？
打扰致歉 orz

**Comment by adproqwq** [comment]
> 我只是表示修了，但是你下 release 看不到效果而已，我哪急了？

但是release是发行版，不会改一次代码就发一次。你说的这话在我看来就是你很急，如果是我理解的方式你不认同，我很抱歉。

**Comment by mo-jinran** [comment]
更新1.2.0
