### ISSUE TITLE
[Bug]: LiteLoader的数据目录为软链接时，LiteLoader.path 为空

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [LiteLoaderQQNT/LiteLoaderQQNT#299]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.10

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.1

### 运行环境

Windows

### 重现步骤

如题

以背景插件为例（实际上任意插件，只要引用了 `LiteLoader.path` 字段都可以复现）

源代码位置：https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/blob/master/main.js#L22

报错：（第22行24列即为 `LiteLoader.path` 的引用）
![image](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/25266280/a746e19d-dba3-4734-a179-ce8e004ef517)

补充：

环境变量：

LITELOADERQQNT_PROFILE = E:\Cache\Tencent\QQ\QQNTLiteLoader

`E:\Cache\Tencent` 为指向 `D:\Cache\Tencent` 的软链接

若将 LITELOADERQQNT_PROFILE 直接指向 `E:\Cache\Tencent\QQ\QQNTLiteLoader` 则没有问题

### 期望的结果是什么？

如上

### 实际的结果是什么？

如上

**Comment by mo-jinran** [comment]
修了
