### ISSUE TITLE
 关键词屏蔽

### ISSUE THREAD

**Issue by Ren-Boo** [LiteLoaderQQNT/LiteLoaderQQNT#300]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

设置一些关键词，如果其他人发送的消息含有指定的关键词，则屏蔽该消息。

**Comment by cxm1024** [comment]
同求

**Comment by mo-jinran** [comment]
https://github.com/elegantloneliness/qqMessageBlocker/tree/main
