### ISSUE TITLE
[Hope]: 语音自动转文字

### ISSUE THREAD

**Issue by toaltf4** [LiteLoaderQQNT/LiteLoaderQQNT#302]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

语音自动转文字
---
在以前的版本，qq是有方便的快捷的方法转文字。但是在qqnt没有会员自动转文字，语音消息旁也没有转文字按钮。已知有一个插件[QQ增强](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote)有此功能，但已删库。感激不尽。

**Comment by huajikl** [comment]
[QQ增强](https://github.com/shiquda/LiteLoaderQQNT-Plugin-QQPromote)

**Comment by Shapaper233** [comment]
@toaltf4 @huajikl 那个归档了，可能对新版QQ稳定性不佳，可以试试我写的一个脚本：https://github.com/Shapaper233/Shapaper-Scriptio-user-scripts#automatic-voice-to-text-conversion

**Comment by Shapaper233** [comment]
QQpromote前置LLAPI在新版QQ会导致启动插件列表丢失，我这个插件已经提取LLAPI的一些用法，可以完成任务
