### ISSUE TITLE
[Bug]: MacOS 运行报错

### ISSUE THREAD

**Issue by Syunraii** [LiteLoaderQQNT/LiteLoaderQQNT#303]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

AppStore 6.9.33

### LiteLoaderQQNT 版本 （或 Commit Id）

latest 6/7/2024 (Commit Id:6e8fe89)

### 运行环境

MacOS

### 重现步骤

1. 脚本自动安装 ([LiteLoaderQQNT_Install](https://github.com/Mzdyl/LiteLoaderQQNT_Install) ->  MacOS Stable通道), 打开QQ报错

2. 下载脚本安装, ./运行安装脚本并根据步骤执行完毕; 结果: 打开QQ报错 

3. 手动安装, clone 到/Users/个人/Applications/app_plugins/QQNT/LitetloaderQQNT, 最后在app_launcher/index.js中首行加入 require('/Users/个人/Applications/app_plugins/QQNT/LiteLoaderQQNT'); 结果: 打开QQ报错
 
4. 手动安装, clone 到QQ.app沙盒 /Users/个人/Library/Containers/com.tencent.qq/Data/Documents, 最后在app_launcher/index.js中首行加入 require('/Users/个人/Library/Containers/com.tencent.qq/Data/Documents/LiteLoaderQQNT'); 结果: 打开QQ报错

### 期望的结果是什么？

成功安装并运行QQ

### 实际的结果是什么？

<img width="509" alt="image" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/79300447/3efde1b8-eca9-4792-89aa-404d27cdae7c">

### 日志记录

(日志为ocr提取, 已略微修正 )
Uncaught Exception：
Error: Cannot find module '/Applications/QQ.app/Contents/Resources/app/versions/config.json' 

Require stack：
- /Users/syunraii/Library/Containers/com.tencent.qq/Data/Documents/ LiteLoader/src/liteloader_api/main.js
- /Users/syunrail/Library/Containers/com.tencent.qq/Data/Documents/ LiteLoader/src/init.js 
- /Applications/QQ.app/Contents/Resources/app/app_launcher/index.js 
- 
at Module._resolveFilename （node:internal/modules/cjs/loader:1084:15）
at n. _resolveFilename （node:electron/js2c/browser_init:2:114728） 
at Module._load （node:internal/modules/cjs/loader:929:27） 
at u._load （node:electron/js2c/asar_bundle:2:14589） 
at Module.require （node:internal/modules/cjs/loader:1150:19） 
at require （node:internal/modules/cjs/helpers:119:18） 
at Object.<anonymous> （/Users/syunrai/Library/Containers/com.tencent.qq/ Data/Documents/LiteLoader/src/liteloader_api/main.js:12:22） 
at Module. _compile （node:internal/modules/cs/loader:1271:14） 
at Module._extensions..js （node:internal/modules/cjs/loader:1326:10） 
at Module.load （node:internal/modules/cjs/loader:1126:32）

### 补充说明（可选）

系统: MacOS 14.4.1 Apple Silicon

补充: main.js所需目录app/versions已经移除了

<img width="611" alt="image" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/79300447/296d083a-0277-41f4-af38-49810d5e29ec">

**Comment by ilharp** [comment]
24402 开始应该正式启用快更逻辑了

- 有快更的系统：更新时只下载资源 zip 解压到 versions 下对应目录后修改 config，重启后 launcher 使用新版本启动
- 无快更的系统：资源和本体均在 app 文件夹内

快更情况下 config 里 curVersion 是当前版本，无快更情况下 package.json 里就是当前版本。读版本的话应该做一个回退

**Comment by Syunraii** [comment]
看了commit之后应该是上次提交的, 注释掉src/main.js中的qqnt_version后可以正常使用, 应该是还没有用到

<img width="738" alt="image" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/79300447/ca6c4dbc-6209-4746-976d-ae88f691a8a7">

<img width="534" alt="image" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/79300447/5e0b7286-eb2f-4e6d-a09b-db94c04dbbed">
