### ISSUE TITLE
[Hope]: 关于解除表情商城的表情无法复制和保存的限制

### ISSUE THREAD

**Issue by Eustia-gif** [LiteLoaderQQNT/LiteLoaderQQNT#305]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

在最近的一次更新之后，qqnt无法对表情商城的表情复制和保存，希望能开发出插件解除限制

**Comment by Starrain08** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> * [x]  我确定这是一个从未被提出和实现过的功能。
> * [x]  我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
> * [x]  我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
> * [x]  我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
> 
> ### 需要添加的功能内容
> 在最近的一次更新之后，qqnt无法对表情商城的表情复制和保存，希望能开发出插件解除限制

可以使用轻量工具箱的本地表情功能来保存，测试是有效的
