### ISSUE TITLE
[Hope]: 清理qq缓存/硬盘占用

### ISSUE THREAD

**Issue by LINKlang** [LiteLoaderQQNT/LiteLoaderQQNT#306]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

现在的qq存储管理太弱了，其他数据不知道是啥也删不掉，我感觉有很多不用的，聊天记录也不能只删多久之前的，希望有大佬写插件解决

**Comment by mo-jinran** [comment]
https://github.com/MisaLiu/LiteLoaderQQNT-QQCleaner
