### ISSUE TITLE
[Feat]: QQNT大约1个月会出现登录失效的弹窗

### ISSUE THREAD

**Issue by bianyuan456** [LiteLoaderQQNT/LiteLoaderQQNT#310]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

QQNT大约1个月会出现登录失效的弹窗，我在想能不能再框架侧或者插件侧，在大概登录了29天时实现退出并重新登录QQNT，来避免出现QQNT登录失效，导致插件没有效果的情况？
<img src="https://pic.imgdb.cn/item/6676fcead9c307b7e94e893e.png" alt="QQ图片20240623003247.png">
我的意思是，LiteLoaderQQNT可不可以新增功能，新增登录指定QQ号码的API和关闭指定号码QQNT的API，来完成这个功能？

**Comment by mo-jinran** [comment]
框架提供了获取账号uid功能，剩下的需要插件实现了

**Comment by bianyuan456** [comment]
> 框架提供了获取账号uid功能，剩下的需要插件实现了

感谢解答，但是获取账号uid跟登录QQNT和关闭QQNT 这俩API没关系吧！？

**Comment by mo-jinran** [comment]
这俩功能较简单，在插件都可以自己实现

**Comment by bianyuan456** [comment]
> ，在插件都可以自己实现，插件只需要用uid去调用对应ipc就行了

谢谢解答。。我对于ts还真是没入门，虽然我不懂但是我感谢你给我指了条路，我试试看看能不能让我用的插件去支持这个api吧。。
