### ISSUE TITLE
[Feat]: 希望推出安卓版的插件

### ISSUE THREAD

**Issue by haoxiang1024** [LiteLoaderQQNT/LiteLoaderQQNT#312]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

在安卓端实现相同的功能

**Comment by model-err** [comment]
请去看qauxiliary等安卓版模块，手机端的适配是永远不会去做的

**Comment by haoxiang1024** [comment]
好的好的・

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Gray David ***@***.***>
发送时间: Tuesday, July 2, 2024 12:38:16 PM
收件人: LiteLoaderQQNT/LiteLoaderQQNT ***@***.***>
抄送: haoxiang ***@***.***>; Author ***@***.***>
主题: Re: [LiteLoaderQQNT/LiteLoaderQQNT] [Feat]: 希望推出安卓版的插件 (Issue #312)


请去看qauxiliary等安卓版模块，手机端的适配是永远不会去做的

―
