### ISSUE TITLE
[Bug]: 新版本QQ9.9.12-25300 安装本程序后报错

### ISSUE THREAD

**Issue by QQ804218** [LiteLoaderQQNT/LiteLoaderQQNT#313]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-25300

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

在更新时提示"无法定位程序输入点 MiniDumpWriteDump 于动态链接库".但卸载本程序后一切正常

### 期望的结果是什么？

正常使用QQ

### 实际的结果是什么？

在修复此问题前 只能卸载后使用原版QQ了,

### 日志记录

无

**Comment by ChenXiaoming233** [comment]
相同的问题，同样是最新版qq，同样修改后无法启动qq

**Comment by mo-jinran** [comment]
还需要更新LiteLoaderQQNT相关

**Comment by devil233-ui** [comment]
被9.12毒害的过来抱团了……折腾了一晚上
