### ISSUE TITLE
[Hope]: 默认QQNT占用CPU过高，希望推出插件禁止不合理的占用

### ISSUE THREAD

**Issue by Natural12349978** [LiteLoaderQQNT/LiteLoaderQQNT#315]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

我非常的疑惑关于QQNT在后台运行时不断吃我CPU这件事。我只是把QQNT关闭掉，CPU温度从73度直接能下降到60度。虽然我觉得这个问题显然理应让腾讯来做优化，可是大概率它们不会管。我在想第三方插件有没有机会优化，把一些无用的QQ进程对于CPU的占用禁止掉？

**Comment by m1a2sep** [comment]
这个问题不是已经解决了？开关一下边栏的那个#号发现频道就可以了，是那个么？轻量工具箱那个插件里有这个功能。

**Comment by mudse** [comment]
你看看你是不是装了个LLAPI的依赖，我把这个删了之后CPU占用从20%降到1.5%了

**Comment by Natural12349978** [comment]
> 这个问题不是已经解决了？开关一下边栏的那个#号发现频道就可以了，是那个么？轻量工具箱那个插件里有这个功能。

只能说有一定程度的效果
