### ISSUE TITLE
[Bug]: 加载LiteLoaderQQNT后QQ的表情无法加载

### ISSUE THREAD

**Issue by HuanMeng-official** [LiteLoaderQQNT/LiteLoaderQQNT#319]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-25493

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

安装LiteLoaderQQNT后打开一个发有表情的群，表情会一直加载
<img width="151" alt="Snipaste_2024-07-07_16-12-46" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/110048961/93075887-ae81-4992-aec9-e0e0134b81e3">

### 期望的结果是什么？

表情正常加载

### 实际的结果是什么？

表情无法加载

### 日志记录

无日志
<img width="867" alt="Snipaste_2024-07-07_16-17-12" src="https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/110048961/d526c941-288f-4ae6-9455-b41da86f2465">

**Comment by long45343** [comment]
同时按下/也无法快捷发送表情

**Comment by mo-jinran** [comment]
已定位到问题所在，正在想办法解决
