### ISSUE TITLE
[Bug]: 最新版qqnt 插件失效

### ISSUE THREAD

**Issue by AltinaNissan** [LiteLoaderQQNT/LiteLoaderQQNT#320]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

 9.9.12-25493 

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

最新版qq 插件失效没有功能

### 期望的结果是什么？

插件生效，设置中可以看到插件

### 实际的结果是什么？

插件失效

**Comment by 20171213** [comment]
![QQ_1720355497030](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/34502902/c09f99b9-bcc3-4b06-8f40-ce345bccdec1)

一样，版本9.9.12-25300，但是插件一样生效， 只是不显示插件列表🤣

**Comment by Whuihuan** [comment]
我本来从24402升级到最新，结果一路回退到24402才能用

**Comment by Majjcom** [comment]
我在这个版本使用正常：
![屏幕截图](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/assets/55314301/b5755da7-9a5c-4285-ad09-5e87653b9211)
插件、主题 能正常加载

**Comment by cuddly-guacamole** [comment]
我排查出来问题了，我使用了LLAPI这个插件。把LiteLoaderQQNT\plugins下的LLAPI文件夹删除就行。

**Comment by LynahZ** [comment]
6.9.39-25493 依旧不生效

**Comment by lmtivy** [comment]
> mac 版 6.9.39-25493 依旧不生效

亲测有效，你用自动安装版试试！

**Comment by LynahZ** [comment]
> > mac 版 6.9.39-25493 依旧不生效
> 
> 亲测有效，你用自动安装版试试！

淦了，彻底卸载QQ重装才行

**Comment by littleaya** [comment]
> 我排查出来问题了，我使用了LLAPI这个插件。把LiteLoaderQQNT\plugins下的LLAPI文件夹删除就行。

+1

**Comment by hengkx** [comment]
> > > mac 版 6.9.39-25493 依旧不生效
> > 
> > 
> > 亲测有效，你用自动安装版试试！
> 
> 淦了，彻底卸载QQ重装才行

自动安装版是哪个我好像用的就是 脚本一键的

**Comment by liaoran2002** [comment]
确实是LLAPI的问题，我是把C:\Users\XXX\Documents\LiteloaderQQNT\plugins下的LLAPI
文件夹删了才解决的

**Comment by lmtivy** [comment]
> > > > mac 版 6.9.39-25493 依旧不生效
> > > 
> > > 
> > > 亲测有效，你用自动安装版试试！
> > 
> > 
> > 淦了，彻底卸载QQ重装才行
> 
> 自动安装版是哪个我好像用的就是 脚本一键的
用的这个
https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/install_mac.sh

**Comment by nfnfgo** [comment]
LiteLoader似乎还没有对于最新版（QQNT9.9.12）进行适配，目前我发现的有：

- WebComponent的`secondary`样式按钮渲染存在问题（从上方的截图也可以看出来）
- 一旦任何插件修改配置（调用了LL的api.config）相关接口，再次使用F5刷新设置界面，也会出现短暂的插件设置页不显示问题（这个比较玄学可能也不是LL的问题）

**Comment by LynahZ** [comment]
> > > > > mac 版 6.9.39-25493 依旧不生效
> > > > 
> > > > 
> > > > 亲测有效，你用自动安装版试试！
> > > 
> > > 
> > > 淦了，彻底卸载QQ重装才行
> > 
> > 
> > 自动安装版是哪个我好像用的就是 脚本一键的
> > 用的这个
> > https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/install_mac.sh

是这个没错，但是不知道什么原因，反正重装之后好了...

**Comment by hengkx** [comment]
> > > > > > mac 版 6.9.39-25493 依旧不生效
> > > > > 
> > > > > 
> > > > > 亲测有效，你用自动安装版试试！
> > > > 
> > > > 
> > > > 淦了，彻底卸载QQ重装才行
> > > 
> > > 
> > > 自动安装版是哪个我好像用的就是 脚本一键的
> > > 用的这个
> > > https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/install_mac.sh
> 
> 是这个没错，但是不知道什么原因，反正重装之后好了...

我就用的这个 不行，要把qq给卸载了重装吗？

**Comment by Kfkcome** [comment]
> > > > > > > mac 版 6.9.39-25493 依旧不生效
> > > > > > 
> > > > > > 
> > > > > > 亲测有效，你用自动安装版试试！
> > > > > 
> > > > > 
> > > > > 淦了，彻底卸载QQ重装才行
> > > > 
> > > > 
> > > > 自动安装版是哪个我好像用的就是 脚本一键的
> > > > 用的这个
> > > > https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/install_mac.sh
> > 
> > 
> > 是这个没错，但是不知道什么原因，反正重装之后好了...
> 
> 我就用的这个 不行，要把qq给卸载了重装吗？

我卸载重装了，用这个也不行，可能就是不适配吧，mac qq最新版

**Comment by wxxsfxyzm** [comment]
> 我排查出来问题了，我使用了LLAPI这个插件。把LiteLoaderQQNT\plugins下的LLAPI文件夹删除就行。

太感谢了，困扰好几天了！！！

**Comment by KaMmySuma** [comment]
> 我排查出来问题了，我使用了LLAPI这个插件。把LiteLoaderQQNT\plugins下的LLAPI文件夹删除就行。

测试有效，十分感谢

**Comment by lmtivy** [comment]
> > > > > > > > mac 版 6.9.39-25493 依旧不生效
> > > > > > > 
> > > > > > > 
> > > > > > > 亲测有效，你用自动安装版试试！
> > > > > > 
> > > > > > 
> > > > > > 淦了，彻底卸载QQ重装才行
> > > > > 
> > > > > 
> > > > > 自动安装版是哪个我好像用的就是 脚本一键的
> > > > > 用的这个
> > > > > https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/install_mac.sh
> > > 
> > > 
> > > 是这个没错，但是不知道什么原因，反正重装之后好了...
> > 
> > 
> > 我就用的这个 不行，要把qq给卸载了重装吗？
> 
> 我卸载重装了，用这个也不行，可能就是不适配吧，mac qq最新版

你卸载完了要记得把回收站也清空了，把插件和数据也先移出来。6.9.39-25493是用着的可以的

**Comment by mark9804** [comment]
我尝试移除了plugins当中所有的插件，但是 mac QQ 6.9.39-25493 仍然不能安装。有成功配置的 Mac 案例分享一下吗

**Comment by mo-jinran** [comment]
更新1.2.0
