### ISSUE TITLE
[Bug]: 使用WindowsPowerShell启动QQ不显示日志

### ISSUE THREAD

**Issue by QingFeng-awa** [LiteLoaderQQNT/LiteLoaderQQNT#326]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-25493

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

1.桌面右键QQ图标，点击`打开文件所在位置`。
2.在出现的文件夹窗口内按住`Shift`,右键，点击`在此处打开命令窗口`或`在此处打开 PowerShell 窗口`。
3.在弹出的控制台窗口内输入`.\QQ.exe`并按下`Enter`。

### 期望的结果是什么？

正常显示日志。

### 实际的结果是什么？

仅仅启动了QQNT,控制台无日志输出。

### 日志记录

![image](https://github.com/user-attachments/assets/1dfbbdf2-b96e-4a81-87ca-60df4d393053)

**Comment by adproqwq** [comment]
现在需要添加`--enable-logging`标志，之前在tg说过的

**Comment by mo-jinran** [comment]
这QQNT自己改的就不要发框架下了
