### ISSUE TITLE
[Bug]: 安装插件无效

### ISSUE THREAD

**Issue by chengshi415** [LiteLoaderQQNT/LiteLoaderQQNT#327]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.11-24815

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

<img width="625" alt="image" src="https://github.com/user-attachments/assets/c2dbbef7-647e-4365-9eeb-3370ae432ec9">

### 期望的结果是什么？

<img width="587" alt="image" src="https://github.com/user-attachments/assets/57cefe3d-1a24-4dd5-8b84-5c49320cbe25">

### 实际的结果是什么？

安装插件无效

### 日志记录

PS D:\Data\NTQQ> .\QQ.exe
PS D:\Data\NTQQ> not mini app.
[preload] process type:
[app]module file name: D:\Data\NTQQ\QQ.exe
[preload] hotupdate base version: 9.9.11-24815
[preload] hotupdate current version: 9.9.11-24815
[preload] install app version: 9.9.11-24815

[preload] succeeded. D:\Data\NTQQ\resources\app\app_launcher\launcher.node
[preload] succeeded. D:\Data\NTQQ\resources\app\versions\9.9.11-24815\major.node
[preload] succeeded. D:\Data\NTQQ\resources\app\versions\9.9.11-24815\wrapper.node
[LiteLoader] Use LITELOADERQQNT_PROFILE environment variables: C:\Users\Administrator\Documents\LiteloaderQQNT
[LiteLoader] Start finding all plugins.
[LiteLoader] Found 0 plugins, no plugin to be loaded.
[preload] register done. launcher.node
[preload] register done. major.node
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86829)
    at WebContents.emit (node:events:517:28)
[preload] register done. wrapper.node

**Comment by adproqwq** [comment]
要放在数据目录，不是本体目录

**Comment by chengshi415** [comment]
是用onebot一键安装脚本安装的，就是数据目录

**Comment by adproqwq** [comment]
> 是用onebot一键安装脚本安装的，就是数据目录
> 

你看看p1里的数据目录路径跟p2的路径，你就是放在本体目录了

**Comment by mo-jinran** [comment]
![QQ_1721832641491](https://github.com/user-attachments/assets/ba5849aa-e5ad-41b4-9009-4416e4653425)
根据这个为准
