### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Doushabao233** [LiteLoaderQQNT/LiteLoaderQQNT#329]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-25493 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

通过官方文档安装QQ和LiteloaderQQNT，QQ我个人安装到了`D:\QQ`，并将`resources\app\app_launcher\index.js`改为：

```
require(String.raw`D:\LiteLoaderQQNT`);
require('./launcher.node').load('external_launcher', module); 
```

然后下载了DLLHijackMethod，放在了QQ.exe同目录下。

### 期望的结果是什么？

运行QQ.exe，QQ打开并加载了LiteloaderQQNT

### 实际的结果是什么？

报错。

![image](https://github.com/user-attachments/assets/2c3e4765-27a9-4d0a-a210-7ebaa8493967)

### 日志记录

无（用终端运行，完全没日志）

### 补充说明（可选）

js中去掉require(String.raw\D:\LiteLoaderQQNT\);后，QQNT可正常打开。

个人猜测问题出在了Loader的代码中有会报错的代码。

**Comment by KLuoNuoYa** [comment]
请问你LiteloaderQQNT放在哪了

**Comment by Doushabao233** [comment]
> 请问你LiteloaderQQNT放在哪了

D:\LiteLoaderQQNT

**Comment by KLuoNuoYa** [comment]
> D:\LiteLoaderQQNT

有没有嵌套文件夹

**Comment by Doushabao233** [comment]
> > D:\LiteLoaderQQNT
> 
> 有没有嵌套文件夹

没有，文件夹下直接就是文件

```
D:\LITELOADERQQNT
├─.github
│  └─ISSUE_TEMPLATE
├─data
│  └─LiteLoader
├─plugins
└─src
    ├─components
    │  └─static
    ├─easter_eggs
    ├─liteloader_api
    └─setting
        └─static
```

**Comment by KLuoNuoYa** [comment]
等一下，你是直接clone的仓库？

**Comment by KLuoNuoYa** [comment]
你试试releases里面的

**Comment by Doushabao233** [comment]
> 你试试releases里面的

好，我把LiteLoaderQQNT文件夹的东西全删了，下载了releases的版本，完了放进去

tree后输出：

```
D:\LITELOADERQQNT
└─src
    ├─components
    │  └─static
    ├─easter_eggs
    ├─liteloader_api
    └─setting
        └─static
```

还是会报错

![image](https://github.com/user-attachments/assets/ad76f6f2-2906-4083-8250-ee706737597d)

**Comment by blblkang** [comment]
尝试重装dbghelp，删除PatchConfig.json，手动恢复index.js

**Comment by Starrain08** [comment]
index.js文件改错了
要这样改才会生效，官网改法有问题
![QQ_1721110468352](https://github.com/user-attachments/assets/64d5015f-267b-4b2e-8e83-3761734655b2)

**Comment by Starrain08** [comment]
> index.js文件改错了 要这样改才会生效，官网改法有问题 ![QQ_1721110468352](https://private-user-images.githubusercontent.com/119772101/348962608-64d5015f-267b-4b2e-8e83-3761734655b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTA5MTcsIm5iZiI6MTcyMTExMDYxNywicGF0aCI6Ii8xMTk3NzIxMDEvMzQ4OTYyNjA4LTY0ZDUwMTVmLTI2N2ItNGIyZS04ZTgzLTM3NjE3MzQ2NTViMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwNjE2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTcwOTJkNDc5OGI5NGYyMjMyMDUyMmQxMTFlZmI3NjU3NzFkZGIxNzI5MzFmMzkyZmI1MmE1MTQ4ZTk2NmMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8wfl7LBaOPj6zdjHx6ujYRQC3TTv9v9FmTypoU3HZSo)

之前遇到过这个问题，后面把这两段纠正后就正常了

**Comment by Doushabao233** [comment]
1. 我在测试你们的方案时，发现文件改错地方了，我改的是launcher.js；
2. 纠正错误之后，我恢复了launcher.js原貌，然后去改index.js，参考了教程和Starrain08的方法，QQ是可以打开了，但是还是没法注入加载器；
3. 尝试过重装dbghelp、删除PatchConfig.json、手动恢复index.js，都不奏效。

**Comment by XiaozhiSans** [comment]
> index.js文件改错了 要这样改才会生效，官网改法有问题 ![QQ_1721110468352](https://private-user-images.githubusercontent.com/119772101/348962608-64d5015f-267b-4b2e-8e83-3761734655b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDg0NzgsIm5iZiI6MTcyNjE0ODE3OCwicGF0aCI6Ii8xMTk3NzIxMDEvMzQ4OTYyNjA4LTY0ZDUwMTVmLTI2N2ItNGIyZS04ZTgzLTM3NjE3MzQ2NTViMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMzM2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzA2ZGI0Y2U0MDVhOGQ3MjdkMTU1OGJkOGQ0NGY1YTM1MjFlYTQyZTViY2UwMTNiOWZmZDc3YWVmYjkwZDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qMjQEYCvFBfTIdSawTvM2HhdN99jh-BNFXTn5ytAHhU)

我寻思我这么改也没问题啊
![image](https://github.com/user-attachments/assets/f2289c2b-7365-47d0-8049-4e8f556763d3)
![image](https://github.com/user-attachments/assets/d2f91bd0-f6f8-4688-95e8-4e9e706f4dc2)

**Comment by mo-jinran** [comment]
使用1.2.2版本，修改了启动流程，查看官网最新的安装教程
