### ISSUE TITLE
[Bug]: 文件损坏

### ISSUE THREAD

**Issue by GisliWong** [LiteLoaderQQNT/LiteLoaderQQNT#330]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.11.24616

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

按照官网的安装方式，修改index.js，打补丁，运行时报错：“文件已损坏，请重新安装“
![image](https://github.com/user-attachments/assets/de0f871d-d0bf-4657-868b-de6793cdd37f)

### 期望的结果是什么？

期望值是不会出现错误，进入QQ主界面

### 实际的结果是什么？

![image](https://github.com/user-attachments/assets/de0f871d-d0bf-4657-868b-de6793cdd37f)

### 日志记录

[app]module file name: D:\QQ\QQ.exe
b83a94f2f9dd0b652230cb53c68d83cf0a82f2188b652594b3e53849e8ec8181
435f46b66f8954648d8cf140c5634cd39e5138cf20f3ee6cc32edb4a6fce269f
error code v2:-8

**Comment by GisliWong** [comment]
在恢复index.js后，QQ正常运行；移动LiteLoader文件位置并不能解决问题

**Comment by Starrain08** [comment]
> 在恢复index.js后，QQ正常运行；移动LiteLoader文件位置并不能解决问题

看看index.js怎么修改的
只有这种才能生效
![QQ_1721110468352](https://github.com/user-attachments/assets/0c6b9a6a-3111-47c5-87e5-a3d45bda37de)

**Comment by pjy612** [comment]
https://liteloaderqqnt.github.io/guide/install.html

我也是刚出现这问题 还以为是QQ坏了 都忘了还有 Patch 这一茬了。。。

**Comment by mo-jinran** [comment]
你应该按照官网教程安装，或使用安装器，你没有进行patch绕过文件损坏验证
