### ISSUE TITLE
[Hope]: 功能请求

### ISSUE THREAD

**Issue by Starrain08** [LiteLoaderQQNT/LiteLoaderQQNT#331]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

目前QQ9.9.12版本去除了透明效果，能不能出一个插件修改一下侧边栏的显示效果，比如实现侧边栏半透明或者磨砂，透明效果

**Comment by mo-jinran** [comment]
https://github.com/mo-jinran/More-Materials

**Comment by Shapaper233** [comment]
> https://github.com/mo-jinran/More-Materials

你好我这边亚克力效果确实是有的
![image](https://github.com/user-attachments/assets/ba590340-950b-4e92-9241-c6192e7967ff)
但是侧边栏一直有个白底怎么破，设置里面的列表也是一样
