### ISSUE TITLE
修改错误建议

### ISSUE THREAD

**Issue by Starrain08** [LiteLoaderQQNT/LiteLoaderQQNT#332]
官网上的手动安装中修改index.js是有误的，会导致运行失败报错，并且文件夹路径是错误填法，会导致识别为字符，正确修改如图2，并且Windows用户在填写路径时应该使用"//"或者"\"
![QQ_1721111343438](https://github.com/user-attachments/assets/438bc013-a49c-4944-8d59-b85a8e750506)
![QQ_1721111613231](https://github.com/user-attachments/assets/a4f051ff-bccb-4c3a-bc6e-cfbd1c7f90dc)

**Comment by mo-jinran** [comment]
代码以奇怪的方式跑起来了

**Comment by mo-jinran** [comment]
框架是需要在QQNT初始化之前加载，你还给放在后面了

**Comment by mo-jinran** [comment]
而且在使用了String.raw后不要再次进行字符转义，因为String.raw的字符串就是raw的

**Comment by Starrain08** [comment]
> 代码以奇怪的方式跑起来了

我之前遇到过，后面改了才正常的，并且编辑器里会把路径/那里识别成其他东西

**Comment by Starrain08** [comment]
> 框架是需要在QQNT初始化之前加载，你还给放在后面了

反正就很奇怪，特别是新安装时最容易出现运行时出现报错

**Comment by xiyuesaves** [comment]
~~为什么你会觉得你比作者还了解代码？~~
