### ISSUE TITLE
[Bug]: 无法正常显示 QQ Emoji 表情

### ISSUE THREAD

**Issue by FriedCoderZ** [LiteLoaderQQNT/LiteLoaderQQNT#333]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.2-25765

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

1. 安装LiteLoaderQQNT，观察QQ聊天表情列表是否正常显示 QQ Emoji ，观测聊天记录中的 QQ Emoji 是否正常显示。

### 期望的结果是什么？

可以正常发送或显示QQ Emoji表情

### 实际的结果是什么？

无法正常发送或显示QQ Emoji表情
![image_164](https://github.com/user-attachments/assets/17a11511-29f0-4b8c-a895-4597ce54dd88)
![image_165](https://github.com/user-attachments/assets/b011c3bc-f1bc-480d-9e3e-3488aca1e9f4)

### 日志记录

终端不输出日志

### 补充说明（可选）

以上个人测试均于无插件环境下进行
![image_167](https://github.com/user-attachments/assets/e6ec1dc5-fcb1-4760-b274-4f464fd23e8d)
![image_168](https://github.com/user-attachments/assets/ba266e56-8ca2-4acb-90e4-3766fe947743)

**Comment by as88866920** [comment]
我的也一样
有插件的不能显示
没插件的可以显示

**Comment by DogeCN** [comment]
> 我的也一样 有插件的不能显示 没插件的可以显示

我没插件也不能显示（；´д｀）ゞ

**Comment by long45343** [comment]
测试之后发现是9.9.12的版本都这样

**Comment by FortunateKoi** [comment]
经测试macOS平台也有该问题，影响6.9.39-25765。

**Comment by adproqwq** [comment]
使用轻量工具箱自定义字体功能，覆盖原emoji大概可以解决

**Comment by DogeCN** [comment]
> 使用轻量工具箱自定义字体功能，覆盖原emoji大概可以解决

尝试过无法解决

![image](https://github.com/user-attachments/assets/cec74106-f602-4a80-8df5-6c11db180e73)

**Comment by as88866920** [comment]
我也试了，没有用
慢慢等解决了

**Comment by adproqwq** [comment]
新版好像修复了，但是LL在新版有bug

**Comment by as88866920** [comment]
那就只能继续等待了

**Comment by Retagrb** [comment]
除此之外，安装 LiteLoaderQQNT 后，使用 QQ 本身的表情快捷键也会失效，例如 /kk 会自动渲染成[快哭了]这个表情，但是使用了 LiteLoaderQQNT 之后 /kk 没办法渲染成表情。

**Comment by DogeCN** [comment]
已经修了，下仓库代码包替换就行。

**Comment by as88866920** [comment]
> 已经修了，下仓库代码包替换就行。

哪里下仓库代码包替换

**Comment by DogeCN** [comment]
> 哪里下仓库代码包替换

![](https://github.com/user-attachments/assets/fdf5a352-b31e-480a-a76a-af09d6e68977)

**Comment by as88866920** [comment]
> > 哪里下仓库代码包替换
> 
> ![](https://private-user-images.githubusercontent.com/142157562/353350456-fdf5a352-b31e-480a-a76a-af09d6e68977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjU1NDYsIm5iZiI6MTcyMjMyNTI0NiwicGF0aCI6Ii8xNDIxNTc1NjIvMzUzMzUwNDU2LWZkZjVhMzUyLWIzMWUtNDgwYS1hNzZhLWFmMDlkNmU2ODk3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwNzQwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODBmNTU4NWE0ZGEyZTAxMmQwY2MyMTM2ZmNkNDhkMGY3NjVkY2FmZTkxNWE1OTA5ZWU3OGQzMDYzNGViODMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jeF-61cVdduwCzoVkhISbVtyqn2v0NFOfoIx7SWY3Ko)

OK，搞定
