### ISSUE TITLE
[Feat]: 群消息首次提醒并发出提示音，但后续不会提醒，除非主动浏览群信息

### ISSUE THREAD

**Issue by 5418541** [LiteLoaderQQNT/LiteLoaderQQNT#336]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

现在群消息如果开启提醒一有消息就会叫 能不能让第一次提醒叫一声，后续就不叫了，除非我主动打开了Q群 或者点了忽略全部的按钮

**Comment by adproqwq** [comment]
这是插件应该干的，不是框架干的

**Comment by 5418541** [comment]
搞错了，是因为轻量工具箱不支持新功能请求所以才发这

**Comment by adproqwq** [comment]
> 搞错了，是因为轻量工具箱不支持新功能请求所以才发这

那你应该选新插件请求
