### ISSUE TITLE
[Hope]: 功能申请，查看合并转发消息记录来源群号/转发记录中人员qq号

### ISSUE THREAD

**Issue by XiliuEIF** [LiteLoaderQQNT/LiteLoaderQQNT#344]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

如题，安卓有QA可以做到这样的功能，虽然消息转发次数过多也会导致群号/qq号被屏蔽无法查到。在LiteLoader复现具有一定的可行性。

**Comment by CreeperAWA** [comment]
我记得这个已经修了诶，现在已经不准了，自己合并发自己查都查不到了（哪怕显示了群号、QQ号，但也是错误的）

**Comment by CO2mega** [comment]
实测在合并转发后，只有在自己账号上qa才能看到群号和qq，在其他账号上qa会显示已被服务端屏蔽

**Comment by XiliuEIF** [comment]
ok，那这个issue就关掉了

**Comment by CreeperAWA** [comment]
这个我记得已经修了，不过有的时候可能有用，比如都是你的好用，我今天在研究拦截QQ的部分域名屏蔽广告和部分信息上报，发现了有一个插件的脚本可以实现这个功能
[链接在这](https://github.com/PRO-2684/Scriptio-user-scripts#msg-record-enhance) 你可以自己研究研究
