### ISSUE TITLE
[Bug]: 使用/无法唤醒表情界面

### ISSUE THREAD

**Issue by xiaoahennuli** [LiteLoaderQQNT/LiteLoaderQQNT#346]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-25765

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

在群内和私信无法打出/唤醒表情功能(例如打/ww就是狗头)
已经尝试了切换成/唤醒机器人模式,没问题可以正常用,切换表情就无法唤醒

### 期望的结果是什么？

打/能正常唤醒表情

### 实际的结果是什么？

如果是表情模式,打/没有效果
如果是机器人指令模式,一切正常

### 日志记录

无日志

### 补充说明（可选）

已经尝试重装QQ,不装LiteLoaderQQNT时正常,安装LiteLoaderQQNT后(无插件情况)无法正常唤起表情

**Comment by xiaoahennuli** [comment]
![88f2ac782beb3a643d2dbd8d30d90cec](https://github.com/user-attachments/assets/9be93f03-5be0-45e2-a9e6-100d74b477ee)

**Comment by Sowari** [comment]
同样的版本，同样的问题。

**Comment by mo-jinran** [comment]
今天复现了，已定位到问题所在，正在想办法解决
