### ISSUE TITLE
[Bug]: 截图UI不显示

### ISSUE THREAD

**Issue by qhy040404** [LiteLoaderQQNT/LiteLoaderQQNT#347]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-26299

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

1. 关闭插件加载器重启qq
2. 打开任意聊天窗口或快捷键触发截图，截图工具不显示
3. 在`launcher.js`注释掉ll再启动qq可以正常显示截图

### 期望的结果是什么？

正常显示截图ui

### 实际的结果是什么？

qq窗口仅消失，会有一个全屏顶层隐藏窗口，但是截图ui不显示

**Comment by xiyuesaves** [comment]
新版本暂未适配，需要降级或使用旧版截图

**Comment by mo-jinran** [comment]
目前最新的commit已修复，可拉取仓库代码使用，或等待发新版
