### ISSUE TITLE
[Bug]: 录屏功能无法正常使用

### ISSUE THREAD

**Issue by naahi-i** [LiteLoaderQQNT/LiteLoaderQQNT#348]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-25493 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

Ctrl+Alt+S开启录屏，在倒计时结束后出现录屏失败提示框

### 期望的结果是什么？

正常录屏

### 实际的结果是什么？

录屏失败
![a395f808-e839-495d-b009-7a6ad96e03bb](https://github.com/user-attachments/assets/9900ba3f-3260-49db-9686-713ec69e42eb)

**Comment by naahi-i** [comment]
> 无法复现，尝试更新1.2.0版本

1.2.0依旧无法录屏

**Comment by mo-jinran** [comment]
在删除LiteLoader的情况下是否可复现？
