### ISSUE TITLE
[Bug]: Windows 最新版 QQNT 上安装出现错误

### ISSUE THREAD

**Issue by b6e0** [LiteLoaderQQNT/LiteLoaderQQNT#350]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

安装最新版 QQ，按照指示修改 index.js 文件，启动 QQ

### 期望的结果是什么？

QQ 正常启动

### 实际的结果是什么？

![error](https://github.com/user-attachments/assets/33f81b9b-e6a0-47d8-be08-8d3a345f6647)

### 日志记录

无日志：
![image](https://github.com/user-attachments/assets/67681a11-64d2-4b6e-8de1-4c6e9d454064)

### 补充说明（可选）

QQNT 退回到 9.9.11 版本后出现同样错误

**Comment by adproqwq** [comment]
Windows修改文件之后需要进行修补，你确认进行了？如果没有，文档上写得很清楚了。

**Comment by b6e0** [comment]
好吧，我的修补文件不知道在哪次更新中消失了，我的问题。
