### ISSUE TITLE
[Bug]: 该项目会导致QQ加载表情出现异常Bug

### ISSUE THREAD

**Issue by David-xian66** [LiteLoaderQQNT/LiteLoaderQQNT#351]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.39-25765

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

MacOS

### 重现步骤

不需要任何操作，你就启动你使用了LiteLoaderQQNT的QQ即可

随后，你会在左侧的聊天预览中看到如下图片：（注意这个笑脸）
![image](https://github.com/user-attachments/assets/be0d218d-2afd-407a-8a51-19774ef35fef)
有问题的第一个聊天

再给你看一个：
![image](https://github.com/user-attachments/assets/7b01fa29-cf65-42d1-aabf-744a8e8f316b)
有问题的第二个聊天

这个就是导致的bug，你以为就这？当然不是

点进第一个图片的聊天里，然后你会发现连带的其他Bug：
![image](https://github.com/user-attachments/assets/e70f39b8-1cfa-4328-ab47-7f4bd080050d)
显示不出来的，正式他给我发的“比心”表情
![image](https://github.com/user-attachments/assets/afa0e783-ee3e-4005-873b-cdc522271556)
我们打开表情面板，这个一直在加载的表情也正是这个

不过。。。还没完事
这个时候我们打开有问题的第二个聊天，你会发现，bug没有了
![image](https://github.com/user-attachments/assets/6a970709-b526-49e2-a483-a081d2071bc8)

，但是你再回到第一个聊天，bug依然存在，并且再表情面板里，那个“比心”表情依然在加载。

==========

随后，咱们重启qq，你这次先点击有问题的第二个聊天：
看：
![image](https://github.com/user-attachments/assets/0a635df5-52e0-48c8-ab57-a2ec8b60b214)
当然了，不用想，表情商店里bug依然存在

（这个时候你可能已经明白整个bug表现了）

我们现在看看第一个聊天：
![image](https://github.com/user-attachments/assets/f70b6219-1960-40ae-aa5f-49358711b30d)

=======
现在应该明白了吧
然后这个在加载的表情包是点不了的

https://github.com/user-attachments/assets/6e90fb4c-a750-48e9-b233-cf679dda3efe

=========
（注意：我保证我的qq没有任何问题，qq存储这些表情包的目录我检查过，我也重置过，当然这都不重要，重要的是我卸载LiteLoaderQQNT后qq就没这个问题了）

### 期望的结果是什么？

显示表情

### 实际的结果是什么？

出现Bug

### 日志记录

qq自己报的一个错，但是我感觉和这个无关
```
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82968)
    at WebContents.emit (node:events:519:28)
```

**Comment by HuanMeng-official** [comment]
《没有找到相同问题的ISSUE》这个issue我已经提了（#319）开发者完全没动静，放弃吧兄弟（

**Comment by mo-jinran** [comment]
无法复现此类问题，其他开发者也没遇到过

**Comment by NotUNperson** [comment]
我也有类似的问题，也是关闭插件加载器，仅使用LiteLoaderQQNT，QQ默认小表情全部无法显示，收到的默认自带表情会统一显示同一种图标，无法复制
![image](https://github.com/user-attachments/assets/492c010d-3ccd-4c03-a848-cf275d41a4cb)
![image](https://github.com/user-attachments/assets/2917662e-135f-45b5-9320-604322c1b75e)

**Comment by mo-jinran** [comment]
终于是想办法复现了，已定位到问题所在，正在想办法解决

**Comment by David-xian66** [comment]
收到
