### ISSUE TITLE
[Bug]: 安装LiteLoader后，部分表情加载失败

### ISSUE THREAD

**Issue by xyfAKIOI** [LiteLoaderQQNT/LiteLoaderQQNT#354]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-25765

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

安装LiteLoader，然后打开QQNT，单击任意会话以加载消息；关闭插件加载器，重启QQNT

### 期望的结果是什么？

所有消息显示正常

### 实际的结果是什么？

两次结果一致，并多次重复验证。打开QQNT后，会话列表中，所有会话的最后一条消息，表情未正常显示。单击某会话以加载消息，该会话中最先加载出来的几条消息中，表情未正常显示。同时，其他会话中的表情恢复正常。未正常显示的所有表情在表情列表中也异常，无法显示或发送。其他表情正常。

**Comment by onlookerLi** [comment]
+1 会以打开qq时，发出或接收到最后一个表情无法加载，亦无法发出

**Comment by Arcticn** [comment]
#351
已经修复了，从仓库下载最新代码覆盖就可以了，我这边已经没问题了

**Comment by xyfAKIOI** [comment]
我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，但是没有找 Closed 里面的，wssb

**Comment by xyfAKIOI** [comment]
> #351 已经修复了，从仓库下载最新代码覆盖就可以了，我这边已经没问题了

我刚试过了，并没有

**Comment by Arcticn** [comment]
那有点奇怪，是不是下错了？还没发release，直接下载新代码
我是先有问题，然后删除原先的，再把新的安装上，就好了

**Comment by xyfAKIOI** [comment]
> 那有点奇怪，是不是下错了？还没发release，直接下载新代码 我是先有问题，然后删除原先的，再把新的安装上，就好了

那我试试

**Comment by xyfAKIOI** [comment]
> 那有点奇怪，是不是下错了？还没发release，直接下载新代码 我是先有问题，然后删除原先的，再把新的安装上，就好了 9.9.12-26339版本

确实修好了，希望能尽快发新 Release

**Comment by onlookerLi** [comment]
您好 是怎么解决的呢 ？下载新代码是指哪部分？

**Comment by Arcticn** [comment]
![图片](https://github.com/user-attachments/assets/f79f10b7-243d-4071-9153-9ccfcc670cea)
