### ISSUE TITLE
[Bug]: 无法使用QQ截图功能 会卡死

### ISSUE THREAD

**Issue by 5418541** [LiteLoaderQQNT/LiteLoaderQQNT#360]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

1.1.2

### LiteLoaderQQNT 版本 （或 Commit Id）

9.9.12 26339

### 运行环境

Windows

### 重现步骤

在官网下载的QQ 再在设置里面检测更新 就会更新到26339版本

### 期望的结果是什么？

点击截图后正常弹出截图功能

### 实际的结果是什么？

卡死 可以按esc退出

### 日志记录

![image](https://github.com/user-attachments/assets/4a8f6662-49c6-45c5-ad47-e18b02751bd6)
日志怎么看啊？这个只会叫我打开QQ 看不了日志啊

**Comment by mo-jinran** [comment]
装新版

**Comment by 5418541** [comment]
> 装新版

QQnt和QQ都已经检查是最新版了，没法再更新了

**Comment by fuhuojie123** [comment]
已经解决了，忘记关闭了，当时是是QQ更新后，QQnt再一次更新解决的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月2日(周三) 晚上11:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LiteLoaderQQNT/LiteLoaderQQNT] [Bug]: 无法使用QQ截图功能 会卡死 (Issue #360)




 
装新版的NTQQ还是新版的NTQQ插件？
