### ISSUE TITLE
[Bug]: 启动后页面异常

### ISSUE THREAD

**Issue by David-xian66** [LiteLoaderQQNT/LiteLoaderQQNT#361]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.51-26339

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.0

### 运行环境

MacOS

### 重现步骤

1、我们使用
`curl -L "https://github.com/Mzdyl/LiteLoaderQQNT_Install/raw/main/install.sh" -o /tmp/install_git.sh && bash /tmp/install_git.sh`
命令来一键安装，随后我们在打开后发现报错：

![image](https://github.com/user-attachments/assets/3658991a-1711-4830-9aed-f2ba5b89da60)

2、我们根据提示，移动文件夹，下面是移动后的效果

![image](https://github.com/user-attachments/assets/a2b6ae58-a696-423b-8ba6-8e584a6677d1)

3、我们再次打开qq，如下
![image](https://github.com/user-attachments/assets/eb1bfbc8-564c-4f71-8bbb-0f29ab04c4b2)

### 期望的结果是什么？

正常显示页面

### 实际的结果是什么？

无法显示页面

### 日志记录

未找到关键记录

**Comment by David-xian66** [comment]
在https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/356中我们看到同样问题，但是他的Linux版本太低了，1.2.0最低要求是`25765`，但是我这个是`26339`

**Comment by Mzdyl** [comment]
请问QQ是App Store 商店版还是官网下载的版本
以及  `~/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/versions` 内是否存在QQUpdate.app

**Comment by David-xian66** [comment]
> 请问QQ是App Store 商店版还是官网下载的版本 以及 `~/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/versions` 内是否存在QQUpdate.app

官网下载的版本，存在QQUpdate.app

**Comment by bootlegseahorse** [comment]
> > 请问QQ是App Store 商店版还是官网下载的版本 以及 `~/Library/Containers/com.tencent.qq/Data/Library/Application Support/QQ/versions` 内是否存在QQUpdate.app
> 
> 官网下载的版本，存在QQUpdate.app

可以参考我在https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/367提到的方法。

卸载旧版QQNT，从官网下载新版QQNT覆盖安装，再安装LiteLoader之后，QQNT应该可以恢复正常。

**Comment by David-xian66** [comment]
@mo-jinran 我在windows上也发现了同样的问题

**Comment by LHXCxyw** [comment]
请问能不能支持9.9.11版本的ntqq安装LiteLoaderQQNT，因为我发现最新版9.9.15安装后非常卡顿，且经常报错闪退

**Comment by Mzdyl** [comment]
> 请问能不能支持9.9.11版本的ntqq安装LiteLoaderQQNT，因为我发现最新版9.9.15安装后非常卡顿，且经常报错闪退

可以，但新版LL（1.2.0 之后）版本不支持旧版QQ
若想给 9.9.11 安装的话请手动安装老版本LL，如1.1.0？之类的
安装器不支持老版本安装

**Comment by mo-jinran** [comment]
更新1.2.2版本，更换了preload的加载方式，不会有这类问题发生了
