### ISSUE TITLE
[Feat]: 使用环境变量指定 data 位置

### ISSUE THREAD

**Issue by TTsdzb** [LiteLoaderQQNT/LiteLoaderQQNT#363]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

部分 Linux 用户可能使用系统包管理器（如通过 AUR 构建）安装插件。此时插件存放在 LiteLoaderQQNT 安装目录下（类似 #210）。但倘若同时使用该目录存放 `data`，会造成以下问题：

- 系统上的所有用户共享同一份插件数据，这可能不是所希望的
- 需要额外对 LiteLoaderQQNT 安装目录赋予读写权限

建议在现有机制的基础上，通过指定 `LITELOADERQQNT_PROFILE_DATA` 指定插件数据的存放位置。也可以考虑添加 `LITELOADERQQNT_PROFILE_PLUGINS` 指定插件目录。

**Comment by mo-jinran** [comment]
本来就能指定`LITELOADERQQNT_PROFILE`位置为什么要单独设置plugins和data位置

**Comment by mo-jinran** [comment]
你给每个用户单独设置`LITELOADERQQNT_PROFILE`环境变量就行了

**Comment by TTsdzb** [comment]
> 本来就能指定LITELOADERQQNT_PROFILE位置为什么要单独设置plugins和data位置

你没明白我的意思，在这种情况下插件和 LiteLoaderQQNT 本体都是通过包管理器安装的，例如 [liteloader-qqnt-lite-tools-bin](https://aur.archlinux.org/packages/liteloader-qqnt-lite-tools-bin)。这样插件也会在系统更新时一并更新，省去很多心力。但是目前如果插件安装在系统里那根本没法比较优雅地设置，要么插件也放在用户目录里，要么用户的数据放系统目录。

规范而言，插件的本体与数据不同，并不是一个需要读写的目录。本体更类似于可执行文件，数据则可能是每个用户都不同的。请问将二者绑定到一起有什么优势呢？

**Comment by mo-jinran** [comment]
可以安装非aur插件，而且aur内的插件就那几个还不是官方维护
以及在框架侧安装插件也需要具备可读写，或者插件市场类插件
