### ISSUE TITLE
[Bug]: 装载 LiteLoaderQQNT 后 QQ 无法启动

### ISSUE THREAD

**Issue by hetaoawa** [LiteLoaderQQNT/LiteLoaderQQNT#365]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12_240729

### LiteLoaderQQNT 版本 （或 Commit Id）

6a059f5

### 运行环境

Windows

### 重现步骤

手动安装 QQNT
按照 [liteloaderqqnt.github.io/guide/install.html](https://liteloaderqqnt.github.io/guide/install.html) 的教程安装 LiteLoaderQQNT
在 resources\app\app_launcher\index.js 文件最前端插入一行require(String.raw`已经改过路径啦`);
保存
运行 QQNT

### 期望的结果是什么？

正常运行并打开 QQ 且 LiteLoaderQQNT 成功安装

### 实际的结果是什么？

QQ 无法运行
![image](https://github.com/user-attachments/assets/582e016a-12ce-49a5-8d80-f97c4f8f60c5)

### 日志记录

![image](https://github.com/user-attachments/assets/5c1e0b1e-895f-493b-96fc-42588bbace32)

### 补充说明（可选）

服务器系统
![image](https://github.com/user-attachments/assets/385b45da-7856-47e4-8832-f188bddf5a4b)

**Comment by Dyson777** [comment]
我这边Windows端，QQNT版本是9.9.11-24568，加载 LiteLoaderQQNT 1.2.0版本时，启动QQ，登录界面空白，无法显示头像、账号密码输入框、登录按钮。
退回 LiteLoaderQQNT 1.1.2之后正常

**Comment by hetaoawa** [comment]
补充一下 感谢 @Dyson777 提供的灵感（x
我更换了 LiteLoaderQQNT 1.1.2 后 QQ 就能正常打开并使用了
且加载插件没有问题

**Comment by mo-jinran** [comment]
无效的issue
