### ISSUE TITLE
[Bug]: LiteLoaderQQNT 1.2.0 Release 版本导致MacOS下软件内在线更新的QQNT无法启动

### ISSUE THREAD

**Issue by bootlegseahorse** [LiteLoaderQQNT/LiteLoaderQQNT#367]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

6.9.51-26339（从旧版软件内左下角在线更新版本）

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.0 Release

### 运行环境

MacOS Ventura 13.6.1

### 重现步骤

之前使用1.1.2版本，一切正常
使用`curl -L "https://github.com/Mzdyl/LiteLoaderQQNT_Install/raw/main/install.sh" -o /tmp/install_git.sh && bash /tmp/install_git.sh`命令安装1.2.0版本之后，QQNT无法启动
卸载，手动重装1.2.0版本，QQNT依然无法启动
卸载1.2.0版，装回1.1.2版，QQNT重新正常启动

### 最新进展

之前我使用的QQNT版本是从旧版本QQ软件左下角在线更新至最新版的，这种更新方式与LiteLoader不兼容。
卸载旧版QQ，从官网下载新版QQ覆盖安装，再安装LiteLoader之后，QQNT恢复正常启动。

### 期望的结果是什么？

在MacOS下，QQNT在左下角热更新之后，可以在新版本LiteLoader安装后正常启动。

### 实际的结果是什么？

在MacOS下，QQNT在左下角热更新之后，在新版本LiteLoader安装后无法启动，但旧版本LiteLoader可以正常启动。
去官网下载最新版本QQNT，之后覆盖安装Applications文件夹中的QQNT，再安装LiteLoader之后，QQ恢复正常启动。
Windows下一切正常。

### 补充说明（可选）

之前我使用的QQNT版本是从旧版本QQ软件左下角在线更新至最新版的，这种更新方式与LiteLoader不兼容。
去官网下载最新版本QQNT，之后覆盖安装Applications文件夹中的QQNT，再安装LiteLoader之后，QQ恢复正常。

**Comment by OiCkilL** [comment]
我也有一样的情况，提示让我把 /Users/USER/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/application 移动到 /Applications/QQ.app/Contents/Resources/app

照做后，列表查看器会有bug，无法用release包安装，不能完整安装插件，把轻量工具箱更新新版重启后发现会缺文件无法正常使用。

**Comment by OiCkilL** [comment]
> > 我也有一样的情况，提示让我把 /Users/USER/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/application 移动到 /Applications/QQ.app/Contents/Resources/app
> > 照做后，列表查看器会有bug，无法用release包安装，不能完整安装插件，把轻量工具箱更新新版重启后发现会缺文件无法正常使用。 列表上无提供图标的插件会变成一直闪烁的placeholder
> 
> 你是不是和我一样，使用的是软件内热更新的版本？
> 
> 就是从旧版本QQ左下角“检测更新”升级到新版本的？
> 
> 我才发现，这种方法更新的QQ是和LiteLoader不兼容的。
> 
> 只要去官网下载最新版本，之后覆盖安装Applications文件夹中的QQ即可。

不，我是官网下载的最新版

**Comment by bootlegseahorse** [comment]
> > > 我也有一样的情况，提示让我把 /Users/USER/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/application 移动到 /Applications/QQ.app/Contents/Resources/app
> > > 照做后，列表查看器会有bug，无法用release包安装，不能完整安装插件，把轻量工具箱更新新版重启后发现会缺文件无法正常使用。 列表上无提供图标的插件会变成一直闪烁的placeholder
> > 
> > 
> > 你是不是和我一样，使用的是软件内热更新的版本？
> > 就是从旧版本QQ左下角“检测更新”升级到新版本的？
> > 我才发现，这种方法更新的QQ是和LiteLoader不兼容的。
> > 只要去官网下载最新版本，之后覆盖安装Applications文件夹中的QQ即可。
> 
> 不，我是官网下载的最新版

那是有点奇怪了，我的轻量工具箱完全可以正常使用。

你可以单独开一个issue讨论一下，咱俩遇到的可能不是同一个问题。

**Comment by xiyuesaves** [comment]
> 照做后，列表查看器会有bug，无法用release包安装，不能完整安装插件，把轻量工具箱更新新版重启后发现会缺文件无法正常使用。 列表上无提供图标的插件会变成一直闪烁的placeholder

工具箱有自更新功能，不要使用插件列表去更新，不要点 `使用仓库代码包`

**Comment by eeetechen** [comment]
## QQNT 版本
6.9.51-26339（从旧版软件内左下角在线更新版本）
## LiteLoaderQQNT 版本 （或 Commit Id）
1.2.0 Release

### 运行环境
MacOS Ventura 13.6.1

### 重现步骤
使用curl -L "https://github.com/Mzdyl/LiteLoaderQQNT_Install/raw/main/install.sh" -o /tmp/install_git.sh && bash /tmp/install_git.sh命令安装最新latest版本之后，打开会提示转移Application，转移后。QQNT 图标会跳动，但是没有窗口。
移除插件目录所有插件之后仍保持原样，dock栏表示程序在运行，但是没有窗口 GUI界面。
不知道跟前面的win版无法启动是不是一个问题。
#396

**Comment by mo-jinran** [comment]
不清楚MacOS下的QQNT的情况，也可能是安装脚本的问题
不过1.2.2版本更换了preload的加载方式，不再需要复制文件
安装方式也变得更加简单，或许可以减少各种意外情况发生
更新QQNT后也必须重新安装LiteLoaderQQNT这是没办法的
