### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HanaKDev** [LiteLoaderQQNT/LiteLoaderQQNT#371]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.12-26339

### LiteLoaderQQNT 版本 （或 Commit Id）

@latest

### 运行环境

Windows

### 重现步骤

干净安装QQ与LiteLoader，并且直接启动

### 期望的结果是什么？

NtQQ 正常运行

### 实际的结果是什么？

崩溃

### 日志记录

![image](https://github.com/user-attachments/assets/f09ca064-52da-4919-b7cf-8ccb111135ae)

### 补充说明（可选）

根据错误找到了 LiteLoader\src\init.js 第三十七行，然后找到了
```const qqnt_application_content = fs.readdirSync(`${qqnt_application_path}.asar`, "utf-8");```

发现全新安装的NtQQ文件夹 resources\app\versions 下只有一个zip压缩文件, 与要求的文件不符合
经过手动解压该压缩文件后恢复正常

可否添加判断是否先解压此zip再继续执行 ? （这个问题貌似是在 [Commit](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/2c3a826a0afdb5f58f86a80f6037c58918a5acf7) 引入的）

**Comment by HanaKDev** [comment]
本地清朝版本，更新后喜炸.gif

**Comment by mo-jinran** [comment]
有些像是QQNT没有正确安装完毕，正常全新安装的QQNT会自动解压这zip文件

**Comment by HanaKDev** [comment]
好的, 感谢你的提醒
经过观察确实如你所言, QQ安装程序会自动解压这个zip文件
因为之前我直接解压安装程序的时候, 拿到之后直接运行NtQQ+LiteLoader没有出现异常（疏忽了）
