### ISSUE TITLE
[Bug]: Issue 模板内“在 Windows 下显示终端日志”方式过时

### ISSUE THREAD

**Issue by RawDiamondMC** [LiteLoaderQQNT/LiteLoaderQQNT#372]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 问题

Issue 模板内“在 Windows 下显示终端日志”没提到要加上--enable-loggin参数。

**Comment by RawDiamondMC** [comment]
实测9.9.12-26466 (64位)就不能用这个方式获取输出了

**Comment by adproqwq** [comment]
加上--enable-logging标志，文档里写了

**Comment by RawDiamondMC** [comment]
> 加上--enable-logging标志，文档里写了

Issue 模板也得更新了...
