### ISSUE TITLE
[Bug]: QQ打开异常

### ISSUE THREAD

**Issue by SZC-CL** [LiteLoaderQQNT/LiteLoaderQQNT#376]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.7-21217-da00ceb5

### LiteLoaderQQNT 版本 （或 Commit Id）

1.1.2

### 运行环境

Windows

### 重现步骤

电脑自动重启后出现

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

<img width="272" alt="Snipaste_2024-08-07_15-19-27" src="https://github.com/user-attachments/assets/800c55fd-e3b9-48d2-9614-92262f8168c6">

### 日志记录

<img width="721" alt="Snipaste_2024-08-07_15-20-48" src="https://github.com/user-attachments/assets/72ac7fb8-e179-4ae5-8012-fa7de2b658a6">

**Comment by mo-jinran** [comment]
更新到1.2.1看是否修复

**Comment by SZC-CL** [comment]
> 更新到1.2.1看是否修复

<img width="240" alt="Snipaste_2024-08-22_20-27-03" src="https://github.com/user-attachments/assets/72634803-c1bb-4df8-9649-7e5717217861">
更新后成这样了

**Comment by mo-jinran** [comment]
你的qq版本太老了，需要更新
