### ISSUE TITLE
[Bug]: 数据目录不支持 Scoop 的 persist？

### ISSUE THREAD

**Issue by wordpure** [LiteLoaderQQNT/LiteLoaderQQNT#381]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-26909

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.0

### 运行环境

Windows

### 重现步骤

1. 在 QQNT 中使用 [Scoop](https://github.com/wordpure/scoop-air/blob/main/bucket/LiteLoaderQQNT.json) 中持久化了 data、plugins 目录的 LiteLoaderQQNT

	![图片](https://github.com/user-attachments/assets/4c987f7c-094c-4176-881d-3f2a20980a32)

2. 使用 LiteLoaderQQNT 安装插件轻量工具箱
3. 重启QQ后打开插件管理页面

### 期望的结果是什么？

轻量工具箱可以正常加载

### 实际的结果是什么？

轻量工具箱显示加载错误

![图片](https://github.com/user-attachments/assets/71d1b6fd-9a9b-4518-aecf-77c900f69281)

### 日志记录

```pwsh
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: 轻量工具箱
[LiteLoader] Found 1 plugins, start loading plugins.
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82968)
    at WebContents.emit (node:events:519:28)
++++++registerSimMojoCallback+++++,
create callbak source success
[18856:0809/234924.775:INFO:CONSOLE(0)] "[2024-08-09 23:49:24.776] [ERROR] [QLogger] [message/AioTimestampService] [clearMsgListTimestamp]newMsgList is undefined", source: D:\Scoop\apps\QQNT\current\resources\app\versions\9.9.15-26909\application\renderer\73347.js (0)
[18856:0809/234925.305:INFO:CONSOLE(0)] "[2024-08-09 23:49:25.304] [ERROR] [QLogger] [message/AioTimestampService] [clearMsgListTimestamp]newMsgList is undefined", source: D:\Scoop\apps\QQNT\current\resources\app\versions\9.9.15-26909\application\renderer\73347.js (0)
23:49:28.068 > [hot update]

------------ app 启动分界线 ------------

23:49:28.134 > [hot update] hotUpdateApi checkHasMultipleQQ:  false
23:49:28.170 > [hot update] hotUpdateApi clearOldVersions start
23:49:28.178 > [hot update] hotUpdateApi clear curVersionZip is: D:\Scoop\apps\QQNT\current\resources\app\versions\9.9.15-26909.zip
23:49:28.185 > [hot update] hotUpdateApi curVersionZip isExist: false
23:49:28.269 > [hot update] {
  "baseVersion": "9.9.15-26909",
  "curVersion": "9.9.15-26909",
  "prevVersion": "",
  "onErrorVersions": [],
  "buildId": "26909",
  "unzipRetryCount": 0
}
23:49:28.333 > [hot update] ----- startUpdate -----
23:49:28.360 > [hot update] hotUpdateApi checkHasMultipleQQ:  false
23:49:28.370 > [hot update] hotUpdateApi start check  9.9.15-26909  IsOnErrorVersion
23:49:28.385 > [hot update] hotUpdateApi checkIsOnErrorVersion result: false
23:49:28.401 > [hot update] [startUpdate] 无需更新
```

### 补充说明（可选）

上述问题仅在 scoop 持久化了 data、plugins 目录时出现，如果我在 manifest 中移除它们的 persist 后重新安装，或者把目录的符号链接去掉，安装的插件就能正常加载。

请问是不支持符号链接，只能像下面这个 [manifest](https://github.com/okibcn/ScoopMaster/blob/master/bucket/LiteLoaderQQNT.json) 这样通过环境变量来持久化数据目录吗？

![图片](https://github.com/user-attachments/assets/608e11d4-50e5-4582-81aa-dfc2cabedab7)

**Comment by mo-jinran** [comment]
目前是这样，但是最新的commits中已支持

**Comment by wordpure** [comment]
感谢大佬🌹
我先改用环境变量，等后续新版本出来再切换回软链接

**Comment by wordpure** [comment]
试了下环境变量，发现 QQNT 关掉重启之后，有时会忽略 LITELOADERQQNT_PROFILE 指定的路径，直接使用 LiteLoaderQQNT 的安装目录作为存储路径，要重启资源管理器才会用回环境变量里的路径😂
