### ISSUE TITLE
A javascript error occurred in the main process...LiteLoaderQQNT插件缺少依赖：euphony

### ISSUE THREAD

**Issue by COLOUREDGLAZES** [LiteLoaderQQNT/LiteLoaderQQNT#386]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15_240808_x64_01

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

安装完LiteLoaderQQNT重启电脑之后

### 期望的结果是什么？

正常启动QQNT

### 实际的结果是什么？

![屏幕截图 2024-08-13 042303](https://github.com/user-attachments/assets/16c8a7d6-5b9e-4bc7-973e-555ef3d8ce23)
![屏幕截图 2024-08-13 022237](https://github.com/user-attachments/assets/1522e1da-050b-4d53-aeaa-d1d4a2a7a108)

### 日志记录

![屏幕截图 2024-08-13 043236](https://github.com/user-attachments/assets/7f14c8e8-7c60-4db9-a3de-46e74bb908fd)

### 补充说明（可选）

重新安装完LiteLoaderQQNT可以正常启动，一旦重启电脑就会出现上述结果。

**Comment by HeJinDing-aipiao** [comment]
我安装完1.2.1后也会这样缺少依赖,回退版本之后也无法启动

**Comment by mo-jinran** [comment]
无效的issue，请根据官网安装，你的qq版本太老了

**Comment by HeJinDing-aipiao** [comment]
官网安装的最新版QQ_9.9.15_240808版本安装1.2.1liteloader仍然会出现问题,回退到1.2.0则恢复正常

**Comment by mo-jinran** [comment]
仅最低支持25765版本

**Comment by HeJinDing-aipiao** [comment]
9.9.15-26909也会出此问题

**Comment by mo-jinran** [comment]
根据提示你需要正确安装 `euphony` 插件，插件问题而非框架问题将删除issue
