### ISSUE TITLE
[Bug]: 安装最新版LLQQNT后，部分插件的index.js/ts路径错误

### ISSUE THREAD

**Issue by minecraft4668** [LiteLoaderQQNT/LiteLoaderQQNT#389]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-26909

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

找manifest.json的inject元素中路径与实际路径不相符的插件并按照正常步骤安装（如list-viewer）
这些插件有些的index是用ts写的，所以即使更改到正确的路径，他们的格式也是错误的
（也有可能是插件作者的问题？）

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

报错（无法找到文件路径，实际文件不存在）

### 日志记录

![image](https://github.com/user-attachments/assets/8c00fc71-bf43-4630-85a5-e5a30600450c)

### 补充说明（可选）

这些插件有些的index是用ts写的，所以即使更改到正确的路径，他们的格式也是错误的
（也有可能是插件作者的问题？）

**Comment by adproqwq** [comment]
用Release包，用源码就会出现这个问题。用ts写的插件仓库readme基本都有说明用发行版（即Release）包去使用。

**Comment by minecraft4668** [comment]
使用Release包确实解决了问题，麻烦大佬了
