### ISSUE TITLE
[Question]我在安装LiteLoaderQQNT后CPU占用异常

### ISSUE THREAD

**Issue by CreeperAWA** [LiteLoaderQQNT/LiteLoaderQQNT#390]
如题，我使用最新版QQNT和LiteLoaderQQNT后启动QQNT占用异常，并且QQNT非常卡顿，但是功能一切正常，但看没其他人提issue，这大概率应该是我的问题
我也尝试过换一台电脑安装，我的服务器因需要llonebot插件，我同样尝试过在我的服务器（Windows系统）上安装，出现同样的问题
希望能有大佬帮忙解决，如需更多信息我也可以提供，感谢！

**Comment by ShiinaRinne** [comment]
我更新至最新版后也碰见了这个问题, 14900k, 单个qq常驻能吃10%~20%, 也非常卡. 
顺带, 以前的笔记本是天选2 r75800h, 低版本 qqnt 挂后台也吃这么多, 6月中换这个新电脑后倒是没出现这个问题

于是我将 qq 回退至了低版本, 现在甚至都打不开了hhh, 即使再降级 liteloader 也没法解决, 正在找群友支援中.jpg
![image](https://github.com/user-attachments/assets/309fc65a-d9b2-486b-ab00-e8040158a524)

**Comment by CreeperAWA** [comment]
> 我更新至最新版后也碰见了这个问题, 14900k, 单个qq常驻能吃10%~20%, 也非常卡. 
> 顺带, 以前的笔记本是天选2 r75800h, 低版本 qqnt 挂后台也吃这么多, 6月中换这个新电脑后倒是没出现这个问题
> 
> 于是我将 qq 回退至了低版本, 现在甚至都打不开了hhh, 即使再降级 liteloader 也没法解决, 正在找群友支援中.jpg
> ![image](https://github.com/user-attachments/assets/309fc65a-d9b2-486b-ab00-e8040158a524)
> 补充, 这时的报错是在寻找一个不存在的 `preload.js` 文件, 在修改 `index.js` 后出现. 
> 调试之后发现 4 个 `preload.js` 成功被写入 application 文件夹, 但后续检测时却没找到, 疑似被删掉了
> ![image](https://github.com/user-attachments/assets/7904ba0e-bcd8-4c5c-90c3-5206ba9388ee)
> 
> 

我可以解决你这个问题，但我解决不了我自己的问题（

**Comment by ShiinaRinne** [comment]
现在就低版本用着, 后悔手贱更新了, 果然能跑就不该动的
![5e896f15a9ffd972cdbfda931e2f744d](https://github.com/user-attachments/assets/b98ae6d1-2123-4264-ba01-8bfae81c5e08)

**Comment by CreeperAWA** [comment]
> 现在就低版本用着, 后悔手贱更新了, 果然能跑就不该动的 ![5e896f15a9ffd972cdbfda931e2f744d](https://private-user-images.githubusercontent.com/45081750/358878164-b98ae6d1-2123-4264-ba01-8bfae81c5e08.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NDcyNjcsIm5iZiI6MTcyMzk0Njk2NywicGF0aCI6Ii80NTA4MTc1MC8zNTg4NzgxNjQtYjk4YWU2ZDEtMjEyMy00MjY0LWJhMDEtOGJmYWU4MWM1ZTA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDAyMDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxNzdiMmU2MjJlMmVhOGUyOTUwOTE1NmZiOTExYmQ4NDNhNTY2MzY4MDQxMmI1M2E4NmM2ZmZiNGVkNTM0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ydrp4KUFWfncqfHVMiu7-9dEW-UvB49DrVrbT-sfImo)

我这里正常的最后一个版本是QQNT 9.9.10-24108 LiteLoader 1.1.1

**Comment by ShiinaRinne** [comment]
试了下仍然会有相同问题, 估计是由于其他奇奇怪怪的 bug 吧
![image](https://github.com/user-attachments/assets/029ec263-4bd7-441a-ad11-64c6f2a580fa)

**Comment by CreeperAWA** [comment]
总之都蛮神奇的(

**Comment by mo-jinran** [comment]
试试看1.2.2版本？改了preload加载方式或许能解决

**Comment by CreeperAWA** [comment]
我之前没有删过插件测试，不清楚，但是这次删除了插件加载确实就正常了，可能还是有插件有问题。
改了加载方式以后因为异常插件的原因，还是有些卡顿和极高的CPU占用，不过比之前流畅多了

**Comment by ShiinaRinne** [comment]
> 试试看1.2.2版本？改了preload加载方式或许能解决

感谢~可以正常使用了。
现在版本 `9.9.15-28327`

**Comment by CreeperAWA** [comment]
> > 试试看1.2.2版本？改了preload加载方式或许能解决
> 
> 感谢~可以正常使用了。 现在版本 `9.9.15-28327`

你以前或现在有没有装LLAPI啊，我今天最新版排查出来是LLAPI有问题

**Comment by EatHatsuneShallots** [comment]
> 你以前或现在有没有装LLAPI啊

话说LLAPI还在更新吗，听说他删库了

**Comment by CreeperAWA** [comment]
> > 你以前或现在有没有装LLAPI啊
> 
> 话说LLAPI还在更新吗，听说他删库了

似乎没删库，但是确实被从主页除名了

**Comment by ShiinaRinne** [comment]
> > > 试试看1.2.2版本？改了preload加载方式或许能解决
> > 
> > 
> > 感谢~可以正常使用了。 现在版本 `9.9.15-28327`
> 
> 你以前或现在有没有装LLAPI啊，我今天最新版排查出来是LLAPI有问题

以前确实是装过的，忘记是因为哪个插件需要 LLAPI 作为前置

**Comment by CreeperAWA** [comment]
> > > > 试试看1.2.2版本？改了preload加载方式或许能解决
> > > 
> > > 
> > > 感谢~可以正常使用了。 现在版本 `9.9.15-28327`
> > 
> > 你以前或现在有没有装LLAPI啊，我今天最新版排查出来是LLAPI有问题
> 
> 以前确实是装过的，忘记是因为哪个插件需要 LLAPI 作为前置

我也忘了是哪个要LLAPI我才装的 可能那个插件已经删库了 反正现在删了正常了，似乎也没哪个插件罢工
那这个问题解决了我就关issue了
