### ISSUE TITLE
[Bug]: QQ 9.9.15-27206无法启动

### ISSUE THREAD

**Issue by YuLinLoli** [LiteLoaderQQNT/LiteLoaderQQNT#396]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-27206

### LiteLoaderQQNT 版本 （或 Commit Id）

LiteLoaderQQNT 1.2.1

### 运行环境

Windows

### 重现步骤

QQ更新到9.9.15-27206后重新安装LiteLoaderQQNT无法启动

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

无法启动

### 日志记录

![屏幕截图 2024-08-20 104946](https://github.com/user-attachments/assets/d21f803f-9e92-4d2f-8b86-7a64b1c8161d)

**Comment by linlin4112** [comment]
我也遇到了这个问题
现在的解决办法是，临时回退到***1.2.0***版本的LiteLoaderQQNT。
这是我目前测试出来最好的办法。

**Comment by bootlegseahorse** [comment]
> 我也遇到了这个问题 现在的解决办法是，临时回退到_**1.2.0**_版本的LiteLoaderQQNT。 这是我目前测试出来最好的办法。

我这里任何版本LiteLoader都不管用

我已退回QQNT 9.9.12

**Comment by Blankdsad** [comment]
> ### 请确保您已阅读以上注意事项，并勾选下方的确认框。
> * [x]  我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
> * [x]  我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> * [x]  我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
> * [x]  我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。
> 
> ### QQNT 版本
> 9.9.15-27206
> 
> ### LiteLoaderQQNT 版本 （或 Commit Id）
> LiteLoaderQQNT 1.2.1
> 
> ### 运行环境
> Windows
> 
> ### 重现步骤
> QQ更新到9.9.15-27206后重新安装LiteLoaderQQNT无法启动
> 
> ### 期望的结果是什么？
> 正常启动
> 
> ### 实际的结果是什么？
> 无法启动
> 
> ### 日志记录
> ![屏幕截图 2024-08-20 104946](https://private-user-images.githubusercontent.com/95580090/359320365-d21f803f-9e92-4d2f-8b86-7a64b1c8161d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODM4MzgsIm5iZiI6MTcyNDM4MzUzOCwicGF0aCI6Ii85NTU4MDA5MC8zNTkzMjAzNjUtZDIxZjgwM2YtOWU5Mi00ZDJmLThiODYtN2E2NGIxYzgxNjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAzMjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MmI5ODY3NmEyMDgyNzIyYTEzNDE1YmE0YWNkNGU2MDVlZjBlMDNkZjQzNWFiMWM1YmQ4ZTgzZWM0ZmVlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PvBnyZX9Fe6Xux-t8ieUglcVcLDfFwu80KQt5PO-R78)
> 
> ### 补充说明（可选）
> _No response_
![image](https://github.com/user-attachments/assets/7f6a7b19-9182-482e-b14e-4c14790b2789)
升级之后，重装 一直失败

**Comment by Beransnow** [comment]
+1

**Comment by liyuxiang-lyx** [comment]
QQNT9.9.15-27597也是同一个问题
但是把index.js里的1和2行调换就可以正常启动了

**Comment by mo-jinran** [comment]
尝试安装QQNT和LiteLoaderQQNT的最新版？
