### ISSUE TITLE
[Feat]: 针对于 （是否将撤回消息存入数据库功能拓展）的一些期望建议

### ISSUE THREAD

**Issue by Yhcc7** [LiteLoaderQQNT/LiteLoaderQQNT#398]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

期望提供自定义配置存入的数据库的相关功能，并能提供技术上简单的使用文档（数据库类型，存储表），避免使用者担心数据泄露的风险（如泄露则该功能使用者自行负责），如后续用户体积量较大节省提供服务方相关资源

**Comment by xiyuesaves** [comment]
issue 提错地方了，这是插件加载器，你应该去对应的插件那里提。
