### ISSUE TITLE
[Bug]: 生成的preload*.js使Appimage打包的QQNT无法使用

### ISSUE THREAD

**Issue by Jackhr-arch** [LiteLoaderQQNT/LiteLoaderQQNT#401]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

1.2.1

### LiteLoaderQQNT 版本 （或 Commit Id）

bd5a9fb16ecfd25adc9d2b760f943582dbb7f531

### 运行环境

Linux

### 重现步骤

参考 [LiteLoaderQQNT_Install的AppImage打包过程](https://github.com/Mzdyl/LiteLoaderQQNT_Install/blob/main/.github/workflows/appimage.yml)打包AppImage文件，启动AppImage文件后提示：
![image](https://github.com/user-attachments/assets/e6bc51a1-5ab1-4275-bc04-25242fb19bee)

而appimage通过fuse加载，每次文件挂载点会改变，对其挂载文件夹的修改不会保存。这导致每次启动QQ都会弹出此窗口。

### 期望的结果是什么？

期望能在安装时通过某种方式提前生成这些文件，方便打包

### 实际的结果是什么？

我未在仓库内找到与preload*.js相关的文件，因此推测其为运行时生成的

### 日志记录

```
version_config_filename :/home/jackhr/.config/QQ/versions/config.json
app_package_filename :/tmp/.mount_QQ.AppLZzMST/resources/app/package.json
config_build_id :27254
config_base_version :3.2.12-27254
config_current_version :3.2.12-27254
app_build_version :27254
version_config_filename :/home/jackhr/.config/QQ/versions/config.json
app_package_filename :/tmp/.mount_QQ.AppLZzMST/resources/app/package.json
version_config_filename :/home/jackhr/.config/QQ/versions/config.json
app_package_filename :/tmp/.mount_QQ.AppLZzMST/resources/app/package.json
config_build_id :27254
config_base_version :3.2.12-27254
config_current_version :3.2.12-27254
app_build_version :27254
config_build_id :27254
config_base_version :3.2.12-27254
config_current_version :3.2.12-27254
app_build_version :27254
[preload] succeeded. /tmp/.mount_QQ.AppLZzMST/resources/app/major.node
[preload] succeeded. /tmp/.mount_QQ.AppLZzMST/resources/app/major.node
```

### 补充说明（可选）

在移除配置文件夹(LiteLoader)再次启动时，除开此报错外另有`No such dir: plugins`，但与主题无关且并非错误。留在这里仅作记录

**Comment by shmilee** [comment]
几个 preload*.js 文件是第一次运行生成的。（按官方文档的意思，不同版本 LiteLoaderQQNT可能会有些差别）
所以一种方法是，appimage打包时，选定一个版本的LiteLoaderQQNT 和 qq 一起打包，同时放入几个 preload*.js，以及qq启动脚本处理一下丢失的 plugins 目录， 让框架和qq都一步到位，开箱即用。
用户的插件和数据放在家目录，用户启动qq后，只需要选自己用的插件就好了。

你可以参考以下我的一些arch打包脚本，https://github.com/shmilee/scripts/tree/master/linuxqq

**Comment by mo-jinran** [comment]
目前1.2.2版本修改了preload.js的加载方式，目前不再需要运行时修改本体目录
