### ISSUE TITLE
[Hope]: 后台被撤回的图片&视频无法拦截，是QQ的限制吗？

### ISSUE THREAD

**Issue by jm3720343** [LiteLoaderQQNT/LiteLoaderQQNT#404]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

![QQ截图20240828133411](https://github.com/user-attachments/assets/e14446e0-6ede-48ea-8d36-9ce7cab8fe22)
![QQ截图20240828133403](https://github.com/user-attachments/assets/d3e06fb4-41dd-4b4b-bed0-bba4847b07cd)
如题，有什么办法可以解决

**Comment by adproqwq** [comment]
要么是你没配置rkey，要么就是你还没下载到图，对方就撤回了。
另外，这不是框架的问题，请不要在框架仓库提issue

**Comment by jm3720343** [comment]
> 要么是你没配置rkey，要么就是你还没下载到图，对方就撤回了。 另外，这不是框架的问题，请不要在框架仓库提issue

抱歉……

**Comment by David-xian66** [comment]
> > 要么是你没配置rkey，要么就是你还没下载到图，对方就撤回了。 另外，这不是框架的问题，请不要在框架仓库提issue
> 
> 抱歉……

你可以close了
