### ISSUE TITLE
安装未生效

### ISSUE THREAD

**Issue by bgvioletsky** [LiteLoaderQQNT/LiteLoaderQQNT#405]
不知道是我安装出现问题还是其他安装路径与修改如图

![系统](https://github.com/user-attachments/assets/6207da24-6b41-4c4c-bbb0-17b61294338d)

index.js修改如图

![image](https://github.com/user-attachments/assets/62f37398-00f9-490b-8781-0ba51734c15c)

安装文件夹如图

![image](https://github.com/user-attachments/assets/e9e9e3ee-0e17-4352-9501-9097adecfbc3)
但是打开QQ设置并未发现插件如图

![image](https://github.com/user-attachments/assets/757adb4a-23d4-4233-a35b-1338beb1bb52)

QQ版本
![QQ_1724841534869](https://github.com/user-attachments/assets/0c68c700-05a2-46c8-9397-af19dc651622)

大佬麻烦您了

**Comment by marcozyj** [comment]
所以你解决了么

**Comment by bgvioletsky** [comment]
没有

**Comment by mo-jinran** [comment]
根据官网教程安装1.2.2版本
