### ISSUE TITLE
[Bug]: 无法自动生成plugins文件夹

### ISSUE THREAD

**Issue by O5-7** [LiteLoaderQQNT/LiteLoaderQQNT#406]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-27333 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

通过克隆仓库，修改js脚本，使用dll覆盖完成安装
启动时报错，提示仓库文件夹下不存在plugins文件夹
仓库文件夹有修改权限

### 期望的结果是什么？

自动创建plugins文件夹，启动后没有报错

### 实际的结果是什么？

启动时报错，提示仓库文件夹下不存在plugins文件夹
自己建立一个空文件夹后正常启动

**Comment by genghaosan** [comment]
问题不是很大自己手动添加也能用哈哈

**Comment by mo-jinran** [comment]
1.2.2版本修了
