### ISSUE TITLE
[Bug]: Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by wordgao** [LiteLoaderQQNT/LiteLoaderQQNT#408]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

3.2.12-27597

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Linux

### 重现步骤

![截图 2024-09-06 01-27-58](https://github.com/user-attachments/assets/75200413-65ad-43fe-8fb3-9c91a0a2f436)

### 期望的结果是什么？

linux版本今日白天正常，晚上不知道是liteloader自动升级，还是其他原因之后就无法启动，并出现上面的校验错误提示了。

### 实际的结果是什么？

无法启动

**Comment by mo-jinran** [comment]
更新1.2.2版本，并查看官网新安装教程
