### ISSUE TITLE
[Bug]: 启动qq失败

### ISSUE THREAD

**Issue by Sakura-cool** [LiteLoaderQQNT/LiteLoaderQQNT#411]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-27597 (64位)

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

更新补丁后QQ启动失败(之前可能有其他插件有问题)
在插件列表内安装并更新了3个软件(忘了哪几个),然后列表出现问题,同时更新了该软件补丁,显示插件列表不可用,重启QQ后,QQ报错
然后通过RevokeMsgPatcher.exe移除补丁后,QQ恢复正常,但是插件同时全部移除,重新通过RevokeMsgPatcher.exe打上补丁后,QQ呈现不可用状态

### 期望的结果是什么？

列表更新,防撤回正常运行,QQ正常运行

### 实际的结果是什么？

QQ启动报错
<img width="719" alt="Snipaste_2024-09-10_18-21-38" src="https://github.com/user-attachments/assets/01cf2f06-0fc2-4cb8-b86e-88743fee1acc">
<img width="879" alt="Snipaste_2024-09-10_18-23-47" src="https://github.com/user-attachments/assets/73a1f6ba-5856-461e-95e1-4a874bbe2edf">

**Comment by Sakura-cool** [comment]
使用的该项目打的补丁,我不知道剔除某个异常进行测试进行操作,故同时附上该项目地址
https://github.com/huiyadanli/RevokeMsgPatcher/tree/1.8

**Comment by mo-jinran** [comment]
这个项目目前没更新，建议先根据官网教程安装1.2.2版本
