### ISSUE TITLE
[Bug]: 无法用于QQNT 9.9.15-28060，需要修改的index.js被移除

### ISSUE THREAD

**Issue by abbaccadd0** [LiteLoaderQQNT/LiteLoaderQQNT#417]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-28060

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

安装QQNT 9.9.15-28060后，QQNT\resources\app\app_launcher下index.js文件被移除
QQNT\versions\9.9.15-28060\resources\app\app_launcher下存在index.js，但是QQ主程序修补并修改index.js后没有任何作用

### 期望的结果是什么？

按照安装说明正常安装运行

### 实际的结果是什么？

无法按照原有方式安装

### 补充说明（可选）

安装包：
[https://dldir1.qq.com/qqfile/qq/QQNT/ad1a575f/QQ9.9.15.28060_x64_QQinner.exe](https://dldir1.qq.com/qqfile/qq/QQNT/ad1a575f/QQ9.9.15.28060_x64_QQinner.exe)

**Comment by mo-jinran** [comment]
框架已适配，但需要简单一点的使用方式

**Comment by Starrain08** [comment]
> 框架已适配，但需要简单一点的使用方式

目前有新的手动安装方式嘛，现有安装方式和对QQ本体修补的都失效
![image](https://github.com/user-attachments/assets/f97c1047-5588-41de-8fa2-c44c484b240a)
这是使用修补程序对qq修补时的截图

**Comment by youlan2333** [comment]
+1👀

**Comment by PTALTS-LK** [comment]
linux 端 3.2.12-28060 似乎也不支持

**Comment by Ahahahala** [comment]
我也遇到了同样的问题

**Comment by singularity2000** [comment]
我也遇到了同样的问题，请大佬尽快更新

**Comment by Joker2Yue** [comment]
可以回退到QQ9.9.15.27597，下载链接：
32位：https://dldir1.qq.com/qqfile/qq/QQNT/d2c72806/QQ9.9.15.27597_x86.exe
64位：https://dldir1.qq.com/qqfile/qq/QQNT/b07cb1a5/QQ9.9.15.27597_x64.exe

**Comment by qwerty-a11y** [comment]
原先的修补程序可以修补version\版本号下的QQNT.dll，那个目录下也能找到对应的index.js，但经过测试修改后并不生效

**Comment by mo-jinran** [comment]
clone最新的项目源码，并绕过文件检测
使用最新的dll放到QQ.exe目录，或使用老版本exe选择QQNT.dll修补
在目录 `versions\版本号\resources\app\app_launcher` 创建 `llqqnt.js` 文件
写入 ```require(String.raw`LiteLoaderQQNT目录路径`)```
再修改 `versions\版本号\resources\app\package.json` 文件 `main` 键值
写入 `./app_launcher/llqqnt.js`
启动QQ即可使用，需确保QQ安装目录有读写权限

**Comment by Error1015** [comment]
> clone最新的项目源码，并绕过文件检测 使用最新的dll放到QQ.exe目录，或使用老版本exe选择QQNT.dll修补 在目录 `versions\版本号\resources\app\app_launcher` 创建 `llqqnt.js` 文件 写入 `` require(String.raw`LiteLoaderQQNT目录路径`) `` 再修改 `versions\版本号\resources\app\package.json` 文件 `main` 键值 写入 `./app_launcher/llqqnt.js` 启动QQ即可使用，需确保QQ安装目录有读写权限

跟着做了 启动qq提示文件损坏 请重新安装QQ 版本号9.9.15-28131

**Comment by ieew** [comment]
> > clone最新的项目源码，并绕过文件检测 使用最新的dll放到QQ.exe目录，或使用老版本exe选择QQNT.dll修补 在目录 `versions\版本号\resources\app\app_launcher` 创建 `llqqnt.js` 文件 写入 `` require(String.raw`LiteLoaderQQNT目录路径`) `` 再修改 `versions\版本号\resources\app\package.json` 文件 `main` 键值 写入 `./app_launcher/llqqnt.js` 启动QQ即可使用，需确保QQ安装目录有读写权限
> 
> Linux 上无须修补,剩下的按照此方法可以启动, ~测试 Flatpak 可行~ 启动后无画面,命令行启动后卡住, ![image](https://private-user-images.githubusercontent.com/17796830/369429387-bcee95d8-735d-4a1f-93d1-5c964efcd5f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDc5MjYsIm5iZiI6MTcyNjg0NzYyNiwicGF0aCI6Ii8xNzc5NjgzMC8zNjk0MjkzODctYmNlZTk1ZDgtNzM1ZC00YTFmLTkzZDEtNWM5NjRlZmNkNWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE1NTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OTgxZTQ3OGJjZGZkOTQyNDZhNmRiMWIzOWZjYWQ4NWJmNDc4YzliZTVlYjJjZmE5NTUyMzM0YTVkN2UwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TdIzpkgcj-dgRuzs21jjbpytv0C_t8wC5PvQ7oWiC4E)

在 linux 上同时把 package.json 文件的权限改成 646 之后可以通过在终端运行 ./qq 的方式启动 qq (我在 archlinux 上不能通过已安装的快捷方式启动)

**Comment by speeed001** [comment]
> > 2. 使用最新的 `.dll` 放到 `QQ.exe` 目录，或使用老版本 `.exe` 选择 `QQNT.dll` 修补
> 
> 这一步没有明白😕
> 

https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases

**Comment by ieew** [comment]
> > 克隆最新的项目源码，并绕过文件检测最新的dll放入QQ.exe目录，或使用老版本exe选择QQNT.dll修复在目录`versions\版本号\resources\app\app_launcher`创建`llqqnt.js`文件写入使用`` require(String.raw`LiteLoaderQQNT目录路径`) ``再修改`versions\版本号\resources\app\package.json`文件`main`键值写入`./app_launcher/llqqnt.js`启动QQ即可使用，需确保QQ安装目录有读写权限
> 
> Linux上修复、剩余的可以按照此方法启动，~测试 Flatpak 可行~ 启动后无画面,命令行启动后卡住, ![图像](https://private-user-images.githubusercontent.com/17796830/369429387-bcee95d8-735d-4a1f-93d1-5c964efcd5f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5ODE3ODIsIm5iZiI6MTcyNjk4MTQ4MiwicGF0aCI6Ii8xNzc5NjgzMC8zNjk0MjkzODctYmNlZTk1ZDgtNzM1ZC00YTFmLTkzZDEtNWM5NjRlZmNkNWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIyVDA1MDQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjFjMWUxYzQ5ZGQzNGQxYTI4NGNmN2NhZmNjM2RhY2Q4ZTY5NTYwZTEyNmIyZDk5MDZhZjE4ODVkNGU2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vbgX5Je1nH_JoLaVUjjFw7xH4lHMZYxpVnWQwJrVoFw)

@chisaato 

刚刚研究了一下，我有一个新的解决方案，用这个方法可以让 `qq` 能够通过 `flatpak run com.qq.QQ` 来运行。
1. 修改 `flatpak` 中 `com.qq.QQ` 的 `metadata` 元数据，把容器外的 `resources\app\package.json` 文件实际位置映射进容器内。例如实际位置在：`/var/lib/flatpak/app/com.qq.QQ/x86_64/stable/xxxxxxx/files/extra/QQ/resources/app/package.json` 那就在 `metadata` 中修改 `filesystems` 的值，在值末尾将实际路径添加进去
2. 修改 `LiteLoaderQQNT` 的源码，把 [这行代码](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/blob/main/src/init.js#L88C72-L88C76) 改成 `const package_path = "/var/lib/flatpak/app/com.qq.QQ/x86_64/stable/xxxxxxx/files/extra/QQ/resources/app/package.json";`
3. 剩余的其他步骤直接按下面操作↓
> clone最新的项目源码，并绕过文件检测
> 在目录 versions\版本号\resources\app\app_launcher 创建 llqqnt.js 文件
> 写入 require(String.raw`LiteLoaderQQNT目录路径`)
> 再修改 versions\版本号\resources\app\package.json 文件 main 键值
> 写入 ./app_launcher/llqqnt.js
> 启动QQ即可使用

**Comment by FinaFina233** [comment]
> clone最新的项目源码，并绕过文件检测 使用最新的dll放到QQ.exe目录，或使用老版本exe选择QQNT.dll修补 在目录 `versions\版本号\resources\app\app_launcher` 创建 `llqqnt.js` 文件 写入 `` require(String.raw`LiteLoaderQQNT目录路径`) `` 再修改 `versions\版本号\resources\app\package.json` 文件 `main` 键值 写入 `./app_launcher/llqqnt.js` 启动QQ即可使用，需确保QQ安装目录有读写权限
package.json的 main 键值会在启动QQ.exe时自动恢复至默认，设置为只读后启动QQ.exe无反应

**Comment by Dragon1573** [comment]
> https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases

已经如图所示完成了 `QQ.exe` 的修补

![image](https://github.com/user-attachments/assets/c88b7269-30d7-44bb-983d-ca6ce9cb520d)

修补后启动 `QQ.exe` 仍提示找不到 Module

**Comment by mo-jinran** [comment]
> clone最新的项目源码，并绕过文件检测 使用最新的dll放到QQ.exe目录，或使用老版本exe选择QQNT.dll修补 在目录 `versions\版本号\resources\app\app_launcher` 创建 `llqqnt.js` 文件 写入 `` require(String.raw`LiteLoaderQQNT目录路径`) `` 再修改 `versions\版本号\resources\app\package.json` 文件 `main` 键值 写入 `./app_launcher/llqqnt.js` 启动QQ即可使用，需确保QQ安装目录有读写权限

在最新的 5bf0e63c755afe25556b76d963b2cd342fc07571 提交中，已不再需要运行时修改 `package.json` 文件

**Comment by mo-jinran** [comment]
在最新的 73097c1d51ecc0b3ce3336bdee1c0bfb171ecec1 提交中，已不再需要运行时生成 preload.js 文件

目前最新的安装方法，最低兼容 25765 版本：
- 安装 QQNT 并下载最新项目源码 73097c1d51ecc0b3ce3336bdee1c0bfb171ecec1 放置在任意位置，并记住 LiteLoaderQQNT 的路径
- 在  `*/resources/app/app_launcher` 中创建任意名称的 `.js` 文件，并写入 ```require(String.raw`***`);``` （请将 `***` 修改成你的 LiteLoaderQQNT 路径）
- 修改 `*/resources/app/package.json` 文件中 `main` 的值为 `./app_launcher/*.js` （请将 `*.js` 修改成你刚在 app_launcher 中创建的文件名）
- 如果 `*/resources/app` 目录内存在 `versions` 文件夹，将 `*/LiteLoaderQQNT/src/preload.js` 文件复制到
  - `*/resources/app/versions/版本号/application/preload.js`
  - 否则直接将文件复制到 `*/resources/app/application/preload.js`
  - （默认没有 application 文件夹需自行创建）

**Comment by yamlling** [comment]
> 在最新的 [73097c1](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/73097c1d51ecc0b3ce3336bdee1c0bfb171ecec1) 提交中，已不再需要运行时生成 preload.js 文件
> 
> 目前最新的安装方法，最低兼容 25765 版本：
> 
> * 安装 QQNT 并下载最新项目源码 [73097c1](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/73097c1d51ecc0b3ce3336bdee1c0bfb171ecec1) 放置在任意位置，并记住 LiteLoaderQQNT 的路径
> * 在 中创建任意名称的 文件，并写入 （请将 修改成你的 LiteLoaderQQNT 路径）`*/resources/app/app_launcher``.js``` require(String.raw`***`); ```***`
> * 修改 文件中 的值为 （请将 修改成你刚在 app_launcher 中创建的文件名）`*/resources/app/package.json``main``./app_launcher/*.js``*.js`
> * 如果  目录内存在  文件夹，将  文件复制到`*/resources/app``versions``*/LiteLoaderQQNT/src/preload.js`
>   * `*/resources/app/versions/版本号/application/preload.js`
>   * 否则直接将文件复制到`*/resources/app/application/preload.js`
>   * （默认没有 application 文件夹需自行创建）

9.9.15-28327 以上方法无效 */resources/app/versions/下不存在文件夹
自行创建并复制preload.js之后也无效

**Comment by Soudayo114** [comment]
> > 在最新的 [73097c1](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/73097c1d51ecc0b3ce3336bdee1c0bfb171ecec1) 提交中，已不再需要运行时生成 preload.js 文件
> > 目前最新的安装方法，最低兼容 25765 版本：
> > 
> > * 安装 QQNT 并下载最新项目源码 [73097c1](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/commit/73097c1d51ecc0b3ce3336bdee1c0bfb171ecec1) 放置在任意位置，并记住 LiteLoaderQQNT 的路径
> > * 在 中创建任意名称的 文件，并写入 （请将 修改成你的 LiteLoaderQQNT 路径）`` */resources/app/app_launcher``.js``` require(String.raw ``***`` ); ```*** ``
> > * 修改 文件中 的值为 （请将 修改成你刚在 app_launcher 中创建的文件名）`` */resources/app/package.json``main``./app_launcher/*.js``*.js ``
> > * 如果  目录内存在  文件夹，将  文件复制到`` */resources/app``versions``*/LiteLoaderQQNT/src/preload.js ``
> >   
> >   * `*/resources/app/versions/版本号/application/preload.js`
> >   * 否则直接将文件复制到`*/resources/app/application/preload.js`
> >   * （默认没有 application 文件夹需自行创建）
> 
> 9.9.15-28327 以上方法无效 */resources/app/versions/下不存在文件夹 自行创建并复制preload.js之后也无效

不存在文件夹那就复制到
> */resources/app/application/preload.js

我自己9.9.15-28327是有效的
