### ISSUE TITLE
[Bug]: 异常高内存占用与收发消息延迟

### ISSUE THREAD

**Issue by Alan-William-Lee** [LiteLoaderQQNT/LiteLoaderQQNT#418]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15.27333

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

搭配使用“[背景插件](https://github.com/xh321/LiteLoaderQQNT-Background-Plugin/tree/master)”，并开启‘在线图片’后，QQ内存占用过高且消息延迟严重

### 期望的结果是什么？

流畅收发消息

### 实际的结果是什么？

暂不清楚是否仅为插件原因，关闭背景插件后仍会有这一问题，但没有那么严重

### 补充说明（可选）

概率在卡顿后被封号

**Comment by EatHatsuneShallots** [comment]
看一下封号原因

**Comment by Alan-William-Lee** [comment]
> 看一下封号原因

涉嫌进行业务违规操作
更新至1.2.2后卡顿问题有所优化，但是使用两天后被封号七天/(ㄒoㄒ)/~~
