### ISSUE TITLE
[Bug]: 1.2.1版本无法使用

### ISSUE THREAD

**Issue by AniaDaniel2** [LiteLoaderQQNT/LiteLoaderQQNT#419]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-27391

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

通过第三方安装的文件替换LiteLoaderQQNT版本后，尝试安装最新版本，然后报错了
![1726486775093](https://github.com/user-attachments/assets/8b44383d-76c8-4afe-af8c-89fd714780d0)

### 期望的结果是什么？

修复打不开的bug

### 实际的结果是什么？

打不开
![1726486775093](https://github.com/user-attachments/assets/b8c1bc33-7f0a-42b7-8e56-e523abd7a089)

**Comment by Magic989** [comment]
是的，QQ 更新后设置里面菜单没了

**Comment by BruceArc** [comment]
去更新list-viewer插件就行
https://github.com/ltxhhz/LL-plugin-list-viewer/releases/tag/v1.4.1
下载压缩包解压到报错提示的插件文件夹下

**Comment by mo-jinran** [comment]
1.2.1有问题那试试1.2.2吧

**Comment by latedreamdev** [comment]
1.2.2有问题那试试1.2.3吧(
