### ISSUE TITLE
[Bug]: 运行自动安装程序以及liteloader后首次启动QQNT无问题，安装插件后重启QQ报错

### ISSUE THREAD

**Issue by CN-CYF060810** [LiteLoaderQQNT/LiteLoaderQQNT#421]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-28131

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

![PixPin_2024-09-21_10-05-35](https://github.com/user-attachments/assets/f1e41886-292d-4e22-9450-d80cf3f5b06e)
QQNT安装在D盘内，使用自动安装程序全程默认安装位置后首次可正常使用并安装了如下插件
![PixPin_2024-09-21_10-08-30](https://github.com/user-attachments/assets/5e84d726-1e86-4e41-be19-2b4078173279)
关闭QQ程序重启时 或者是在QQ左下角菜单退出账号时会弹出报错窗口
![PixPin_2024-09-21_10-04-15](https://github.com/user-attachments/assets/509597e0-f9e6-4351-95fb-e3d5158b6340)
终端日志的内容如下
![111](https://github.com/user-attachments/assets/d6fbde00-d9e3-4fff-9c6e-8668158135b6)
再次重新运行自动安装liteloader程序，第一次可以正常启动，关闭QQ后重启状况同上

### 期望的结果是什么？

正常启动QQ，正常使用插件

### 实际的结果是什么？

无法启动QQNT

**Comment by CN-CYF060810** [comment]
我在浏览bug报告页时发现#411帖子也出现了同样的问题但未解决

**Comment by mo-jinran** [comment]
根据官网教程安装最新的1.2.2版本
