### ISSUE TITLE
[Bug]: QQNT18060/18131中导致QQ自带截图无法正常使用

### ISSUE THREAD

**Issue by LeoChen98** [LiteLoaderQQNT/LiteLoaderQQNT#423]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-18131（18060也有同样问题）

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.1

### 运行环境

Windows

### 重现步骤

* 正常安装启动
* 使用快捷键唤起QQ自带的截图工具

### 期望的结果是什么？

截图工具正常显示并工作

### 实际的结果是什么？

截图工具启动后加载覆盖层失败，框选功能和编辑功能都无法显示，但是可以通过鼠标盲选截图范围。

### 补充说明（可选）

在不安装LL的情况下截图工具是可以正常使用的，认为应该是LL和QQNT新版本截图工具不兼容导致

**Comment by LeoChen98** [comment]
![image](https://github.com/user-attachments/assets/7e12dc72-fc72-4537-b695-74f76a89f84b)

**Comment by LeoChen98** [comment]
从spy++中可以看到截图实际的窗体已经创建但是没有成功显示
![image](https://github.com/user-attachments/assets/a34e8ca9-d03e-488f-8f66-77041a48a696)

**Comment by sjx-github** [comment]
我这边截图贴图等功能倒是运转良好
![info](https://github.com/user-attachments/assets/a87bd947-72c0-43fb-8141-130ac06654b4)

**Comment by mo-jinran** [comment]
无法复现

**Comment by Starrain08** [comment]
> 无法复现

这个问题在28060以下的版本出现过，我当时还因为这个bug重装qq了，在重装完成后截屏恢复，但是在安装完ll后截屏出现异常，具体是截屏组件出现了，但是屏幕会整个灰掉或者显示黑色，这个bug在qq靠前的版本是大概率出现，小概率恢复，靠后的版本就一直这样，当时以为是QQbug，直到前几天更新QQ到28060然后再装ll，就发现这个bug消失了，推测是llhook的位置扩大了，把截图组件一起包括进去了

**Comment by mo-jinran** [comment]
新的1.2.2版本应该修复了此问题

**Comment by shibuyameltdown** [comment]
qq版本：9.9.16-28971
liteloader版本：1.2.2
截图还是会整个屏幕变成灰色![](https://p.sda1.dev/19/549ddb84fcf9ea6daf427dfb3271eca3/a0187b1f868cfab85dd6c4386639388e.png)
