### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fire-mirror** [LiteLoaderQQNT/LiteLoaderQQNT#426]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.15-28131

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.2

### 运行环境

Windows

### 重现步骤

按照官方网站写入require(String.raw`*`) 其中 * 为 LiteLoaderQQNT 的路径
![image](https://github.com/user-attachments/assets/040b382a-543f-4aad-8cbf-4aeec28fda4e)

### 期望的结果是什么？

![image](https://github.com/user-attachments/assets/c1888945-d181-45b0-a65f-7c37d2f9a664)

### 实际的结果是什么？

![image](https://github.com/user-attachments/assets/f65f7ef3-dc26-4a76-9671-ccc43fe2fd7b)

### 补充说明（可选）

写成：
require("*");   //  “*”LiteLoaderQQNT实际路径
后可以正常使用，所以，改下安装说明?

**Comment by FootClick** [comment]
为啥我改成require("");还是一样

**Comment by mo-jinran** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher/releases/tag/1.9
用安装器吧
