### ISSUE TITLE
[Hope]: 希望有能在指定时间段自动开启/关闭群禁言的功能

### ISSUE THREAD

**Issue by HoShiNo-Estrella6066** [LiteLoaderQQNT/LiteLoaderQQNT#436]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的功能，没有找到相同功能的ISSUE。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

我未能在网上找到拥有此功能且支持onebot协议的项目，
也没在插件商店中找到拥有这种功能的插件，
如果各位大佬之前有注意到具有相关功能的项目，请为我指路，万分感谢！！

**Comment by YangRucheng** [comment]
我看到 [LLOneBot](https://github.com/LLOneBot/LLOneBot) 支持 onebot11 协议。

其中支持 [全群禁言](https://llob.napneko.com/zh-CN/develop/api#:~:text=%E2%9C%94-,%E5%85%A8%E7%BE%A4%E7%A6%81%E8%A8%80,-set_group_whole_ban)。

你自己写个定时任务调用此API不就行了吗？
