### ISSUE TITLE
[Bug]: 请问怎么更改安装根目录

### ISSUE THREAD

**Issue by Nova-h** [LiteLoaderQQNT/LiteLoaderQQNT#442]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报主程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### QQNT 版本

9.9.16-28788

### LiteLoaderQQNT 版本 （或 Commit Id）

1.2.2

### 运行环境

Windows

### 重现步骤

用revokemsg安装 偷懒直接安装在了桌面但是不知道怎么修改本体目录位置 也不知道怎么卸载重装

### 期望的结果是什么？

希望能将本体路径修改到想要的位置 或者能卸载重装

### 实际的结果是什么？

设置界面本体目录只能进入路径 不能修改 也不知道怎么修改路径或者卸载重装到新的路径
![QQ20241028-095013](https://github.com/user-attachments/assets/6aea39cf-6caa-4a42-b56a-647bfe0d4c7a)

**Comment by huiyadanli** [comment]
使用RevokeMsgPatcher还原后移动RevokeMsgPatcher目录的位置到你期望的存放的地方，然后重新安装

**Comment by Nova-h** [comment]
> 1. 使用 RevokeMsgPatcher 还原
> 2. 移动 RevokeMsgPatcher 目录的位置到你期望的存放的地方
> 3. 重新安装

感谢 已解决

**Comment by Nova-h** [comment]
> 不就是改
> 
> > require(String.raw`*`);
> 
> 里的*么
> 
> ~话说顺手测了下路径好像不能有中文~ ~不对，是某个插件出问题了~ 算了懒得排查了

感谢 已解决

**Comment by devil233-ui** [comment]
> > 不就是改
> > > require(String.raw`*`);
> > 
> > 
> > 里的*么
> > ~话说顺手测了下路径好像不能有中文~ ~不对，是某个插件出问题了~ 算了懒得排查了
> 
> 感谢 已解决

草抱歉当时没注意看你用的是RevokeMsgPatcher ，居然也是差不多流程？
