### ISSUE TITLE
[Feat]: 换架构的微信4.0有可能做这种类似的插件吗

### ISSUE THREAD

**Issue by Ahahahala** [LiteLoaderQQNT/LiteLoaderQQNT#446]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

微信换架构了，能实现类似的插件吗

**Comment by baizhi958216** [comment]
换架构？

**Comment by singularity2000** [comment]
Windows微信也出electron重写的内测版了，支持深色模式

**Comment by baizhi958216** [comment]
是Qt哦，[Windows微信 4.0.0 内测版本更新：新增深色模式，改用Qt跨平台框架](https://linux.do/t/topic/229001)

**Comment by jiongjiongJOJO** [comment]
+1，挺想用微信的插件🤗🤗
