### ISSUE TITLE
[Feat]: 增加云黑系统♥️♥️福瑞控我草死你们😋😋

### ISSUE THREAD

**Issue by MCyudix** [LiteLoaderQQNT/LiteLoaderQQNT#656]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

云黑qq

**Comment by RetardedFatherlessPoorGayAnimals8964** [comment]
操你死妈，你妈大黑逼是不是也黑的进云黑了？操你妈臭逼，你个烂逼男性同性恋福瑞控对着你那个人不人鬼不鬼雄性小动物大屁眼子撸你那个3mm袖珍小牛子谁给你的资格在这里野狗乱叫我操你妈逼
