### ISSUE TITLE
[Feat]: 复制代码和发送卡片消息

### ISSUE THREAD

**Issue by KagaJiankui** [LiteLoaderQQNT/LiteLoaderQQNT#75]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

有没有可能在liteloader中实现卡片消息的解析、修改和发送？如果有可能的话，希望能实现相关API或加入相关功能

**Comment by zhanghua000** [comment]
发送卡片消息可能会被滥用，这个建议谨慎对待
考虑到有类似功能的手机 XPosed 模块 QAuxiliary 对这个功能的应对策略是实名记录发送者 QQ 号，我个人建议如果真要开发发送卡片消息的功能也要使用防范手段

**Comment by PRO-2684** [comment]
复制卡片消息已经有了，实现起来挺简单的；但是发送可能就挺麻烦的
