### ISSUE TITLE
[Feat]: 自定义表情

### ISSUE THREAD

**Issue by BAKAOLC** [LiteLoaderQQNT/LiteLoaderQQNT#82]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我确定这是一个从未被提出和实现过的功能。
- [X] 我已经在 [Issue Tracker](https://github.com/mo-jinran/LiteLoaderQQNT/issues) 以及 [Pull Request](https://github.com/mo-jinran/LiteLoaderQQNT/pulls) 中找过我要提出的功能，没有找到相同功能的ISSUE和PR。
- [X] 我已知晓并同意，此处仅用于建议新功能。若这个 Issue 是关于其他非主题的问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### 需要添加的功能内容

希望加入类似原本QQ的自定义表情包功能 ~~（隔壁某框架好像有人做了个类似的就等那个框架更新，这边是没有的）~~
大概就是可以直接指定文件夹或者提供配置表来在QQNT的聊天栏中追加对应的表情分页
我不会用js写界面之类的所以只能先来提个需求了（悲）
加到这里（或者直接把这个表情选择页用个新的直接整个改了？）
![Snipaste_2023-08-05_17-35-54](https://github.com/mo-jinran/LiteLoaderQQNT/assets/35646643/b40b5e8d-d63b-4b10-99d6-2514fb0ea731)

**Comment by xh321** [comment]
看起来已经有了类似的插件，可以看看？

**Comment by BAKAOLC** [comment]
> 看起来已经有了类似的插件，可以看看？

之前看到过有bcmRayCrazy-coder/stickerpp，但是那个实际使用不生效
然后Night-stars-1/LiteLoaderQQNT-Plugin-QSticker也有问题就没用

刚刚看的话现在轻量工具箱有这个功能了，基本符合使用需求，很好用
